### ISSUE TITLE
Get-MDEInvestigationPackage playbook retrives SAS URI but returns "expired token"

### ISSUE THREAD

**Issue by applefacts** [Azure/Azure-Sentinel#6142] opened 2022-09-12 17:26 UTC
**Describe the bug**

This playbook https://github.com/Azure/Azure-Sentinel/tree/master/Playbooks/Get-MDEInvestigationPackage
Is ran against a Sentinel Incident and it is able to retrieve the get investigation package download URI. However when I navigate to the URL I get a JSON error Message: "Expired token"

**To Reproduce**
1. Go to 'Sentinel Incident'
2. Click on 'Run Playbook (Preview)'
3. Select Get-MDEInvestigationPackage and click "Run"
![2022-09-12 10_23_24](https://user-images.githubusercontent.com/87787083/189718161-b2ce4d8b-358f-4fae-8c07-659f6896177a.jpg)

![2022-09-12 10_24_46](https://user-images.githubusercontent.com/87787083/189717786-eca1c1db-0171-4348-aebd-9b5ce487670b.jpg)

**Expected behavior**

URL from playbook is supposed to download the investigation package

**Screenshots**

See above

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Firefox
 - Version 104.0.2

**Additional context**
Permissions as per readme were granted to managed identity.

**Comment by BenjiSec** [comment] 2022-10-14 11:33
Hi @kevelife - we are currently investigating why there is error with expired token. in meantime you can utilize HTTP action as a workaround
![image](https://user-images.githubusercontent.com/61513156/195836396-79aaf4ce-92b8-4961-bd5b-40d70896f70a.png)

**Comment by BenjiSec** [comment] 2023-02-13 09:53
Update - API token to get investigation package expires couple of minutes after generating, so if you don't click on the link immediately, you will get "token expired" notification.

**Comment by v-mchatla** [comment] 2023-02-13 10:44
@BenjiSec - Thaks for the prompt response.
@applefacts - Closing this incident as its by design and please feel free to reopen if you need any further information on this.
Thanks

**Closed by v-mchatla** 2023-02-13 10:44 UTC
Labels: Playbook

**Comment by applefacts** [comment] 2023-02-13 18:01
> Update - API token to get investigation package expires couple of minutes after generating by design, so if you don't click on the link immediately, you will get "token expired" notification.

Hi @BenjiSec, I am clicking the package URL immediately and I am not waiting for it to expire.

**Comment by KrisDeb78** [comment] 2023-05-09 23:28
The token life is definitely too short for this use case - I've managed to download it clicking refresh on the incident page only during the second run (2 minutes); after the first, 5 minutes run, the token was already expired. I can see that the token life is something between 4-5 minutes in total, please correct me if I'm wrong. Anyway, as I said, it is way too short for the production use.
