### ISSUE TITLE
Analytics Rules "Excessive number of failed connections from a single source" have Blank IP Address Log and Inconsistent Descriptions

### ISSUE THREAD

**Issue by jeffrywu28** [Azure/Azure-Sentinel#10135] opened 2024-03-13 06:42 UTC
**Describe the bug**
Why your Log one of them is not showing IP? And inconsistent Alert Description number. it showing 5k but there is no indicator of 5k failure.

**To Reproduce**
1. Go to Sentinel
2. Click on alert "Excessive number of failed connections from" but not showing the IP. Alert is from Analytics Rules "Excessive number of failed connections from a single source (ASIM Network Session schema)"
3. Read The description Correctly and Click the log.

**Expected behavior**
It must have IP Address. We need truly information!

**Screenshots**
<img width="364" alt="image" src="https://github.com/Azure/Azure-Sentinel/assets/47622164/a46239f2-acd1-4f87-be48-25228fd02fd0">

<img width="708" alt="image" src="https://github.com/Azure/Azure-Sentinel/assets/47622164/ea4669a9-eb98-48c1-8bb9-b944a65ecc2d">

**Comment by jeffrywu28** [comment] 2024-03-13 06:45
Another Issue. this is hard to investigate
<img width="952" alt="image" src="https://github.com/Azure/Azure-Sentinel/assets/47622164/03b227d1-834c-4ba1-adab-5f727186d143">

**Comment by v-sudkharat** [comment] 2024-03-15 12:26
Hi @jeffrywu28, 
1. We have reproduced this issue from our end and able to see the IP address in alter title- 
![image](https://github.com/Azure/Azure-Sentinel/assets/132428394/aadda5b4-acf8-4c7a-b8a4-b6742440eade)

2. Regarding the Alter description, the value is showing 5k failure is threshould value, which is default set while creating the analytic rule, and this value is fetch to incident description once it gets generated. 
So, while creating the Analytic rule you can Modify the threshold to change the sensitivity of the rule: the higher the threshold, the less sensitive is the rule and less incidents will be generated- 
![image](https://github.com/Azure/Azure-Sentinel/assets/132428394/897dba28-1e6c-4066-a483-8fa010ce1a6c)

In above screenshot, we have kept the- `threshold = 100` and created the rule. 
So, when the incident gets generated the Alter description will be- 
`The client at address ( 192. . . . ) generated more than 100 failures over a 5 minutes time window, which may indicate malicious activity. `
You can also get more detailed info about incident, by using new tab feature- 
![image](https://github.com/Azure/Azure-Sentinel/assets/132428394/38f9c253-f533-4317-8411-9f374f823c81)

Please let us know your feedback on this. 
Thanks!

**Comment by v-sudkharat** [comment] 2024-03-19 08:31
Hi @jeffrywu28, We are waiting for your response on above comment. Thanks!

**Comment by v-sudkharat** [comment] 2024-03-21 06:39
Hi @jeffrywu28, Gentle Reminder: We are waiting for your response on this issue. If you still need to keep this issue active, please respond to it in the next 2 days. If we don't receive a response by 25-03-2024 date, we will be closing this issue. 		
Thanks!

**Comment by v-sudkharat** [comment] 2024-03-28 10:54
Hi @jeffrywu28, since we have not received a response in the last 5 days, we are closing your issue as per our standard operating procedures. If you still need support for this issue, feel free to re-open at any time. Thank you for your co-operation.

**Closed by v-sudkharat** 2024-03-28 10:54 UTC
Labels: Analytic Rules
