### ISSUE TITLE
The change to the Atlassian Jira Audit connector in PR6999 has broken it

### ISSUE THREAD

**Issue by cbqc** [Azure/Azure-Sentinel#7259] opened 2023-02-02 18:36 UTC
We stopped receiving Jira Audit records in our workspace at the end of December. The last one was ingested at 2022-12-29T19:40:00.347Z.

I have confirmed that the API is returning records via Postman when queried from this date:
![image](https://user-images.githubusercontent.com/85615685/216416254-9c693ee1-4aa7-4857-8d78-32230334bddc.png)

I redeployed the connector to ensure it wasn't a deployment-specific issue and manually updated the funcstatemarkerfile to the above time. The output reports that 0 records were processed:
![image](https://user-images.githubusercontent.com/85615685/216417152-d0b4a382-9a94-490f-a4b6-7ec878e5206d.png)

There doesn't seem to be enough diagnostic logging in place to tell where it's going wrong, but have attached the App Insights output with the storage account name redacted.
[JiraFunctionExecution.csv](https://github.com/Azure/Azure-Sentinel/files/10572245/JiraFunctionExecution.csv)

I can only see Requests and Responses from the Storage Account, nothing from the actual Jira API, so I don't know if it's even making the call correctly.

**Comment by cbqc** [comment] 2023-02-02 18:39
I think I may have spotted the issue... the while loop is never executing:
![image](https://user-images.githubusercontent.com/85615685/216419356-c9efde59-d9aa-44c5-99aa-258d0923ba4b.png)

**Comment by NikTripathi** [comment] 2023-02-03 14:04
Hi @cbqc We have find out the root cause and we have fixed the function app code which was causing the error. Can you please ask the customer to use the WEBSITE_RUN_FROM_PACKAGE value to below URL and restart the function.
Also if it resolves the issue please ask the customer to modify the state manager file. Update the value of function app maker file inside function marker share to the date this impact started so that customer won't face any data loss.
URL:- https://github.com/Azure/Azure-Sentinel/blob/v-ntripathi/AtlassianJiraFixIcM361594503/DataConnectors/AtlassianJiraAudit/JiraAuditAPISentinelConn.zip?raw=true

Impact start date:- Dec 30, 2022, 6:48PM GMT+5:30


![image](https://user-images.githubusercontent.com/87809732/216623007-02b61cf5-de88-4a14-bff0-704b9ce52175.png)

**Comment by cbqc** [comment] 2023-02-07 12:37
I'm afraid this has caused a different problem. The function has been failing since I pointed it at the new package:
![image](https://user-images.githubusercontent.com/85615685/217246710-15fab8e6-b5a3-4bf4-beb1-c90777bf7b7c.png)

**Comment by NikTripathi** [comment] 2023-02-09 06:46
Hi @cbqc We have fixed that change. Can you please restart your function app? It should work fine now.
Thanks.

**Comment by NikTripathi** [comment] 2023-02-10 11:25
Hi @cbqc  One of our customer has confirmed that their issue has been fixed. We have merged the updated fix. You can use below URL now.https://aka.ms/sentinel-jiraauditapi-functionapp

Thanks.

**Closed by NikTripathi** 2023-02-10 11:25 UTC
Labels: Connector
