### ISSUE TITLE
Transformation on Table ASimDnsActivityLogs not working

### ISSUE THREAD

**Issue by Blutsh** [Azure/Azure-Sentinel#9976] opened 2024-02-19 10:35 UTC
**Describe the bug**
Creating a Transformation on table _ASimDnsActivityLogs_ to filter out logs based on a simple condition :

```
source
| where DstIpAddr !startswith "192."
```

Does not work (Event are not being filtered even after few hours).

**To Reproduce**
1. Configure the "Windows DNS Events via AMA" from sentinel portal.
2. Check that logs are flowing by checking content of table _ASimDnsActivityLogs_ 
3. Test your KQL against the logs
4. Go to your log Analytics workspace > Tables
5. Select _ASimDnsActivityLogs_ > Edit Transformation
6. Assign the transformation to a WorkspaceWide DCR, insert the transformation (given above)
7. Wait for 30min (so the changes are effective)
8. Check that events are not filtered out as they should

**Expected behavior**
I should not see logs in Table _ASimDnsActivityLogs_  where DstIpAddr starts with "192."

**ARM Dcrs**

DCR generated by DataConnector "Windows DNS Events via AMA" :

```JSON

{
    "properties": {
        "immutableId": "dcr-3768b0cace0c4122b2b256db67d4e709",
        "dataSources": {
            "extensions": [
                {
                    "streams": [
                        "Microsoft-ASimDnsActivityLogs"
                    ],
                    "extensionName": "MicrosoftDnsAgent",
                    "extensionSettings": {
                        "Filters": []
                    },
                    "name": "ASimDnsActivityLogsTypeExtension"
                }
            ]
        },
        "destinations": {
            "logAnalytics": [
                {
                    "workspaceResourceId": "/subscriptions/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx/resourceGroups/rg_sentinel/providers/Microsoft.OperationalInsights/workspaces/lab-esxi",
                    "workspaceId": "xxxxxxxxxxxxxx",
                    "name": "DataCollectionEvent"
                }
            ]
        },
        "dataFlows": [
            {
                "streams": [
                    "Microsoft-ASimDnsActivityLogs"
                ],
                "destinations": [
                    "DataCollectionEvent"
                ]
            }
        ],
        "provisioningState": "Succeeded"
    },
    "location": "somewhere",
    "tags": {},
    "kind": "Windows",
    "id": "/subscriptions/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx/resourceGroups/RG_Sentinel/providers/Microsoft.Insights/dataCollectionRules/xxxxxxxxxxxxxx-ms-sentinel-asimdnsactivity",
    "name": "xxxxxxxxxxxxxx-ms-sentinel-asimdnsactivity",
    "type": "Microsoft.Insights/dataCollectionRules",
    "etag": "\"0a00f893-0000-1700-0000-65cf14f00000\"",
    "systemData": {
        "createdBy": "johndoe@doe.com",
        "createdByType": "User",
        "createdAt": "2024-02-16T07:55:26.3377829Z",
        "lastModifiedBy": "johndoe@doe.com",
        "lastModifiedByType": "User",
        "lastModifiedAt": "2024-02-16T07:55:26.3377829Z"
    }
}

```

WorkspaceWide DCR created trough the portal :

```JSON
{
    "properties": {
        "immutableId": "dcr-e899d9e9e6a94f999bbf6e03a5e33df1",
        "dataSources": {},
        "destinations": {
            "logAnalytics": [
                {
                    "workspaceResourceId": "/subscriptions/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx/resourcegroups/rg_sentinel/providers/microsoft.operationalinsights/workspaces/lab-esxi",
                    "workspaceId": "xxxxxxxxxxxxxx",
                    "name": "2a8df5c5fc844fdcbca44b214cdbc33c"
                }
            ]
        },
        "dataFlows": [
            {
                "streams": [
                    "Microsoft-Table-ASimDnsActivityLogs"
                ],
                "destinations": [
                    "2a8df5c5fc844fdcbca44b214cdbc33c"
                ],
                "transformKql": "source\n| where DstIpAddr !startswith \"192.\"\n"
            }
        ],
        "provisioningState": "Succeeded"
    },
    "location": "somewhere",
    "kind": "WorkspaceTransforms",
    "id": "/subscriptions/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx/resourceGroups/RG_Sentinel/providers/Microsoft.Insights/dataCollectionRules/DCR_WorkspaceWide_esxi",
    "name": "DCR_WorkspaceWide_esxi",
    "type": "Microsoft.Insights/dataCollectionRules",
    "etag": "\"0a00a2c1-0000-1700-0000-65cf1b1f0000\"",
    "systemData": {
        "createdBy": "johndoe@doe.com",
        "createdByType": "User",
        "createdAt": "2024-02-16T08:21:48.5212847Z",
        "lastModifiedBy": "johndoe@doe.com",
        "lastModifiedByType": "User",
        "lastModifiedAt": "2024-02-16T08:21:48.5212847Z"
    }
}
```

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Firefox / Edge

**Additional context**
I did test in multiple environments, I also did try to create a TransformKql in the DCR created by the dataconnector -> doesnt work aswell.

**Comment by t0neex** [comment] 2024-02-19 14:49
Can you please check on Tables page of Log Analytics Workspace? Do you have this error above of page?
![image](https://github.com/Azure/Azure-Sentinel/assets/100233276/d9af04ad-6300-4a0d-af78-b6a981e848a1)
I'm facing same issue with Syslog table for transforming CEF messages but its not working and writes CEF messages to my Syslog table as well. I just wonder are we facing same issue.

**Comment by t0neex** [comment] 2024-02-19 15:55
> > Hi @Blutsh, Can you please check on Tables page of Log Analytics Workspace? Do you have this error above of page? ![image](https://private-user-images.githubusercontent.com/100233276/305983437-d9af04ad-6300-4a0d-af78-b6a981e848a1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgzNTc4OTAsIm5iZiI6MTcwODM1NzU5MCwicGF0aCI6Ii8xMDAyMzMyNzYvMzA1OTgzNDM3LWQ5YWYwNGFkLTYzMDAtNGEwZC1hZjc4LWI2YTk4MWU4NDhhMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxOVQxNTQ2MzBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kYjM0YzMzYzM4OTcxMWVlMDViOWRhMGE3Njk2OWNjOWY4M2RhNGM0MDNiYWMwZDVlMjZkYzRiNzMyMGZlOTIzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.8aOwuGJcEkBqCb7eX8BGPvrbnRMYO3yv-B-lkKBICls) I'm facing same issue with Syslog table for transforming CEF messages but its not working and writes CEF messages to my Syslog table as well. I just wonder are we facing same issue.
> 
> Hello @t0neex, no I don't have this warning message on the table view, nor on the DCR view. I do have a blue informational message : ![image](https://private-user-images.githubusercontent.com/34598061/306011493-d4e4cac4-52c2-46a1-baad-d176796bdb20.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgzNTgzODAsIm5iZiI6MTcwODM1ODA4MCwicGF0aCI6Ii8zNDU5ODA2MS8zMDYwMTE0OTMtZDRlNGNhYzQtNTJjMi00NmExLWJhYWQtZDE3Njc5NmJkYjIwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE5VDE1NTQ0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA2ZTcwZjI2YjI4NWU5NGE1NjliOTcxMWE3MmM4ZTljMDRmMWFkYmQ3MDNjMTRkNzU5N2U3MzQ5MGUyNzAyN2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7zfwuKh9_YiYVyf4akPQvuL_3Y9PVhcl8Zw4c0Enmf0)
> 
> (By the way the link explicitly list the table "ASimDnsActivityLogs" as supported for ingestion time transformations)

Uhh okey, we're facing different issues. Thank you for your response, have a nice day :)

**Comment by v-sudkharat** [comment] 2024-02-21 13:36
Hi @Blutsh, Thanks for flagging this issue, we will investigate this issue and get back to you with some updates by 29-02-2024. Thanks!

**Comment by v-sudkharat** [comment] 2024-02-26 10:46
Hey @Blutsh, just want to check, while creating a DCR have you check the result get projected with your mentioned condition?
Could you please check it and let us know the result. 
Sharing screenshot for your reference, here we have taken table which we have available into workspace- 
![image](https://github.com/Azure/Azure-Sentinel/assets/132428394/6fb863b4-9379-461c-b183-5743bd74d07e)
And could you please share the sample data with us, so we can reproduce this issue from our end. 
Thanks

**Comment by v-sudkharat** [comment] 2024-02-27 06:25
@Blutsh, thank you for your response, we are investigating this issue and will share our mail to with you for sharing the data privately with us. Thanks!

**Comment by v-sudkharat** [comment] 2024-02-29 12:53
Hi @Blutsh, Could you please follow below steps from MS documentation, it looks the table schema has been created but the data is not written into it. So could you please check it and let us know if still facing the issue. - 
MS Doc link - https://learn.microsoft.com/en-us/azure/azure-monitor/logs/tutorial-logs-ingestion-portal
![image](https://github.com/Azure/Azure-Sentinel/assets/132428394/ce6d92c5-9aa0-499d-858f-eddcac2ca5ef)

**Comment by v-sudkharat** [comment] 2024-03-04 11:23
Hi @Blutsh, As per documentation you need the Microsoft.Insights/Telemetry/Write access to write the data into the tables. To address it could you please verify/follow the below steps and let us know if it's already compliant it in your end - 
1.Go to your created DCR rule- 
![image](https://github.com/Azure/Azure-Sentinel/assets/132428394/13ea3b2a-3b65-46b5-baf8-775fe087b77f)

2. Click on Access Control (IAM) and select Add role assignment- 
![image](https://github.com/Azure/Azure-Sentinel/assets/132428394/a8eb4af1-401c-4985-a550-15f80417fe66)

3. Select Monitoring Metrics Publisher > Next. You could instead create a custom action with the Microsoft.Insights/Telemetry/Write data action.
![image](https://github.com/Azure/Azure-Sentinel/assets/132428394/6fdecf29-4b2d-46d5-ad24-81a8dca51418)

4.Select User, group, or service principal for Assign access to and choose Select members. Select the application that you created and then choose Select.
![image](https://github.com/Azure/Azure-Sentinel/assets/132428394/72352c83-e982-457b-99da-5eac095fb607)

5. Select Review + assign and verify the details before you save your role assignment.
![image](https://github.com/Azure/Azure-Sentinel/assets/132428394/b5c027d2-bd54-4218-a9c9-a86475f6bfd4)

Once the roll gets added to DCR, please check the transformation/data filter is done for the table. 
If issue is still persisted in your end, please share your mail id with us so we can connect with you via a call and troubleshoot the issue further. 

Thanks!

**Comment by v-sudkharat** [comment] 2024-03-08 06:37
Hi @Blutsh, Thank you for provide detailed info with us. We will replicate this issue from our end and will update you. Thanks!

**Comment by v-sudkharat** [comment] 2024-03-12 06:58
Hi @Blutsh, we are reaching out to the respective DCR concerned team for this issue, once we receive an update on this, we will share with you. Thanks!

**Comment by v-sudkharat** [comment] 2024-04-12 06:28
Hi @Blutsh, Sorry for delay in response. Still, we are waiting response from our DCR team about the transformation, once we get any info from team, we will share with you via your shared mail ID or GitHub comment itself. 
Thanks!

**Comment by dvag-oliver-kretz** [comment] 2024-04-12 06:49
Hi,
we had a similar issue with our transformation. In our case we had 2 other dcrs, writing in the same log analytics workspace with the same stream (in our case Contsainer).
Do you have other DCRs which using Microsoft-ASimDnsActivityLogs as stream?
Microsoft advised us to use the transformation in all DCRs. (Or it is also possible to use one DCR also for the other sources)
I´m not sure but maybe it can help you...
Best Regards

**Comment by v-sudkharat** [comment] 2024-04-30 09:57
Hey @Blutsh, Could you please verify is there any other DCR rules has been already configured, which writing/sending the data into same table?
Please let us know once you verify, so we can share this update with team. 
Thanks!

**Comment by v-sudkharat** [comment] 2024-05-08 13:07
@Blutsh, thanks for sharing the info with us. We have forwarded these details to respective team and will update you once receive any information from team. Thanks!

**Comment by v-sudkharat** [comment] 2024-05-17 08:15
Hi @Blutsh, We received the response from our concern team, in above mentioned scenario there are 2 DCR has been configured for a source : 
1. The DCR created while configuring the (AMA) data connector.
![image](https://github.com/Azure/Azure-Sentinel/assets/132428394/9c9b00cb-07be-4161-9d13-99f1298f6b6b)

2. The DCR created for table transformation. 
![image](https://github.com/Azure/Azure-Sentinel/assets/132428394/6eb1bd5c-2ca2-41e5-b254-20bcbba305ee)

And both the transformation points to the same table. So, the transformation will not work to the table `ASimDnsActivityLogs` as you have the dedicated DCR configured, the second workspace DCR will not apply. 

Thanks!

**Comment by v-sudkharat** [comment] 2024-05-21 06:38
Hi @Blutsh, Waiting for your response on above comment and please let us know if any questions for us. Or can we close this issue? Thanks!

**Comment by v-sudkharat** [comment] 2024-05-23 12:43
Hi @Blutsh, Gentle Reminder: We are waiting for your response on this issue. If you still need to keep this issue active, please respond to it in the next 2 days. If we don't receive a response by 27-05-2024 date, we will be closing this issue. 		
Thanks!

**Comment by v-sudkharat** [comment] 2024-05-27 08:36
Hi @Blutsh, since we have not received a response in the last 5 days, we are closing your issue as per our standard operating procedures. If you still need support for this issue, feel free to re-open at any time. Thank you for your co-operation.

**Closed by v-sudkharat** 2024-05-27 08:36 UTC
Labels: Connector
