### ISSUE TITLE
Error when Deploying a single honeytoken

### ISSUE THREAD

**Issue by Goz123** [Azure/Azure-Sentinel#7731] opened 2023-04-03 09:20 UTC
Hi

While in the process of deploying HoneyTokens, when trying to add monitoring to the SOC -
"Add monitoring in the SOC (key: XXX)"
During the step - "Deploy a single honeytoken"

I get this error -

{"error":{"code":"NoResponse","message":"The server did not receive a response from an upstream server. Request tracking id '08585252349462813247572448420CU19'."}} Please assist to enable and add monitoring to the keys. 

Will appreciate any lead for help :)
Thank you.

**Comment by grsandeep** [comment] 2023-04-24 05:36
Mee too facing this issue while monitoring the SoC, any solution ?

@Goz123  - Pls let me know if you overcome this solution

**Comment by v-vdixit** [comment] 2023-06-05 09:51
Hi @Goz123 @grsandeep We are working with the solution owners on this, we will update you once we hear back from them, thanks!

**Comment by v-vdixit** [comment] 2023-06-19 07:35
Hi, we are still waiting to hear back from concerned team, thanks!

**Comment by v-vdixit** [comment] 2023-06-26 11:42
Hi @grsandeep @Goz123 thanks for your patience please ensure you have admin access to install and use this solution and refer to this documentation - [Honey Tokens Solution](https://github.com/Azure/Azure-Sentinel/blob/master/Solutions/HoneyTokens/README.md) to troubleshoot from your end, we are working on with the team will update you shortly, thanks!

**Comment by v-vdixit** [comment] 2023-07-03 10:43
Hi @grsandeep and @Goz123 we are waiting for your confirmation on this, please provide an update in the next 2 days else we will have to close this issue as per our standard procedure, thanks!

**Comment by Goz123** [comment] 2023-07-05 06:50
Hi @v-vdixit 
Checked and i have full admin access.
Also, followed the documentation with same result, same error.
Can we connect and try to resolve it?

Thanks.

**Comment by v-vdixit** [comment] 2023-07-05 13:02
Sure @Goz123 please let me know of your availability, this is my email v-vdixit@microsoft.com, thanks!

**Comment by v-vdixit** [comment] 2023-07-10 10:57
Hi @Goz123 as mentioned by you in mail, we will connect with you this week to resolve this, thanks!

**Comment by v-vdixit** [comment] 2023-07-12 10:55
Hi @Goz123 we have scheduled the meeting, thanks!

**Comment by v-vdixit** [comment] 2023-07-14 05:40
The meeting has been scheduled for Monday, 17th July 2023, will provide updates post that discussion, thanks!

**Comment by v-vdixit** [comment] 2023-07-19 09:50
Hi @Goz123 as per our discussion in the meeting we have taken note of your issue and also provided you with the demo video, as per the updates we have the issue you are facing is concerned with access or configuration only please check and update us if you have heard anything back on this from your team, thanks!

**Comment by v-vdixit** [comment] 2023-07-24 05:58
Gentle Reminder: We are waiting for your response on this issue. If you still need to keep this issue active, please respond on it in the next 2 days. If we don't receive response, we will be closing this issue as per our standard procedures, thanks!

**Comment by v-amolpatil** [comment] 2023-07-26 15:14
Since we have not received a response in the last 5 days, we are closing your issue #7731 as per our standard operating procedures. If you still need support for this issue, feel free to re-open at any time. Thank you for your co-operation.

**Comment by v-rbajaj** [comment] 2023-07-27 10:43
We will soon reschedule a call and have a discussion around it.

**Comment by v-rbajaj** [comment] 2023-07-31 12:00
We will soon reschedule a call and have a discussion around it.

**Comment by v-rbajaj** [comment] 2023-08-07 13:13
We had a call with Author and had a detailed discussion to understand the issue, we will again have a call with Author tomorrow.

**Comment by v-rbajaj** [comment] 2023-08-09 09:59
We had a call again with the author and we will continue the discussion on this issue on Monday.

**Comment by v-muuppugund** [comment] 2023-08-21 06:42
Hi Goz123 ,We are working on this after troubleshooting call on 16Aug23 and will provide update ASAP

**Comment by Goz123** [comment] 2023-08-21 07:24
Thank you for the update

**Comment by v-muuppugund** [comment] 2023-08-26 16:37
Hi Goz123 ,understood the cause of the issue and scheduled call for the same on 28/08/2023.

**Comment by v-muuppugund** [comment] 2023-09-07 06:54
Hi Goz123 ,Issue got resolved  28/08/2023 after making configuration and other steps and detailed explanation of issue details, will be marking it as resolved and will follow up on changes to be reflected in main template.

**Closed by v-muuppugund** 2023-09-07 06:54 UTC
Labels: Workbook

**Comment by Goz123** [comment] 2023-09-07 07:22
Thank you for the help

**Comment by plim2282** [comment] 2023-12-05 14:27
What was the solution to this issue?
