### ISSUE TITLE
Installer script breaks rsyslog due to bad SELinux context on new config file

### ISSUE THREAD

**Issue by pagienge** [Azure/Azure-Sentinel#11047] opened 2024-08-29 19:53 UTC
**Describe the bug**
Running DataConnectors/Syslog/Forwarder_AMA_installer.py according to the docs causes rsyslog to not run any longer, at least on RHEL9, potentially any SELinux enabled VM.

**To Reproduce**
1. Deploy a stock RHEL 9 system
2. Run the installer per documents ( sudo wget -O Forwarder_AMA_installer.py
https://raw.githubusercontent.com/Azure/Azure-Sentinel/master/DataConnectors/Syslog/Forwarder_AMA_installer.py&&sudo
python Forwarder_AMA_installer.py
3. rsyslog will now no longer run, even if editing the rsyslog.conf file back to 'stock'

**Expected behavior**
rsyslog.service runs

**Screenshots**
![image](https://github.com/user-attachments/assets/4f557b9e-060f-4dc5-987d-9e37715bfcd0)

 - OS: RHEL 9

**Additional context**
The SELinux context of the file is incorrect due to the way the installer creates/copies the file around.
# ls -alFZ /etc/rsyslog.*
-rw-r--r--. 1 root root unconfined_u:object_r:admin_home_t:s0 3380 Aug 29 19:35 rsyslog.conf
-rw-r--r--. 1 root root unconfined_u:object_r:etc_t:s0        3380 Aug 29 19:33 rsyslog.conf.bak

Running 'restorecon -v /etc/rsyslog.conf' will restore functionality.

Alternatively - it would probably be better to create a /etc/rsyslog.d drop-in file as opposed to editing the base config, given that this is exactly the purpose of .d directories.  If the chosen route is to keep editing the config, either actually edit the file (import fileinput perhaps?) vs creating a new copy and then overwriting, or make sure to deal with selinux context.

**Comment by garis** [comment] 2024-08-30 07:24
Workaround is to use `sudo chcon -t syslog_conf_t /etc/rsyslog.conf` to restore the original SELinux context after running the script.
Seems to work in my test machine but needs more testing.

**Comment by pagienge** [comment] 2024-09-03 13:03
Hi @garis , I also provided the workaround

restorecon -v /etc/rsyslog.conf

That being said, this shouldn't break a built-in service out of the box.  We are seeing support cases regarding this.

**Comment by v-rusraut** [comment] 2024-09-16 10:06
Hi @pagienge, Thanks for flagging this issue, we will investigate this issue and get back to you with some updates. Thanks!

**Comment by v-rusraut** [comment] 2024-09-18 06:45
Hi @pagienge,
We reached out to respective team for this issue, and as a team mentioned that you need to raise a support case for this issue, as support team have the backend access to find the root cause of this issue. and if required the support team can forward the ticket to respective teams.
So, we are closing this issue from GitHub. If you still need support for this issue, feel free to re-open it any time. Thank you for your co-operation.

**Closed by v-rusraut** 2024-09-18 06:45 UTC
Labels: AMA_Connector
