### ISSUE TITLE
Manually ASIM Deployment - Failed to validate, Conflict

### ISSUE THREAD

**Issue by rcegan** [Azure/Azure-Sentinel#8623] opened 2023-07-25 03:19 UTC
**Describe the bug**
Upon trying to deploy ASIM parsers via the 'Deploy to Azure' button and filling out the required parameters, a 'Conflict' error appears with the following error: (workspace, location and resource group have been omitted)

```
The resource '<SENTINELWORKSPACE> already exists in location <LOCATION> in resource group <RESOURCEGROUP>. A resource with the same name cannot be created in location <LOCATION>. Please select a new resource name.
```
Upon giving it a different name, it creates a new LAW in the designated resource group.

**To Reproduce**
1. Go to list of parsers https://github.com/Azure/Azure-Sentinel/tree/master/ASIM
2. Deploy any of them
3. Fill out the workspace name in the 'Workspace' field and pick the correct resource group containing the LAW
4. Deploy
5. 
**Expected behavior**
The parsers should deploy into the targeted workspace and become available for query.

**Screenshots**
<img width="204" alt="image" src="https://github.com/Azure/Azure-Sentinel/assets/5835816/3242c8a9-94f1-4a7a-bd53-315a753ec9d8">

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Edge
 - Version: 115

**Additional context**
I have all required permissions to deploy this content.

**Comment by v-rbajaj** [comment] 2023-07-26 12:19
Hi @rcegan, we are checking on this and we will provide an update soon.

**Comment by v-rbajaj** [comment] 2023-07-28 10:32
Hi @rcegan, waiting for update from concerned team, once we receive an update will let you know.

**Comment by v-rbajaj** [comment] 2023-08-01 12:49
Hi @rcegan, waiting for update from concerned team, once we receive an update will let you know.

**Comment by v-rbajaj** [comment] 2023-08-04 12:10
Hi @rcegan, we are still waiting for update from concerned team, we will get back to you once there is an update.

**Comment by v-rbajaj** [comment] 2023-08-09 09:40
Hi @rcegan, we are still waiting for update from concerned team, we will get back to you once there is an update.

**Comment by rcegan** [comment] 2023-08-13 06:37
I was able to work around the problem by deploying the resources to a different location than the log analytics workspace itself. Solves my issue but I suspect that's probably not the intended behaviour

**Comment by v-rbajaj** [comment] 2023-08-16 11:47
> I was able to work around the problem by deploying the resources to a different location than the log analytics workspace itself. Solves my issue but I suspect that's probably not the intended behaviour

According to the error message, it is working as expected.

**Comment by vakohl** [comment] 2023-08-18 13:29
@rcegan thanks for raising this issue. Can you please share the location details where it failed and where it worked for you?

**Comment by rcegan** [comment] 2023-08-20 06:36
I was working with Australia Southeast and Australia East. Deploying to Australia Southeast, with the log analytics workspace in the same location, the deployment failed (due to a resource already existing in that location - the workspace itself). Picking a different location (Australia East) it appeared to work fine.

**Comment by azurekid** [comment] 2023-09-18 07:30
Hi, This behavior is as expected due to the following reason.
When deploying the ASIM parsers using the ARM templates a `POST` request is done at the background.

Because the ASIM parsers already exists, this will result in an error as described above.

There are 2 workarounds to remediate this issue:
- Remove the existing ASIM parsers for the workspace using the Microsoft PowerShell [script](https://github.com/Azure/Azure-Sentinel/tree/master/ASIM/dev/Delete-SentinelFunction)
- Deploy the updated parsers using the API using the `UPDATE` method.

It is more an issue related to Log Analytics than Microsoft Sentinel or ASIM as they are dependent on Log Analytics.

What I can do is create a PowerShell script that updates the ASIM parsers is they already exists and use the ASIM yaml files as input. Or create and ARM template that uses a Script Extension to run the PowerShell script in a different context.

This might need some extra permissions in the Azure Subscription / Resource Group but need to validate this first.

@rcegan @vakohl

**Comment by vakohl** [comment] 2023-09-22 17:08
@rcegan I created a new workspace, deployed [Process Event](https://aka.ms/ASimProcessEventDoc) parsers multiple times on same workspace. I didn't got that error. Am I missing anything that you tried? What schema parser you were trying to deploying. Can you please retry on a new and on the same workspace you previously tried, see if you are still getting that error?

**Comment by v-rbajaj** [comment] 2023-09-27 08:56
Hi @rcegan, 

Gentle Reminder: We are awaiting for your response on this issue. If you still need to keep this issue active please respond on it in the next 2 days. If we don't receive response, we will be close this issue.

**Comment by jusso-dev** [comment] 2023-09-27 22:01
Sorry to add to the noise, but I'm having the exact same problem. Tried deploying all ASIM parsers and then just one-by-one, same error message "Conflict"

![image](https://github.com/Azure/Azure-Sentinel/assets/16183422/5f07dcd2-d92e-4ed0-b134-6b6a3ab4782a)

I've tried putting the LAW in Australia Southeast and the LAW in Australia East, and also putting them in the same region, no difference to the output.

Drilling into the error message isn't any more help, just states eTAG for specific error was outdated

newer data exists. If you are using eTag please use the latest one and try again in a few minutes. Operation Id: '4918a525df68776dd0a7063aaa6db6dd' (Code: NewerDataExists)

**Comment by vakohl** [comment] 2023-11-23 12:03
@rcegan @jusso-dev FYI, this issue is being investigated.

**Comment by vakohl** [comment] 2023-12-06 13:08
@rcegan @jusso-dev @azurekid 
This issue is still being looked into. This seems more of Log Analytics issue than Sentinel, we are working with concerned teams to get this fixed.

**Comment by vakohl** [comment] 2024-05-15 10:31
tagging related issue, raised by another user - https://github.com/Azure/Azure-Sentinel/issues/10481

**Comment by frendsick** [comment] 2024-08-29 15:36
The root cause of the issue is that each parser deployment script deploys the Log Analytics workspace before deploying the saved search. The conflict happens when tens of parser deployment ARM templates are trying to deploy the Log Analytics workspace at the same time.

The current version of ASIM parser deployment could create a new Log Analytics workspace, which could be unwanted behavior. I would expect the ASIM parser deployment ARM template only to create parsers for the already existing Log Analytics workspace and not create another one if I, for example, type the workspace name wrong into the template.

The issue does not relate to the existing versions of the ASIM parsers, as I have seen this issue occur when deploying the ASIM parsers for the first time to a given Log Analytics workspace. The error messages always refer to the workspace, which is constantly redeploying itself by the referenced ARM templates. Also, the referenced parser templates always seem to define `"etag": "*"`, meaning they always overwrite the existing resource.

I made an example commit on how the issue could be solved by only verifying the Log Analytics workspace exists by declaring the workspace as an [existing resource](https://learn.microsoft.com/en-us/azure/azure-resource-manager/templates/resource-declaration#declare-existing-resources): 0986d7f

@vakohl, what do you think of this solution? Would you like me to implement it for the other parsers as well, or would you prefer to tackle the issue in-house?

**Comment by hitem** [comment] 2024-10-17 13:33
Any news on this?
Ive deployed a few sentinels the last few months and all of them had these issues. I started deploying each entity by itself and i have about 70% success and 30% fails with "Newer data exists". 

Here is when running the DNS asim by itself as an example:
![Image](https://github.com/user-attachments/assets/806dc15f-c964-4bd8-9740-320e5fd5b965)
"Failed to modify resource '/subscriptions/xxxxxxxxxxxxxxx' Microsoft.OperationalInsights/workspaces/xxxxxxxxx', newer data exists. If you are using eTag please use the latest one and try again in a few minutes"

**Comment by frendsick** [comment] 2024-10-18 11:00
I found a way to deploy the saved search without deploying the Log Analytics workspace and without using the `languageVersion` 2.0. I believe this should be the least possible change for each parser ARM template file to fix the issue of unnecessarily redeploying the Log Analytics workspace.

Example: 5aa3b7537996d7a4abfb31e352d3f4b3b366d827

I will prepare the required changes for the parser ARM templates and create a PR.

**Closed** 2024-11-13 05:19 UTC
Labels: ASIM
