### ISSUE TITLE
Failing to Deploy 

### ISSUE THREAD

**Issue by GodOfNekos** [Azure/Azure-Sentinel#10551] opened 2024-05-30 09:44 UTC
Hi All,

Trying to test and deploy this to Sentinel but when im attempting to deploy im consistently getting the below. ive followed in some of the other issues which ive now resolved but i cannot get past this crowdstrike playbook, is there anyway to bypass it? or to fix and deploy.

![image](https://github.com/Azure/Azure-Sentinel/assets/15893709/f767b411-638c-4c5b-9f55-19367fda4084)

**Comment by v-rusraut** [comment] 2024-06-04 11:41
Hi @GodOfNekos, Thanks for flagging this issue, we will investigate this issue and get back to you with some updates by 07-06-2024. Thanks!

**Comment by GodOfNekos** [comment] 2024-06-07 14:17
Hi @v-rusraut Has there been any updates yet, as noticed today after syncing im not able to even get past the login attempts to try and deploy, now getting the below

![image](https://github.com/Azure/Azure-Sentinel/assets/15893709/3532dff6-6be6-4e29-9ae7-516df16c9355)

I would like to be able to get this deployed ASAP how can i go about that?

**Comment by v-rusraut** [comment] 2024-06-10 08:14
Hi @GodOfNekos,
This error occurred due to the version of Az.Account has been increased. Downgrading to version 2.19.0 of Az.Accounts will resolve the issue. Use below command. 
Install-Module -Name Az.Accounts -RequiredVersion 2.19.0 -Force
Thanks

**Comment by GodOfNekos** [comment] 2024-06-12 10:49
@v-rusraut Im not a dev, where do i put this to get it working?, i just want to be able to deploy to a test environment right now for some R&D but not able to do that as i cannot deploy at all. unfortunately not my area of expertise and documentation is not clear on how to resolve these kinds of issues.

**Comment by GodOfNekos** [comment] 2024-06-12 12:48
NVM fixed it, now just awaiting fix for crowdstrike error, when can this be expected as it is already beyond 07-06-2024 or was that meant to be 06-07-2024?

**Comment by v-rusraut** [comment] 2024-06-13 11:33
Hi @GodOfNekos,
There is custom deployment option available to deploy the playbook.
Please refer attachment which contain steps to deploy playbook using custom deploy option.
[CustomDeploymentsteps.docx](https://github.com/user-attachments/files/15818482/CustomDeploymentsteps.docx)

Please refer readme file for your reference.
https://github.com/Azure/Azure-Sentinel/blob/master/Playbooks/CrowdStrike/Playbooks/CrowdStrike_ResponsefromTeams/readme.md

Thanks

**Comment by GodOfNekos** [comment] 2024-06-13 13:02
@v-rusraut Unable to open document for Custom Deployment due to the Information Management Rights.

Finally got to a point with the deployment after removing content which is not needed for my environment. But failing right at the end of the deployment now. Can you let me know what the fix is for this.

![image](https://github.com/Azure/Azure-Sentinel/assets/15893709/d7ff3408-b5bb-4214-84cf-fc76e8f111c2)

**Comment by v-rusraut** [comment] 2024-06-14 08:46
Hi @GodOfNekos,
Please provide detail steps which you are following for deployment, so we can reproduce this issue.
Are you using Sentinel Repositories option to deploy this playbook ?
<img width="615" alt="image" src="https://github.com/Azure/Azure-Sentinel/assets/126679503/fafb95a1-69a5-4523-b8da-881d9a0d6438">
Thanks

**Comment by GodOfNekos** [comment] 2024-06-14 09:24
Hi @v-rusraut 
I have just been following the https://github.com/Azure/Azure-Sentinel/blob/master/GettingStarted.md and using the Sentinel Repositories on Azure. The only thing i have done which was different from the instructions was not creating a fork of the Repo, as this was intentionally going to be a test environment, i didnt want variables to change too much while i worked on how to deploy and finding out what was actually useful for my environments.

**Comment by v-rusraut** [comment] 2024-06-21 05:34
Hi @GodOfNekos,
Need more time to investigate this issue, we will update you.

**Comment by v-sudkharat** [comment] 2024-07-02 10:04
> @v-rusraut Unable to open document for Custom Deployment due to the Information Management Rights.
> 
> Finally got to a point with the deployment after removing content which is not needed for my environment. But failing right at the end of the deployment now. Can you let me know what the fix is for this.
> 
> ![image](https://private-user-images.githubusercontent.com/15893709/339369061-d7ff3408-b5bb-4214-84cf-fc76e8f111c2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk5MTM4NDgsIm5iZiI6MTcxOTkxMzU0OCwicGF0aCI6Ii8xNTg5MzcwOS8zMzkzNjkwNjEtZDdmZjM0MDgtYjViYi00MjE0LTg0Y2YtZmM3NmU4ZjExMWMyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAyVDA5NDU0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI2ODljZjJhMmFkMmY1ZGI4OTIzODVmMzg5ZTVmY2U4YTQxOWRlZDI5YzBiYTc2YThlYTJiNzk1NDI2MWNjNjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.AQeNjorghDNNsIkYUX-L24giJ5Z3BHy1I77qlyLNIvg)

Hi @GodOfNekos, based on your shared screenshot, you're getting error after perform operation to Main/master branch. Which is not accessible. 
Please correct if I'm wrong, you're planning to deploy the contents (Playbook, workbook, Solution, etc.) into your azure sentinel portal? 
Or you want to contribute this repro? but while committing the file your getting error's? 

Kindly let us know your inputs on it, it would be really helpful for us to provide resolution to your issue. Thanks!

**Comment by GodOfNekos** [comment] 2024-07-02 10:55
@v-sudkharat I am trying to deploy to my Sentinel workspace.

**Comment by v-sudkharat** [comment] 2024-07-02 11:38
@GodOfNekos, thank you for your response. 
One of the customers was facing a similar issue, like the one you are currently experiencing: https://github.com/Azure/Azure-Sentinel/issues/9876. As a resolution, we provided a repository link containing the deployable ARM template format. Below, I am sharing the Microsoft documentation and the repository link with you :
MS doc - https://learn.microsoft.com/en-us/azure/sentinel/ci-cd-custom-deploy?tabs=github
Sample repo - https://github.com/SentinelCICD/RepositoriesSampleContent

I Hope it help you. Kindly let us know if you have any queries or above links help you to resolve issue. 
Thanks!

**Comment by v-sudkharat** [comment] 2024-07-04 08:27
Hi @GodOfNekos, Waiting for your response on above comment, kindly let us know if anything for us. Thanks!

**Comment by v-sudkharat** [comment] 2024-07-08 08:15
Hi @GodOfNekos, Gentle Reminder: We are waiting for your response on this issue. If you still need to keep this issue active, please respond to it in the next 2 days. If we don't receive a response by 10-07-2024 date, we will be closing this issue. 		
Thanks!

**Comment by v-sudkharat** [comment] 2024-07-10 06:40
Hi @GodOfNekos, since we have not received a response in the last 5 days, we are closing your issue as per our standard operating procedures. If you still need support for this issue, feel free to re-open at any time. Thank you for your co-operation.

**Closed by v-sudkharat** 2024-07-10 06:40 UTC
Labels: help wanted
