### ISSUE TITLE
Bug: Crowdstrike analytics rule not working

### ISSUE THREAD

**Issue by hazcod** [Azure/Azure-Sentinel#6631] opened 2022-11-15 12:38 UTC
**Describe the bug**

The current CrowdStrike analytics rule only uses the table which is used by the Crowdstrike agent source.
It does not use the Falcon Data Replicator, which is the other S3 source method also in the Crowdstrike package.

I've managed to build a detection rule which triggers on data replicator detections:

```kusto
CrowdstrikeReplicatorLogs_CL
     | where EventType_s == "Event_ExternalApiEvent"
     | extend customFields=parse_json(custom_fields_message_s) 
     | where customFields["ExternalApiType"] == "Event_DetectionSummaryEvent"
     | summarize by Timestamp=unixtime_milliseconds_todatetime(tolong(customFields["UTCTimestamp"])),
        Name=tostring(customFields["DetectName"]),
        Hostname=tostring(customFields["ComputerName"]),
        Severity=tostring(customFields["SeverityName"]),
        Tactic=tostring(customFields["Tactic"]),
        Technique=tostring(customFields["Technique"]),
        Description=tostring(customFields["DetectDescription"]),
        User=tostring(UserName_s),
        LocalIP=tostring(customFields["LocalIP"])
;
```

**To Reproduce**
1. Install Crowdstrike source
2. Setup the S3 replicator
3. Install the built-in analytics rule(s)
4. Never see anything happening since the table used keeps empty

**Expected behavior**
All analytics rules working.

**Comment by v-vdixit** [comment] 2023-05-05 05:10
Hi @hazcod are you still facing this issue, please confirm, thanks!

**Comment by v-rbajaj** [comment] 2023-06-07 12:01
We wanted to check on the status of Issue https://github.com/Azure/Azure-Sentinel/issues/6631 . The issue is pending for more than x days. Please let us know if you need any assistance to review this Issue. As per our standard operating procedures if no response is received in the next 7 business days, we will close this Issue. Thank you for your cooperation.

**Comment by v-vdixit** [comment] 2023-06-19 07:31
Hi @hazcod we are working with the concerned team, will update you once we hear back from them, thanks!

**Comment by v-vdixit** [comment] 2023-06-26 12:39
Hi @hazcod we are still waiting for update, will update you by end of this week, thanks!

**Comment by v-vdixit** [comment] 2023-07-03 10:48
Hi @hazcod can you please provide us details on whether your concern is with an existing rule or you are looking for a new rule to be added to the solution, thanks!

**Comment by hazcod** [comment] 2023-07-03 10:54
@v-vdixit It's the existing rule for CrowdStrike.

**Comment by v-vdixit** [comment] 2023-07-10 10:10
Hi @hazcod can you please provide a link for this rule, we are unable to locate it in the solution, thanks!

**Comment by v-vdixit** [comment] 2023-07-17 04:10
Gentle Reminder: We are waiting for your response on this issue. If you still need to keep this issue active, please respond on it in the next 2 days. If we don't receive response, we will be closing this issue as per our standard procedures, thanks!

**Comment by hazcod** [comment] 2023-07-17 06:54
The analytics rules in Content Hub refer to table `CrowdStrikeFalconEventStream`, which does not exist/fill up when using CrowdStrike Falcon Data Replicator. It uses `CrowdstrikeReplicatorLogs_CL`

**Comment by v-vdixit** [comment] 2023-07-17 13:22
Thanks for the update @hazcod we will discuss with the team and update you for same.

**Comment by v-vdixit** [comment] 2023-07-20 12:45
Hi @hazcod we are discussing this with the team, will raise PR with changes by 25th July 2023, thanks!

**Comment by v-vdixit** [comment] 2023-07-24 11:28
Hi @hazcod we need some time to check on this rule so we will not be raising the PR currently, will provide you update by 27th July 2023, thanks!

**Comment by v-muuppugund** [comment] 2023-07-28 11:56
Hi @hazcod we need some time to check on this rule so we will not be raising the PR currently, will provide you update by 04th Aug2023, thanks!

**Comment by v-muuppugund** [comment] 2023-08-02 02:42
Hi @hazcod we need some time to check on this rule so we will not be raising the PR currently, will provide you update once we are working on it.

**Comment by v-muuppugund** [comment] 2023-08-04 12:17
We are adding this item in our backlog as a feature request ,so closing this issue.

**Closed** 2023-08-04 12:18 UTC
Labels: enhancement, Detection
