### ISSUE TITLE
Duplicated logs ingested into Sentinel with OCI (Azure Functions) Data Connector

### ISSUE THREAD

**Issue by fa-clavis** [Azure/Azure-Sentinel#10863] opened 2024-07-23 19:41 UTC
**Describe the bug**
Hello team,

When I was going to model and create some analytics rules for a client, I noticed that there were multiple logs with the same "id_g" field populated into the OCI_Logs_CL table.

This "id_g" field (in OCI logs it's the eventID) is the unique identifier for which every alert receives, so there shouldn't be multiple logs with the same ID in Sentinel.
Source: https://docs.oracle.com/en-us/iaas/Content/Audit/Reference/logeventreference.htm

I have installed the default Azure Functions with the ARM template, while I have crosschecked multiple eventIDs in the OCI audit logs, I'm not sure why the same log is being populated 2,3,5, 30 times or more. 

See the attached screenshots to understand the issue better.

P.S. I suspected something was odd with the connector because the amount of logs that's being ingested because the amount of logs that are produced in OCI is much less than the client's AWS environment.

**To Reproduce**
1. Install the data connector via ARM: Oracle Cloud Infrastructure (using Azure Functions)
2. Create all the required backend logging on the OCI side
3. Insert all the client details in the template and in "CursorType" instead of "group", insert "partition"
4. Wait for the logs to populate into the table
5. In the Sentinel Workspace, query the following table "OCI_Logs_CL" and look for the eventIDs in the "id_g" column

**Expected behavior**
The expected behavior is to ingest each eventID once and not multiple times.

**Screenshots**
![image](https://github.com/user-attachments/assets/475edb4f-7f33-4f70-a466-c50aec7f064c)
![image](https://github.com/user-attachments/assets/81746e4e-f8b0-4bf5-a508-8a2859543ef1)
![image](https://github.com/user-attachments/assets/a6e96aa8-3152-4da4-917b-0b57e7b09b23)
![image](https://github.com/user-attachments/assets/82c46630-e276-4f1e-847e-159f8cc37633)
![image](https://github.com/user-attachments/assets/18798d04-20f5-48e2-864d-ba4a67a6afc1)

**Additional context**

To install and configure the data connector, I used the following resources: 
1. https://docs.oracle.com/en/learn/stream-oci-logs-to-azure-sentinel/index.html#related-links
2. https://learn.microsoft.com/en-us/azure/sentinel/data-connectors/oracle-cloud-infrastructure

While the log is unique within the Audit Log service, I strongly believe there is something wrong with the Function App or the Python script where the cursor isn't being set up correctly as it pages through the logs.

I believe the problem is somewhere near this line in the main.py file:
https://github.com/Azure/Azure-Sentinel/blob/296f272801f36b1945cc2b921d1ec55746617ac4/Solutions/Oracle%20Cloud%20Infrastructure/Data%20Connectors/AzureFunctionOCILogs/main.py#L131

**Comment by fa-clavis** [comment] 2024-07-29 12:41
Hello team,
Any updates regarding this issue?

**Comment by v-sudkharat** [comment] 2024-08-01 11:52
Hey @fa-clavis, Thanks for flagging this issue, we will investigate this issue and get back to you with some updates. Thanks!

**Comment by fa-clavis** [comment] 2024-08-08 13:21
Hello @v-sudkharat, any updates regarding this issue?

**Comment by v-sudkharat** [comment] 2024-08-09 11:17
Hey @fa-clavis, We are checking the function code for duplicate ingestion of data, just want to know, it's possible to you to share OCI demo account with us? so we can check our changes. Or please let us also know if you have any test workspace into your environment where you can test our change. Thanks!

**Comment by fa-clavis** [comment] 2024-08-09 12:46
Hello @v-sudkharat , I talked with the client here, and they don't have a test environment available for OCI, however, they prefer to do the troubleshooting in a quick meet.
Is there any way we can schedule this meeting through e-mail or Teams?

**Comment by v-sudkharat** [comment] 2024-08-12 10:53
Hi @fa-clavis, let us check with our team to validate some changes, which required the OCI env. once it gets validated will update you. Thanks!

**Comment by fa-clavis** [comment] 2024-08-12 13:52
Hello @v-sudkharat, great news!
Hope it gets fixed ASAP!

**Comment by v-sudkharat** [comment] 2024-08-13 09:39
Hi @fa-clavis, Could you please share few events generated with same id_g with us via a mail - v-sudkharat@microsoft.com
to understand the duplication of data in each event. 
![image](https://github.com/user-attachments/assets/261f116d-57db-4e07-bccc-745ffa5a9629)

**Comment by v-sudkharat** [comment] 2024-08-27 06:23
Hi @fa-clavis, Just want to check with you, Is there any multiple function app deployed into the environment and point towards the same workspace?

**Comment by v-sudkharat** [comment] 2024-09-02 06:46
@fa-clavis, Waiting for your response on above comment, so based on that we can reach out to respective team. Thanks!

**Comment by v-sudkharat** [comment] 2024-09-04 10:22
Hi @fa-clavis, Any response for us?

**Comment by fa-clavis** [comment] 2024-09-04 11:54
Hello @v-sudkharat, sorry for the delay.
No, there is only 1 function app which is now in the "stopped" status.

![image](https://github.com/user-attachments/assets/7437dca5-3367-41bb-971f-6a3fbc6204cc)

**Comment by v-sudkharat** [comment] 2024-09-10 06:06
@fa-clavis, thank you for the update, we are connecting with our concern data connector team for this issue, we will keep you updated.  Thanks!

**Comment by fa-clavis** [comment] 2024-09-19 17:45
Hello @v-sudkharat, any updates regarding this issue?

**Comment by v-sudkharat** [comment] 2024-09-23 08:15
Hi @fa-clavis, We are still in connect with appropriate data connector team for this issue, and we will once get back to you with some update from them. 
And may I know is there any support case raise by you, if yes, could you please share the ticket ID with us. Thanks!

**Comment by fa-clavis** [comment] 2024-09-23 21:28
Hello @v-sudkharat, alright, no problem!
No, there is no support case raised by the client, as they recently changed their support plans.
Thanks!

**Comment by v-sudkharat** [comment] 2024-09-24 11:01
Hi @fa-clavis, 

With your shared data I can see there are slight change in time **oracle_ingestedtime_t** column for id **8e8b4a6c-0877-4ff8-b51b-4ac04fecdc59** so, can you check the same in oracle side as well if you are getting different **oracle_ingestedtime** in RAW logs of OCI :
![image](https://github.com/user-attachments/assets/307e164c-f33e-4b96-8f44-a84adc91ab26)

**Comment by fa-clavis** [comment] 2024-09-24 13:17
Hello @v-sudkharat, yes it is correct on the OCI side.
With the following ID, there were 2 requests within milliseconds of each other.

![image](https://github.com/user-attachments/assets/849a2dd2-0378-4a0a-bed5-15f6caef48d0)

However, this doesn't explain why I would have that same event in Sentinel, 542 times as shown in the “count_logs_query_data.csv” file that I sent through e-mail.

As I've been mentioning for a while now, there is probably a problem with the loop within the function app as it keeps iterating through the same log somehow. Because there is no problem on the OCI side, it's a truly 100% MS problem.

**Comment by v-sudkharat** [comment] 2024-09-25 12:14
Hi @fa-clavis, Thank you for your response. We have reached out to our concern team for this issue and shared the issue details, to troubleshoot on this issue team suggested to open an azure support case. 
So, please open a support case for this issue, so our support team have the required access with them and forward this ticket to respective team, also they will get in call with you if required. 
Please confirm once after open the case. Thanks!

**Comment by v-sudkharat** [comment] 2024-09-27 06:51
Hi @fa-clavis, Could you please confirm did you raise a support case in azure? so our support team can prioritize this case. Thanks!

**Comment by fa-clavis** [comment] 2024-09-27 17:09
Hello @v-sudkharat,
I'm checking with the client the possibility of opening such case as it involves other areas within the company.
As I can understand, this problem will only be solved with the ticket?
Why can't it be solved without the support case?

**Comment by v-sudkharat** [comment] 2024-09-30 06:26
Hi @fa-clavis, The support case helps our concern team to get the required access of workspace/data to troubleshoot the root cause of issue, which cannot be shared or done via a GitHub as it's as open source, and it also help to prioritize/escalate the issue to respective teams to gets resolve. 
So, kindly confirm once after opening it, so we can close this once from GitHub. Thanks!

**Comment by fa-clavis** [comment] 2024-10-02 12:37
Hello @v-sudkharat, alright, thanks for your explanation.
I will check in with the team and when the support case is open, I will post it here.

**Comment by v-sudkharat** [comment] 2024-10-03 05:41
@fa-clavis, Thanks!

**Comment by v-sudkharat** [comment] 2024-10-08 11:23
Hi @fa-clavis, Any update on case?

**Comment by fa-clavis** [comment] 2024-10-09 17:59
Hello @v-sudkharat, unfortunately, I still don't have any updates with the team because of some complexity that involves the company budget and another internal team's approval inside the company.
Hopefully I'll be able to send the support case number, ASAP.

**Comment by v-sudkharat** [comment] 2024-10-11 08:18
@fa-clavis, Ok. Thanks!

**Comment by v-sudkharat** [comment] 2024-10-24 09:37
Hi @fa-clavis, Please share the support ticket ID on below mail once it raised: v-sudkharat@microsoft.com
As we are proceeding this issue via a support case, closing this issue. If you still need support for this issue, feel free to re-open it any time. Thank you for your co-operation.

**Closed by v-sudkharat** 2024-10-24 09:37 UTC
Labels: Connector
