### ISSUE TITLE
Analytic rule not working properly

### ISSUE THREAD

**Issue by UNOBeheer** [Azure/Azure-Sentinel#11125] opened 2024-09-13 14:03 UTC
The rule "Detections/SigninLogs/AuthenticationAttemptfromNewCountry.yaml" detects sign-ins from microsoft ip addresses and creates a incident. But the correct ip subnet with prefix is mention in the included JSON file. Sentinel wil create a incident with the microsoft ip addresses. 

create a sign-in from a microsoft ip and run the rule. 

![afbeelding (4)](https://github.com/user-attachments/assets/f28ec29b-d39a-436a-8e0c-e35e6f22f333)

**Comment by v-rusraut** [comment] 2024-09-19 07:05
Hi @UNOBeheer, Thanks for flagging this issue, we will investigate this issue and get back to you with some updates. Thanks!

**Comment by v-rusraut** [comment] 2024-09-26 12:27
Hi @UNOBeheer, please provide more details about the issue. You mentioned that it created an incident with the Microsoft IP address; please provide more information about this as well.

**Comment by v-rusraut** [comment] 2024-09-30 05:26
Hi @UNOBeheer,
We are waiting for response.

**Comment by v-rusraut** [comment] 2024-10-03 06:02
Hi @UNOBeheer , Gentle Reminder: We are waiting for your response on this issue. If you still need to keep this issue active, please respond to it in the next 2 days. If we don't receive a response by 05-10-2024 date, we will be closing this issue. 		
Thanks!

**Comment by UNOBeheer** [comment] 2024-10-04 09:29
Hello @v-rusraut, 

The rule detects 95% off the time sign-ins within the non-interactive sign-in logs from Microsoft IP's. Within the screenshot that I previously submitted you see the events off 1 incident and it shows the Microsoft ip addresses. 
When I investigate the incident I see Hybrid joined laptops within the sign-in event and when i search the ip on virustotal the Autonomous System Label is Microsoft. An example: https://www.virustotal.com/gui/ip-address/20.91.233.82/details
If I search in the json file thats included in the rule I see the subnet "20.91.128.0/17". The detected IP address falls within this /17 subnet and should therefore not appear in the incident.

We running de following analytic rule template version: 1.1.2

Do you need more information or is this enough for you?

Yours sincerely,
Boris

**Comment by v-rusraut** [comment] 2024-10-07 10:01
Hi @UNOBeheer,
As we verify, the IP address from incident 20.91.233.82 is different from the addressPrefixes mentioned in the JSON file 20.91.128.0. The third digit (host) is different, which is why the incident was created.

**Comment by UNOBeheer** [comment] 2024-10-08 06:53
Hello @v-rusraut 
Sorry but a /17 network includes 32768 ip addresses, this ip is within the range. Please fix it.

**Comment by v-rusraut** [comment] 2024-10-11 04:43
Hi @UNOBeheer,
We are working with respective team, we will update you.

**Comment by v-rusraut** [comment] 2024-10-11 06:31
Hi @praveenthepro , please help on this issue .

**Comment by praveenthepro** [comment] 2024-10-15 05:02
@v-rusraut , Started working on it, will keep you updated

**Comment by praveenthepro** [comment] 2024-10-15 08:25
The service tags json file used for exceptions in this alert was outed which is the root cause of this false positives, Raised the PR for updating the json, https://github.com/microsoft/mstic/pull/33, Which will fix the issue.

**Comment by v-rusraut** [comment] 2024-10-17 06:08
Hi @UNOBeheer , The PR raised by Praveen has been merged. Please check if your issue is resolved so we can close it.

**Comment by v-rusraut** [comment] 2024-10-21 06:07
Hi @UNOBeheer, we are waiting for your response on this issue. If you still need to keep this issue active, please respond to it in the next 2 days. If we don't receive a response by 23-10-2024 date, we will be closing this issue.
Thanks!

**Comment by v-rusraut** [comment] 2024-10-23 04:36
Hi @UNOBeheer , since we have not received a response in the last 5 days, we are closing your issue as per our standard operating procedures. If you still need support for this issue, feel free to re-open at any time. Thank you for your co-operation.

**Closed by v-rusraut** 2024-10-23 04:36 UTC
Labels: Analytic Rules

**Comment by UNOBeheer** [comment] 2024-10-29 09:09
I was able to test with the new JSON, but now more false positives are showing up.
