### ISSUE TITLE
Get-GeoFromIpAndTagIncident Playbook fails

### ISSUE THREAD

**Issue by paisleyborg** [Azure/Azure-Sentinel#6305] opened 2022-10-05 05:00 UTC
Hi,

We are working through this very lab: https://github.com/Azure/Azure-Sentinel/blob/master/Solutions/Training/Azure-Sentinel-Training-Lab/Modules/Module-4-Incident-Management.md.

In Exercise 2, Step 9 it says: _Locate the playbook Get-GeoFromIpAndTagIncident and press Run. If the playbook is configured correctly, it should finish in a couple of seconds._

The playbook fails to execute with 'bad request' - please see screenshots.
![Playbook1](https://user-images.githubusercontent.com/19217163/193984342-e4a7668f-2d49-42b4-bd83-d9abfb0b451d.jpg)
![Playbook3](https://user-images.githubusercontent.com/19217163/193985264-1f311be3-7c38-4303-9c9c-ba5a8b8eb486.jpg)

We are therefore not getting the expected behavior for this lab, as described in Exercise 2, Step 10. _Navigate back to the main incident page and notice to new tags that added to the incident._

We are working through this Sentinel Lab on a Windows 11 laptop (22H2, Build 22621.521), and using Firefox browser version 105.0.1.

Look forward to hearing back from the team.

Thank you.

**Comment by javiersoriano** [comment] 2022-10-10 10:35
@paisleyborg I'm not able to reproduce the issue. Did you complete this section before moving into Module 4 https://github.com/Azure/Azure-Sentinel/blob/master/Solutions/Training/Azure-Sentinel-Training-Lab/Modules/Module-1-Setting-up-the-environment.md#exercise-3-configure-azure-sentinel-playbook?

![image](https://user-images.githubusercontent.com/13329585/194847374-183b7ede-09b0-404c-ab63-627e93d7b70c.png)

![image](https://user-images.githubusercontent.com/13329585/194847455-7425a43f-e327-48f1-b644-2bfb4c7a5aa5.png)

**Comment by v-amolpatil** [comment] 2023-02-12 16:30
Hi @paisleyborg, thank you for flagging this. Apologies for the delayed response. If you still need assistance, please reply here within 5 business days.

**Comment by v-amolpatil** [comment] 2023-02-16 18:27
Hi @paisleyborg, As per previous comment by Javier closing this issue as it is not reproducable. Feel free to re-open the issue if you need an assistance on this. Thank you for your co-operation.

**Closed by v-amolpatil** 2023-02-16 18:27 UTC
Labels: bug
