### ISSUE TITLE
ArchivingBasicLogsRetention workbook cant retain 7 years in total

### ISSUE THREAD

**Issue by philfy20** [Azure/Azure-Sentinel#6464] opened 2022-10-21 06:35 UTC
**Describe the bug**
Unable to set total retention days via the Archiving BasicLogs Retention workbook of 7 years which is is 2556 days - currently maxed to 2555 days

**To Reproduce**
1. Go to Archiving, Basic Logs, and Retention workbook
2. select table you want to archive
3. set archive to 7 years whcih is 2556 days
4. See error max days is 2555

**Expected behavior**
should be able to select 2556 days to get the full 7 years

**Additional context**
changing max value accepted to 2556 days should resolve the error

**Comment by v-rbajaj** [comment] 2023-06-07 12:16
Hi @philfy20, We wanted to check on the status of Issue https://github.com/Azure/Azure-Sentinel/issues/6464 . The issue is pending for more than expected days. Please let us know if you need any assistance to review this Issue. As per our standard operating procedures if no response is received in the next 7 business days, we will close this Issue. Thank you for your cooperation.

**Comment by philfy20** [comment] 2023-06-09 04:35
@v-rbajaj - issue is still recurring with the latest workbook. I have global admin and contributor on all resources. Same issue happens with other customers I work with. Thanks

**Comment by v-rbajaj** [comment] 2023-06-19 12:42
Hi @philfy20, we are checking on this internally with the team, we will soon get to back to you.

**Comment by v-vdixit** [comment] 2023-06-30 12:15
Hi @philfy20 we have raised a PR with the updates, will be published once the PR is merged, thanks!

**Comment by v-vdixit** [comment] 2023-07-05 07:27
Hi @philfy20 the PR is under review by team, will be published once merged, thanks!

**Comment by v-vdixit** [comment] 2023-07-10 10:20
Hi @philfy20 we are working on updates in PR, changes will be published once merged, thanks for your patience!

**Comment by philfy20** [comment] 2023-07-10 10:38
thanks for the update

**Comment by Rishik999** [comment] 2023-07-12 09:03
Hi @philfy20, thanks for being patience. There is a validation check which is failing in the PR and we are actively looking into this issue with respective team. Once that is fixed, we will get back to you.

**Comment by v-rbajaj** [comment] 2023-07-12 09:05
Hi @philfy20, thanks for being patience. There is a validation check which is failing in the PR and we are actively looking into this issue with respective team. Once that is fixed, we will get back to you.

**Comment by v-vdixit** [comment] 2023-07-14 05:52
Hi @philfy20 we had to mark the PR as draft presently, as the validation test is failing even when all requirements are met, we have updated the concerned team about the error and are waiting for them to update the validation checks, thanks for your patience!

**Comment by v-vdixit** [comment] 2023-07-17 12:25
We are waiting for update on validation tests, the PR will be reviewed and merged post that, thanks!

**Comment by v-vdixit** [comment] 2023-07-19 11:19
Hi @philfy20 we are still waiting for updates on validation tests, thanks!

**Closed** 2023-07-20 12:58 UTC
Labels: enhancement, Workbook
