### ISSUE TITLE
LastPass Solution not ingesting Data?

### ISSUE THREAD

**Issue by asterictnl-lvdw** [Azure/Azure-Sentinel#6529] opened 2022-11-01 09:00 UTC
**Describe the bug**
I have configured the LastPass Solution using the CID and API-Key (Hash). But it has been 3 days now and no custom data table is created and no data is ingested in 

**To Reproduce**
1. [Configure the LastPass Enterprise Monitoring Solution](https://azuremarketplace.microsoft.com/en-us/marketplace/apps/thecollectiveconsultingbv1584980370320.lastpass-enterprise-monitoring-solution?ocid=GTMRewards_WhatsNewBlog_lastpass-enterprise-monitoring-solution_031022)
2. Configure and install the Connector
3. Goto the **Sentinel Data Connector Page** and search for LastPass
4. Fill in the CID en API-Hash key and click on Connect
5. Wait minutes/hours/days for data???
6. No data... :(
I tried the manual version as well, but it does not seem to ingest data as well.

**Expected behavior**
Data should be ingested and the Connector should be active

**Screenshots**
![image](https://user-images.githubusercontent.com/99249102/199197810-800789af-1adf-43fa-a8eb-d78f96f5e5f4.png)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Microsoft Edge
 - Version Latest Stable Version

**Comment by rjaakke** [comment] 2022-12-01 13:48
I have similar issue with another codeless dataconnector I've written for 1Password. Same principals and it has worked fine the last few months but stopped working a couple of days back. Redeploying the data connector doesn't fix it.

SentinelHealth show me there's a "Data fetch failed (Non-TransientException FlurlHttpException exception) " with reason "MethodNotAllowed" for the data connector.

**Comment by asterictnl-lvdw** [comment] 2022-12-12 08:28
Any update on this? I want to know if this issue is going to be fixed at all?

**Comment by ashishsyal** [comment] 2022-12-23 11:05
We are looking into this and will update you next week.

**Comment by NikTripathi** [comment] 2022-12-23 14:17
Hi @rjaakke Can you please test the below custom template and let us know the output.

Please deploy the custom template available on the below URL. It will update your solution and then please test the connector.

URL:- https://raw.githubusercontent.com/Azure/Azure-Sentinel/f3ad344e225e348e2d946f1dcf4ec696ebb3e8c7/Solutions/LastPass/Package/mainTemplate.json

Steps:- 
1: Go to Portal and search for deploy a custom template.
![image](https://user-images.githubusercontent.com/87809732/209349690-39e3d802-2e0c-4a8d-b5ba-667ff5d20ba3.png)
2: Click on build your own template in editor.
![image](https://user-images.githubusercontent.com/87809732/209349902-12d559d7-7667-4b5f-b4dd-6cca2fc576a7.png)
3: Remove the content and paste the content which is available on the above URL and click on save.
![image](https://user-images.githubusercontent.com/87809732/209350012-ce5cc030-98a4-4a03-a2c9-4875beecd5a5.png)
4: Select Resource group and workspace and then click on review + Create.
![image](https://user-images.githubusercontent.com/87809732/209350112-0c843a29-fd04-4768-975e-27feb0a489bb.png)
5: Once deployment is done please test the data connector and let us know the output. 

Thanks.

**Comment by jakristensen** [comment] 2022-12-23 19:13
@NikTripathi I think @rjaakke is trying to ingest data from a 1Password log source, and not LastPass.
@rjaakke have you found a solution to your issue? I am trying to setup the same solution in 1Password to Sentinel.

**Comment by jakristensen** [comment] 2022-12-29 13:43
I raised this issue to Product manager from Microsoft and have been told that the issue is caused by an bug with the POST HTTP method. The bug should have been fixed now and has been planned to be deployed onto production this Monday the 2th of January 2023.

**Comment by v-dvedak** [comment] 2023-01-05 06:28
Closing this issue since it is fixed as per confirmation from Thijs.

**Closed by v-dvedak** 2023-01-05 06:28 UTC
Labels: Connector
