### ISSUE TITLE
Problem with Sentinel PB Fortigate - Function Fortinet-GetEntityDetails

### ISSUE THREAD

**Issue by Joaquin1912** [Azure/Azure-Sentinel#4015] opened 2022-01-26 12:57 UTC
**Describe the bug**
When I try to run the PB to find if the IP is created in the Forti I get the error "The remote certificate is invalid according to the validation procedure." and I can't get past this step. If I just execute the function, the same thing happens to me. 

**To Reproduce**
I execute this code:
<img width="457" alt="image" src="https://user-images.githubusercontent.com/98459788/151166364-43ddc18c-e457-4bf7-8c6d-90ec923cc82c.png">

**Screenshots Error**
<img width="410" alt="image" src="https://user-images.githubusercontent.com/98459788/151166860-9aef220f-db4e-4fd1-b44a-06d4ae7041bd.png">

Can you help me?

**Comment by Lodewyk-Git** [comment] 2022-01-27 12:06
If you get “The remote certificate is invalid according to the validation procedure” exception while trying to establish SSL connection.

To me it looks like the error is with your authentication. Maybe try using this outdated method that I wrote:

Function for getting token - use the correct API values etc, would be good to first test values using Postman.
```
private static string GetToken(){
    var request = (HttpWebRequest)WebRequest.Create("https://login.microsoftonline.com/316bec54-8d14-4882-8af3-ee5e61570603/oauth2/token");

        var postData = "grant_type=" + Uri.EscapeDataString("client_credentials");
            postData += "&client_id=" + Uri.EscapeDataString(""); //add client ID
            postData += "&client_secret=" + Uri.EscapeDataString(""); //add client secret
            postData += "&resource=" + Uri.EscapeDataString("https://api.loganalytics.io");
        var data = Encoding.ASCII.GetBytes(postData);

        request.Method = "POST";
        request.ContentType = "application/x-www-form-urlencoded";
        request.ContentLength = data.Length;

        using (var stream = request.GetRequestStream())
        {
            stream.Write(data, 0, data.Length);
        }

        var response = (HttpWebResponse)request.GetResponse();
        var responseString = new StreamReader(response.GetResponseStream()).ReadToEnd();

        //convert token to string
        dynamic stuff = JsonConvert.DeserializeObject(responseString);
        string token = stuff.access_token;

        return token;

}
```


Perform the request using the token that you just got.
Remember to fill in the correct accept and other values for the request.

```
private static string Request() {
    
    var access = GetToken();
    var request = (HttpWebRequest)WebRequest.Create("REQUESTHERE");
    
    request.Method = "GET";
    request.Accept = "application/json";
    request.Headers["Authorization"] = "Bearer "+access;
    

    var response = (HttpWebResponse)request.GetResponse();
    var responseString = new StreamReader(response.GetResponseStream()).ReadToEnd();

    //convert token to string
    dynamic results = JsonConvert.DeserializeObject(responseString);
    
    return results.ToString(); //I'm returing this in a string format, but if you can parse it and think of a better way, please do make the change
}
```

**Comment by Joaquin1912** [comment] 2022-01-31 16:18
Sorry, but I don't quite understand your code. I explain to you, this function in the photo is used to connect via API to a FortiGate using the key that we have added in the key vault and the predefined values in the APP(Picture) function. I don't know why my code fails and I don't know if yours is compatible with what I want to do. I can't use PostMan due to permission issues. Can you help me?
Thank you.
<img width="432" alt="image" src="https://user-images.githubusercontent.com/98459788/151830971-ccc68f5c-56cc-435b-8f2e-b30d460b36b8.png">

**Comment by Joaquin1912** [comment] 2022-02-11 09:58
Any updates??

**Comment by Joaquin1912** [comment] 2022-02-22 09:11
Hello?

**Comment by Joaquin1912** [comment] 2022-03-09 10:50
Any updates?

**Comment by anki-narravula** [comment] 2022-03-09 17:44
Hi @Joaquin1912  - Sorry for delay in responding. We are not able to replicate this issue, but I am thinking this might be caused by 2 reasons 1) Invalid Key 2) Your host is not enabled with SSL certificate. 
Since you have mentioned that you can't use postman, can you please try with curl ? Sample API call is given below, you can replace with your fortigate host details 

curl -X POST "https://'fwurl'/api/v2/cmdb/firewall/address" -H "accept: application/json" -H "Authorization: Bearer 'api key'" -H "Content-Type: application/json" -d "{ "name": "test1000", \"type": "iprange", "start-ip": "20.1.1.12", "end-ip": "20.1.1.12"}"

**Comment by Joaquin1912** [comment] 2022-03-10 11:58
![image](https://user-images.githubusercontent.com/98459788/157637627-4b340156-1ba2-4967-a9bb-b138dc16cb4a.png)
Hello!!
Thanks for the reply, I get this above when I run it 

Regards

**Comment by anki-narravula** [comment] 2022-03-11 07:24
Hi @Joaquin1912  - Thanks for checking. So based on this, it clearly indicates that these is an issue with Fortigate hosts SSL configuration. This is generic issue and nothing to do with this Playbook or Sentinel. So please try to address this issue by contacting system administrator or fortigate team. 

![image](https://user-images.githubusercontent.com/10404181/157821342-00f1d452-6e7c-4362-8873-f234341af7cd.png)

**Comment by raj009970** [comment] 2022-03-24 09:26
Hi all,
Greetings !!!

I just wanted to create a playbook in sentinel for auto-blocking an IP address in FortiGate Firewall. by using the below link. could anyone tell me the step by step how i can achieve it.

like we need function app, custom connector and API key. but how playbook will communicate with On-Prem Fortigate firewall. what configuration we have to do in FortiGate Firewall side.

https://github.com/Azure/Azure-Sentinel/tree/master/Playbooks/Fortinet-FortiGate

Regards

**Comment by v-amolpatil** [comment] 2023-01-30 17:34
Hi @raj009970, Thank you for your comment. Can you please create a new issue as this issue is not related to the actual issue opened here.

**Comment by v-amolpatil** [comment] 2023-01-30 17:35
Hi @Joaquin1912, As per earlier comment this issue is from Fortinet hosts SSL so closing this issue as it is not related to playbook or Sentinel.

**Closed by v-amolpatil** 2023-01-30 17:35 UTC
Labels: Connector

**Comment by NinaSec** [comment] 2023-03-15 11:02
Hello, 

I resolved the issue on the run.cx of the function please update by writing this code : 

#r "Newtonsoft.Json" 
#r "System.Net.Http"
using System.Net; 
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Primitives; 
using Newtonsoft.Json; 
using Newtonsoft.Json.Linq;
using System.Security.Cryptography.X509Certificates;
public static async Task<IActionResult> Run(HttpRequest req, ILogger log)
{
    HttpClientHandler handler = new HttpClientHandler();
handler.ServerCertificateCustomValidationCallback +=(sender,cert,chain,sslPolicyErrors) => true;
log.LogInformation("HTTP request received.");
var entity = req.Query["entity"];
var filter = req.Query["filter"];
var key = Environment.GetEnvironmentVariable("Authorization", EnvironmentVariableTarget.Process);
var endpointURL = Environment.GetEnvironmentVariable("EndpointURL", EnvironmentVariableTarget.Process);
var baseURL = Environment.GetEnvironmentVariable("BaseURL", EnvironmentVariableTarget.Process);
JToken results = null;
log.LogInformation(filter);
log.LogInformation(entity);
log.LogInformation(baseURL);
var httpclient = new HttpClient(handler);
var httpRequest = new HttpRequestMessage(HttpMethod.Get, new Uri(endpointURL + baseURL + entity + "?" + filter ));
log.LogInformation(httpRequest.RequestUri.ToString());
 if (key.StartsWith("Bearer", StringComparison.InvariantCultureIgnoreCase)) 
 {key = key.ToString();
 log.LogInformation(key);} 
 else {key = "Bearer" + key.ToString();}
 httpRequest.Headers.Add("Authorization", key.ToString());
 log.LogInformation(key);
 log.LogInformation(httpRequest.ToString()); 
 var response = httpclient.SendAsync(httpRequest).Result;

 //response = response.ToString()
 var responseJson = response.Content.ReadAsStringAsync().Result;
 if (responseJson != null)
 {
 JObject json = new JObject();
 dynamic obj = JsonConvert.DeserializeObject(responseJson);
 json = (JObject)obj;
 results = json.SelectToken("results");
 return new OkObjectResult(results);
 }
 return new OkObjectResult(results);
 }
