### ISSUE TITLE
Dynatrace solution data connectors under certain circumstances fields are being trimmed to the max allowed size for log analytics workspace

### ISSUE THREAD

**Issue by keyoke** [Azure/Azure-Sentinel#10826] opened 2024-07-16 15:04 UTC
**Describe the bug**
Dynatrace solution data connectors( Audit & Problem ) under certain circumstances data returned by the Dynatrace REST API contains a very large value i.e. JSON data, a warning is triggered  by Log Analytics Workspace about being trimmed to the max allowed size.

Some examples:

- The following fields' values evidenceDetails_details of type DynatraceProblems_CL have been trimmed to the max allowed size, 32766 bytes. Please adjust your input accordingly. (1)

- The following fields' values patch of type DynatraceAuditLogs_CL have been trimmed to the max allowed size, 32766 bytes. Please adjust your input accordingly. (1)

**Expected behavior**
The connectors should correctly handle these cases where field length is longer than 32kb

**Question**
What is the guidance from Microsoft for handling these cases when partners develop a codeless connector? Is it possible to use Data Collection Rules to transform the incoming data and fan it out into one or more additional tables?

**Comment by keyoke** [comment] 2024-07-26 08:45
Hello @v-sudkharat  we have customers which are currently impacted by this issue are you able to provide us any feedback? many thanks

**Comment by v-mabrindha** [comment] 2024-07-30 07:17
Hi @keyoke, Thanks for flagging this issue, we will investigate this issue and get back to you with some updates by
02-08-2024. Thanks!

**Comment by v-mabrindha** [comment] 2024-08-01 11:40
Hi @keyoke,

This is expected Behaviour, since this is a limit that is documented for data collector API:
[https://learn.microsoft.com/en-us/azure/azure-monitor/service-limits#log-analytics-workspaces](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Flearn.microsoft.com%2Fen-us%2Fazure%2Fazure-monitor%2Fservice-limits%23log-analytics-workspaces&data=05%7C02%7Cv-asharaf%40microsoft.com%7Cd9bfe1ba5dbe4d18276808dcb13348af%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638580081026450451%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=mjzYyWmskKPioXzZ3kdMsMEK1ltiu4WacJpPyG4z8o4%3D&reserved=0)

![image](https://github.com/user-attachments/assets/22197f88-050c-45ac-8ae8-f8e825ce382c)
 
And this API will deprecated and will no longer be functional as of 14/9/2026.
Reference Doc :- [Azure Monitor HTTP Data Collector API - Azure Monitor | Microsoft Learn](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Flearn.microsoft.com%2Fen-us%2Fazure%2Fazure-monitor%2Flogs%2Fdata-collector-api%3Ftabs%3Dpowershell&data=05%7C02%7Cv-asharaf%40microsoft.com%7Cd9bfe1ba5dbe4d18276808dcb13348af%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638580081026463855%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=uBZ0ovD0yh29A14cAwKPCXz34Z4pEX1hBElgr%2FDqscs%3D&reserved=0)
 
Below is 2 workaround that can help you to unblock from the size limitations:-
You need to change your code\script used in Data connector to split the data before it's ingested into workspace. 
2. Or you can migrate to use the new Log Ingestion API which has a field limit of 64KB instead of 32KB. The guidance is documented added here:
[Migrate from the HTTP Data Collector API to the Log Ingestion API - Azure Monitor | Microsoft Learn](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Flearn.microsoft.com%2Fen-us%2Fazure%2Fazure-monitor%2Flogs%2Fcustom-logs-migrate&data=05%7C02%7Cv-asharaf%40microsoft.com%7Cd9bfe1ba5dbe4d18276808dcb13348af%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638580081026473978%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=SG0ZenIjoSZc%2BFUis1PTy3629uzCqBFDaiSod00xXWc%3D&reserved=0)

**Comment by v-mabrindha** [comment] 2024-08-05 04:25
Hi @keyoke,
Could you please inform us if this has helped in resolving your issue?

**Comment by v-mabrindha** [comment] 2024-08-07 10:37
Hi @keyoke ,
Gentle Reminder: We are waiting for your response on this issue. If you still need to keep this issue active, please respond on it in the next 2 days. If we don't receive response by given date, we will be close this issue.

**Comment by keyoke** [comment] 2024-08-07 13:08
Hi @v-mabrindha, 
Thanks we are aware of the limits

1. we leverage codeless connector therefore there is no code/scripts 
2. how is this implemented in CCI do you have any docs?

**Comment by v-mabrindha** [comment] 2024-08-12 11:04
Hi @keyoke,

Please the reference document - https://github.com/Azure/Azure-Sentinel/blob/master/Tools/Create-Azure-Sentinel-Solution/V3/CCP_README.md

**Comment by keyoke** [comment] 2024-08-21 10:59
@v-mabrindha thank you for the document

**Comment by v-mabrindha** [comment] 2024-08-22 12:38
Thank you, @keyoke for the status update. I'll proceed with closing this GitHub issue.

**Closed by v-mabrindha** 2024-08-22 12:38 UTC
Labels: Connector
