### ISSUE TITLE
Squid parser data connector could not parse the data correctly.

### ISSUE THREAD

**Issue by v-jackzou** [Azure/Azure-Sentinel#8999] opened 2023-09-13 05:57 UTC
Bug description

After installing the squid proxy connector from the Sentinel content hub solution. It will start ingesting the squidProxy_CL log into the workspace. However the parser could not parse the day column correctly.

To reproduce 

The squidProxy_CL with the RAW data ingested as follows; 

 Sep 11 13:27:33 xxxxxx (squid-1): 100000000.547 701 1.1.1.1 TCP_MISS/200 386364 POST http://sample.com :9002/webSvc/Get - HIER_DIRECT/1.1.1.1 application/json

However, after the parsing the day column only parse 11 instead of Sep 11

**Comment by v-rbajaj** [comment] 2023-09-13 11:30
Hi @v-jackzou , thanks for flagging this issue, we will soon get back to you on this. Thanks!

**Comment by v-rbajaj** [comment] 2023-09-22 14:56
Hi @v-jackzou, we have reached out to concerned team for this, we will get back to you by 27 Sep 2023.

**Comment by v-jackzou** [comment] 2023-09-26 02:18
Sure! thanks looking forward to your updates!

**Comment by v-jackzou** [comment] 2023-10-01 06:40
HI team, just a follow up regarding this issue, any updates regarding this issue?

**Comment by v-jackzou** [comment] 2023-10-04 08:14
HI TEAM 

just a follow up for this ticket, let me know if there are any further help required.

**Comment by v-jackzou** [comment] 2023-10-04 08:15
Hi team

Any updates for this ticket ?

**Comment by v-jackzou** [comment] 2023-10-04 08:15
HI team 

Any updates for this issue ?

**Comment by v-rbajaj** [comment] 2023-10-05 13:12
Hi @v-jackzou, sorry for delay in response, we are still  investigating on this issue, please provide us sometime, we will get back to you by 11 oct 2023.

**Comment by v-rbajaj** [comment] 2023-10-05 13:38
Hi @v-jackzou, we investigated on this issue and we could find that the parser was optimized for this issue over this PR 
https://github.com/Azure/Azure-Sentinel/pull/7490/files

Please have a look and update the solution if its not updated.

**Comment by v-rbajaj** [comment] 2023-10-10 08:56
Hi @v-jackzou, Gentle Reminder: We are awaiting for your response on this issue. If you still need to keep this issue active please respond on it in the next 2 days . If we don't receive response, we will be close this issue.

**Comment by v-jackzou** [comment] 2023-10-10 09:04
Hi @v-rbajaj  allow me to sync with the customer

**Comment by ypendhare** [comment] 2023-10-10 10:06
issue is yet not fixed, morever fields are distorted 

![image](https://github.com/Azure/Azure-Sentinel/assets/64295945/2ae7d985-7ae5-4b17-930c-c27c2ef0601d)

**Comment by v-rbajaj** [comment] 2023-10-12 07:43
Hi @ypendhare, thanks for updating us, let us check and will get back to you by 16 Oct 2023

**Comment by v-jackzou** [comment] 2023-10-27 04:52
Hi team, any updates for this issue?

**Comment by v-rbajaj** [comment] 2023-11-01 16:00
Hi @v-jackzou, apologies for delay in response, we will provide you an update by  7 Nov 2023

**Comment by v-rbajaj** [comment] 2023-11-07 09:24
Hi @v-jackzou, we are still investigating on this issue, we will provide an update by 09 Nov 2023.

**Comment by v-rbajaj** [comment] 2023-11-09 18:19
Hi @v-jackzou, we have tested the parser and it seems to be parsing the data correctly. 

![image](https://github.com/Azure/Azure-Sentinel/assets/120547590/8315a829-3cbd-4960-91c4-eb7550222884)

**Comment by ypendhare** [comment] 2023-11-10 07:10
Team, i am still seeing issue, this time a different one - EpochTimeExtended field is mixed with other field data

![image](https://github.com/Azure/Azure-Sentinel/assets/64295945/04a3b851-78aa-4fc9-bbd2-b50c6dbd1d29)

**Comment by v-rbajaj** [comment] 2023-11-14 14:22
Hi @ypendhare, can you please share the complete list of raw log messages which you guys are trying to parse, because the ones which we have is parsing the data correctly.
Thanks

**Comment by v-muuppugund** [comment] 2023-11-16 07:38
Hi @ypendhare  Could you please share the the complete list of raw log messages so we can parse the data correctly

**Comment by v-jackzou** [comment] 2023-11-20 07:59
Hi team 

Thanks again for the help on this, I have provided the required information to @v-muuppugund , please investigate and we will wait for your response. 

Thank you

**Comment by ypendhare** [comment] 2023-11-22 03:16
[squidlog.log](https://github.com/Azure/Azure-Sentinel/files/13433154/squidlog.log)
@v-muuppugund attached is file

**Comment by v-muuppugund** [comment] 2023-11-22 12:45
@ypendhare  Thanks for sharing it,will check on it and get back to you

**Comment by v-rbajaj** [comment] 2023-11-23 13:20
We are checking the logs and trying to ingest similar data and will get back to you by 27 Nov 2023.

**Comment by v-rbajaj** [comment] 2023-11-27 12:42
We are trying to ingest similar data and will get back to you by 30 Nov 2023

**Comment by v-rbajaj** [comment] 2023-11-29 13:58
We have reached out to concerned team we will get back to you by 1 Dec 2023

**Comment by v-rbajaj** [comment] 2023-12-12 11:34
Hi @ypendhare, Gentle Reminder: We are awaiting for your response on this issue. If you still need to keep this issue active please respond on it in the next 2 days . If we don't receive response, we will be close this issue.

**Comment by ypendhare** [comment] 2023-12-12 13:06
I have already provided log file refer earlier comments 
You can save that as csv as well

**Comment by v-muuppugund** [comment] 2023-12-20 14:09
Hi @ypendhare / @v-jackzou ,need some details from customer as we are unable to process the log format to csv and few queries on the issue,Could you please suggest convenient time slots for teams meeting,

**Comment by v-sudkharat** [comment] 2023-12-26 11:42
Hi @v-jackzou / @ypendhare, Could you please share your convenient time slot for meeting on this mail id - [v-muuppugund@microsoft.com](mailto:v-muuppugund@microsoft.com)

Thanks!

**Comment by v-muuppugund** [comment] 2023-12-28 06:55
Hi @ypendhare / @v-jackzou ,As discussed on yesterday call ,got the data and the following are the issues and working on it ,will update you

- Epoch time is not parsing
- Day is not coming properly

**Comment by v-muuppugund** [comment] 2024-01-08 01:23
Hi @ypendhare / @v-jackzou  Still data dump is in progress with large data, Will update you once testing is completed by 10Jan2024

**Comment by v-muuppugund** [comment] 2024-01-17 17:05
Hi @v-jackzou ,As discussed over teams ,having issues with data, working on it,once done,will test and schedule meeting with customer.

**Comment by v-muuppugund** [comment] 2024-01-21 10:24
Hi @ypendhare / @v-jackzou ,Completed the testing,scheduled call for the showing the changes on Tuesday i.e. 23/1/24 at 4:30pm to 5pm ,please join the meeting.

**Comment by v-muuppugund** [comment] 2024-01-23 13:58
Hi @ypendhare ,As discussed over today's call ,Squid proxy parser changes tested successfully and changes are in this branch(https://github.com/Azure/Azure-Sentinel/blob/users/v-muuppugund/SquidProxyParserChanges/Solutions/SquidProxy/Parsers/SquidProxy.txt),as the issue is resolved, we are closing your issue (https://github.com/Azure/Azure-Sentinel/issues/8999) . If you still need support for this issue, feel free to re-open at any time. Thank you for your co-operation!

**Closed by v-muuppugund** 2024-01-23 13:58 UTC
Labels: Connector, Parser
