### ISSUE TITLE
Microsoft Exchange Connector - Message Tracking is broken

### ISSUE THREAD

**Issue by FormindMPO** [Azure/Azure-Sentinel#9862] opened 2024-01-30 13:21 UTC
**Describe the bug**

Error in the `[Option 6] Message Tracking of Exchange Servers` from the `Microsoft Exchange Logs and Events` Connector.
The manual DCR deployement can't be done.

**To Reproduce**
1. Install Message Tracking of Exchange Servers Connector
2. Create a DCE
3. Try to create the DCR
4. Get the [ESI-MessageTrackingLogs.json](https://github.com/Azure/Azure-Sentinel/blob/master/Sample%20Data/Custom/ESI-MessageTrackingLogs.json) DCR-based tempalte
5. See error (1)
6. Transform `date-time` to `TimeGenerated` fields
7. See error (2)

**Expected behavior**

Successful creation

**Screenshots**

![image](https://github.com/Azure/Azure-Sentinel/assets/127124531/1572de7e-9ca0-4833-8941-1ff00563428f)

![image](https://github.com/Azure/Azure-Sentinel/assets/127124531/1a30d0f6-b301-4df1-88c0-28c284343254)

Error (1) :
![image](https://github.com/Azure/Azure-Sentinel/assets/127124531/e8648979-36d6-4880-9cc2-14ffb2b734b0)

Error (2) :
![image](https://github.com/Azure/Azure-Sentinel/assets/127124531/e1869ba2-7848-4fcd-af9c-4f135191ebe3)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Firefox
 - Version 122

**Additional context**

**Comment by v-muuppugund** [comment] 2024-01-31 07:49
Hi @FormindMPO , Thanks for flagging this issue, we will investigate this issue and get back to you with some updates by 06/02/2024. Thanks!

**Comment by v-muuppugund** [comment] 2024-02-07 02:58
Hi @FormindMPO , Still need some more time for replicating the issue ,will update you

**Comment by v-muuppugund** [comment] 2024-02-11 05:30
Hi @FormindMPO ,I am able to replicate the issue and working on further analysis for fix,please find below screen shot for reference
![image](https://github.com/Azure/Azure-Sentinel/assets/139563098/185328c9-99d2-47a5-8763-ae28f863bc73)

**Comment by v-muuppugund** [comment] 2024-02-18 16:55
Hi @FormindMPO ,Working on data changes,once done,will test and update you

**Comment by t0neex** [comment] 2024-02-19 07:58
Hi @v-muuppugund, does it also block data ingestion from Exchange servers with ARM template? I faced the same issue with manual deployment, then I tried with ARM template, but it's not ingesting any data from Exchange.

**Comment by v-muuppugund** [comment] 2024-02-19 08:01
Hi @t0neex ,this is different issue,Could you please share more details,what issue you are facing,where and when it happened? with screen shots.

**Comment by t0neex** [comment] 2024-02-19 08:38
Hi @v-muuppugund, actually it seems same issue.

I tried to create MessageTrackingLog as like issue reporter FormindMPO and I faced same issue. Then i tried with Option 1 - Azure Resource Manager ARM Template option and template deployed succesfully but its not ingesting any data to my table.

If the [ESI-MessageTrackingLogs.json](https://github.com/Azure/Azure-Sentinel/blob/master/Sample%20Data/Custom/ESI-MessageTrackingLogs.json) file is also being applied in the ARM template, then the template should be changed with the new JSON file you will fix.

![image](https://github.com/Azure/Azure-Sentinel/assets/100233276/7cac4d0f-f1e7-43be-bb31-f609516c5d90)

**Comment by v-muuppugund** [comment] 2024-02-19 09:01
> Hi @v-muuppugund, thanks for your response, actually it seems same issue.
> 
> I tried to create MessageTrackingLog as like issue reporter FormindMPO and I faced same issue. Then i tried with Option 1 - Azure Resource Manager ARM Template option and template deployed succesfully but its not ingesting any data to my table.
> 
> If the [ESI-MessageTrackingLogs.json](https://github.com/Azure/Azure-Sentinel/blob/master/Sample%20Data/Custom/ESI-MessageTrackingLogs.json) file is also being applied in the ARM template, then the template should be changed with the new JSON file you will fix.
> 
> ![image](https://private-user-images.githubusercontent.com/100233276/305880340-7cac4d0f-f1e7-43be-bb31-f609516c5d90.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgzMzI3OTMsIm5iZiI6MTcwODMzMjQ5MywicGF0aCI6Ii8xMDAyMzMyNzYvMzA1ODgwMzQwLTdjYWM0ZDBmLWYxZTctNDNiZS1iYjMxLWY2MDk1MTZjNWQ5MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxOVQwODQ4MTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03ZWZhY2I4MWQ2ODAyZGZkNjdiMmNlYWZmN2I0YzZhYjBkYzg3Mzg4NDI3YmZmMWQ0NWVmZTFjNDc0M2FlYTYyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.4eFPr4Y8k8jnDHxQjOqWneurHJAN20WASKac622gNlA)

Sure @t0neex ,Please let me know convenient time slots for teams meeting for option 1 issue to this email id i.e. v-muuppugund@microsoft.com

**Comment by v-muuppugund** [comment] 2024-02-22 03:49
Hi @t0neex ,As discussed on Monday the issue is due to permissions could you please check and let us know if you still facing any issues.

**Comment by v-muuppugund** [comment] 2024-02-22 03:50
> Hi @FormindMPO ,Working on data changes,once done,will test and update you

Hi @FormindMPO ,Could you please try option 1 as work around and still need some more time on further data changes

**Comment by v-muuppugund** [comment] 2024-02-27 01:24
Hi @FormindMPO ,Gentle reminder ,Could you please try option 1 once and let me know if any issues and working on option 6 steps needs to be done,will update you

**Comment by v-muuppugund** [comment] 2024-02-27 10:14
> Hello @v-muuppugund, sorry I worked around this issue by using custom DCR I raised this issue to fix implem and refresh documentation

Sure @FormindMPO ,Working on it, meanwhile suggested alternate option for workaround.

**Comment by thom2804** [comment] 2024-03-11 14:33
Any status updates on this issue? Also running into the same issue, if someone has a fix or details about a workaround that would be appreciated.

**Comment by v-muuppugund** [comment] 2024-03-11 14:49
> Any status updates on this issue? Also running into the same issue, if someone has a fix or details about a workaround that would be appreciated.

Hi @thom2804 , Working on it ,will update you, As a work around could you please check option 6

**Comment by thom2804** [comment] 2024-03-11 15:12
> > Any status updates on this issue? Also running into the same issue, if someone has a fix or details about a workaround that would be appreciated.
> 
> Hi @thom2804 , Working on it ,will update you, As a work around could you please check option 6

Option 6 is the part of the steps where I am running into the issues, all the other options work fine, I am just unable to get the Transform action with the provided KQL query to work on the Custom Text log data source.

Query which is giving issues: `source| extend TimeGenerated = todatetime(['date-time'])| extend    clientHostname = ['client-hostname'],    clientIP = ['client-ip'],    connectorId = ['connector-id'],    customData = ['custom-data'],    eventId = ['event-id'],    internalMessageId = ['internal-message-id'],    logId = ['log-id'],    messageId = ['message-id'],    messageInfo = ['message-info'],    messageSubject = ['message-subject'],    networkMessageId = ['network-message-id'],    originalClientIp =  ['original-client-ip'],    originalServerIp = ['original-server-ip'],    recipientAddress= ['recipient-address'],    recipientCount= ['recipient-count'],    recipientStatus= ['recipient-status'],    relatedRecipientAddress= ['related-recipient-address'],    returnPath= ['return-path'],    senderAddress= ['sender-address'],    senderHostname= ['server-hostname'],    serverIp= ['server-ip'],    sourceContext= ['source-context'],    schemaVersion=['schema-version'],    messageTrackingTenantId = ['tenant-id'],    totalBytes = ['total-bytes'],    transportTrafficType = ['transport-traffic-type']| project-away    ['client-ip'],    ['client-hostname'],    ['connector-id'],    ['custom-data'],    ['date-time'],    ['event-id'],    ['internal-message-id'],    ['log-id'],    ['message-id'],    ['message-info'],    ['message-subject'],    ['network-message-id'],    ['original-client-ip'],    ['original-server-ip'],    ['recipient-address'],    ['recipient-count'],    ['recipient-status'],    ['related-recipient-address'],    ['return-path'],    ['sender-address'],    ['server-hostname'],    ['server-ip'],    ['source-context'],    ['schema-version'],    ['tenant-id'],    ['total-bytes'],    ['transport-traffic-type']`

Error I am getting: `Update Error - Error occurred while compiling query in query: SemanticError:0x00000006 at 2:36 : Undefined symbol: date-time`

**Comment by v-muuppugund** [comment] 2024-03-11 16:22
> > > Any status updates on this issue? Also running into the same issue, if someone has a fix or details about a workaround that would be appreciated.
> > 
> > 
> > Hi @thom2804 , Working on it ,will update you, As a work around could you please check option 6
> 
> Option 6 is the part of the steps where I am running into the issues, all the other options work fine, I am just unable to get the Transform action with the provided KQL query to work on the Custom Text log data source. I have tried both the manual and the automatic version.
> 
> Query which is giving issues: `source| extend TimeGenerated = todatetime(['date-time'])| extend clientHostname = ['client-hostname'], clientIP = ['client-ip'], connectorId = ['connector-id'], customData = ['custom-data'], eventId = ['event-id'], internalMessageId = ['internal-message-id'], logId = ['log-id'], messageId = ['message-id'], messageInfo = ['message-info'], messageSubject = ['message-subject'], networkMessageId = ['network-message-id'], originalClientIp = ['original-client-ip'], originalServerIp = ['original-server-ip'], recipientAddress= ['recipient-address'], recipientCount= ['recipient-count'], recipientStatus= ['recipient-status'], relatedRecipientAddress= ['related-recipient-address'], returnPath= ['return-path'], senderAddress= ['sender-address'], senderHostname= ['server-hostname'], serverIp= ['server-ip'], sourceContext= ['source-context'], schemaVersion=['schema-version'], messageTrackingTenantId = ['tenant-id'], totalBytes = ['total-bytes'], transportTrafficType = ['transport-traffic-type']| project-away ['client-ip'], ['client-hostname'], ['connector-id'], ['custom-data'], ['date-time'], ['event-id'], ['internal-message-id'], ['log-id'], ['message-id'], ['message-info'], ['message-subject'], ['network-message-id'], ['original-client-ip'], ['original-server-ip'], ['recipient-address'], ['recipient-count'], ['recipient-status'], ['related-recipient-address'], ['return-path'], ['sender-address'], ['server-hostname'], ['server-ip'], ['source-context'], ['schema-version'], ['tenant-id'], ['total-bytes'], ['transport-traffic-type']`
> 
> Error I am getting: `Update Error - Error occurred while compiling query in query: SemanticError:0x00000006 at 2:36 : Undefined symbol: date-time`

Sorry option 6 fix i am working ,Could you please try other options,For option 6 ,i am working on it,will update you

**Comment by thom2804** [comment] 2024-03-12 10:28
> > > > Any status updates on this issue? Also running into the same issue, if someone has a fix or details about a workaround that would be appreciated.
> > > 
> > > 
> > > Hi @thom2804 , Working on it ,will update you, As a work around could you please check option 6
> > 
> > 
> > Option 6 is the part of the steps where I am running into the issues, all the other options work fine, I am just unable to get the Transform action with the provided KQL query to work on the Custom Text log data source. I have tried both the manual and the automatic version.
> > Query which is giving issues: `source| extend TimeGenerated = todatetime(['date-time'])| extend clientHostname = ['client-hostname'], clientIP = ['client-ip'], connectorId = ['connector-id'], customData = ['custom-data'], eventId = ['event-id'], internalMessageId = ['internal-message-id'], logId = ['log-id'], messageId = ['message-id'], messageInfo = ['message-info'], messageSubject = ['message-subject'], networkMessageId = ['network-message-id'], originalClientIp = ['original-client-ip'], originalServerIp = ['original-server-ip'], recipientAddress= ['recipient-address'], recipientCount= ['recipient-count'], recipientStatus= ['recipient-status'], relatedRecipientAddress= ['related-recipient-address'], returnPath= ['return-path'], senderAddress= ['sender-address'], senderHostname= ['server-hostname'], serverIp= ['server-ip'], sourceContext= ['source-context'], schemaVersion=['schema-version'], messageTrackingTenantId = ['tenant-id'], totalBytes = ['total-bytes'], transportTrafficType = ['transport-traffic-type']| project-away ['client-ip'], ['client-hostname'], ['connector-id'], ['custom-data'], ['date-time'], ['event-id'], ['internal-message-id'], ['log-id'], ['message-id'], ['message-info'], ['message-subject'], ['network-message-id'], ['original-client-ip'], ['original-server-ip'], ['recipient-address'], ['recipient-count'], ['recipient-status'], ['related-recipient-address'], ['return-path'], ['sender-address'], ['server-hostname'], ['server-ip'], ['source-context'], ['schema-version'], ['tenant-id'], ['total-bytes'], ['transport-traffic-type']`
> > Error I am getting: `Update Error - Error occurred while compiling query in query: SemanticError:0x00000006 at 2:36 : Undefined symbol: date-time`
> 
> Sorry option 6 fix i am working ,Could you please try other options,For option 6 ,i am working on it,will update you

No problem, the oher options are already configured and work properly, just waiting on a fix for option 6.

**Comment by slivoski** [comment] 2024-03-22 20:46
Also ran into this issue. Option 1 (ARM template) does deploy, but if try to modify the DCR you get the same error as manually creating the DCR and transformation 'Undefined symbol: date-time'.

**Comment by v-muuppugund** [comment] 2024-04-03 03:39
> Also ran into this issue. Option 1 (ARM template) does deploy, but if you try to modify the DCR you get the same error as manually creating the DCR and transformation 'Undefined symbol: date-time'.
> 
> Logs do not ingest, likely due to the transform error.

Checked on it,Will update you

**Comment by v-muuppugund** [comment] 2024-04-07 09:24
Hi @FormindMPO / @slivoski  ,Could you please update the following query in transformation editor and create custom log 
 source | extend TimeGenerated = todatetime(['date-time']) | extend clientHostname = ['client-hostname'], clientIP = ['client-ip'], connectorId = ['connector-id'], customData = ['custom-data'], eventId = ['event-id'], internalMessageId = ['internal-message-id'], logId = ['log-id'], messageId = ['message-id'], messageInfo = ['message-info'], messageSubject = ['message-subject'], networkMessageId = ['network-message-id'], originalClientIp = ['original-client-ip'], originalServerIp = ['original-server-ip'], recipientAddress= ['recipient-address'], recipientCount= ['recipient-count'], recipientStatus= ['recipient-status'], relatedRecipientAddress= ['related-recipient-address'], returnPath= ['return-path'], senderAddress= ['sender-address'], senderHostname= ['server-hostname'], serverIp= ['server-ip'], sourceContext= ['source-context'], schemaVersion=['schema-version'], messageTrackingTenantId = ['tenant-id'], totalBytes = ['total-bytes'], transportTrafficType = ['transport-traffic-type'] | project-away ['client-ip'], ['client-hostname'], ['connector-id'], ['custom-data'], ['date-time'], ['event-id'], ['internal-message-id'], ['log-id'], ['message-id'], ['message-info'], ['message-subject'], ['network-message-id'], ['original-client-ip'], ['original-server-ip'], ['recipient-address'], ['recipient-count'], ['recipient-status'], ['related-recipient-address'], ['return-path'], ['sender-address'], ['server-hostname'], ['server-ip'], ['source-context'], ['schema-version'], ['tenant-id'], ['total-bytes'], ['transport-traffic-type']

**Comment by v-muuppugund** [comment] 2024-04-07 09:26
> Hi @FormindMPO / @slivoski ,Apologies for delayed response,Could you please update the following query in transformation editor during custom dcr
source | extend TimeGenerated = todatetime(['date-time']) | extend clientHostname = ['client-hostname'], clientIP = ['client-ip'], connectorId = ['connector-id'], customData = ['custom-data'], eventId = ['event-id'], internalMessageId = ['internal-message-id'], logId = ['log-id'], messageId = ['message-id'], messageInfo = ['message-info'], messageSubject = ['message-subject'], networkMessageId = ['network-message-id'], originalClientIp = ['original-client-ip'], originalServerIp = ['original-server-ip'], recipientAddress= ['recipient-address'], recipientCount= ['recipient-count'], recipientStatus= ['recipient-status'], relatedRecipientAddress= ['related-recipient-address'], returnPath= ['return-path'], senderAddress= ['sender-address'], senderHostname= ['server-hostname'], serverIp= ['server-ip'], sourceContext= ['source-context'], schemaVersion=['schema-version'], messageTrackingTenantId = ['tenant-id'], totalBytes = ['total-bytes'], transportTrafficType = ['transport-traffic-type'] | project-away ['client-ip'], ['client-hostname'], ['connector-id'], ['custom-data'], ['date-time'], ['event-id'], ['internal-message-id'], ['log-id'], ['message-id'], ['message-info'], ['message-subject'], ['network-message-id'], ['original-client-ip'], ['original-server-ip'], ['recipient-address'], ['recipient-count'], ['recipient-status'], ['related-recipient-address'], ['return-path'], ['sender-address'], ['server-hostname'], ['server-ip'], ['source-context'], ['schema-version'], ['tenant-id'], ['total-bytes'], ['transport-traffic-type']

**Comment by v-muuppugund** [comment] 2024-04-11 05:45
Hi @FormindMPO / @slivoski / @thom2804 / @samet-ibis PR has been raised for the Option 6,Please find below PR link (https://github.com/Azure/Azure-Sentinel/pull/10274) as per our standard operating procedures. If you still need support for 	this issue(https://github.com/Azure/Azure-Sentinel/issues/9862), feel free to re-open at any time. Thank you for your co-operation!

**Comment by v-muuppugund** [comment] 2024-04-15 11:21
Hi @FormindMPO / @slivoski / @thom2804 / @samet-ibis, we have raised the PR with the enhancements. The changes will be reflected once the PR is merged.
PR link -
https://github.com/Azure/Azure-Sentinel/pull/10274

Thank you for your cooperation.

**Closed by v-muuppugund** 2024-04-15 11:21 UTC
Labels: enhancement, Connector
