### ISSUE TITLE
DataConnector Failed to connect, How to debug?

### ISSUE THREAD

**Issue by huangyingw** [Azure/Azure-Sentinel#6156] opened 2022-09-15 00:13 UTC
I am creating a Codeless Connector Platform (CCP) Connector to pull data from my data ware house.

I used "Deploy a custom template" service to create my custom Connector, from a json file:
Attached 
[marcass.txt](https://github.com/Azure/Azure-Sentinel/files/9570727/marcass.txt)
 is the json I used.

then in "Microsoft Sentinel" --> "Data connectors" --> search for the connector I created, and then "Open connector page", enter my key in the key textare, and "Connect".

I got following error:
```
    Failed to connect
    Unauthorized - Non-TransientException FlurlHttpException exception
```

This is the command I used to do the post request from console:
```
    curl 'https://marcasss.marcass.com/mcm/alerts?maxAlerts=1&alertCategoryList=kSecurity&alertStateList=kOpen&startDateUsecs=1662447600000000&endDateUsecs=1663052399999000' \
    -H 'accept: application/json, text/plain, */*' \
    -H 'accept-language: en-US,en;q=0.9,zh-CN;q=0.8,zh;q=0.7' \
    -H 'apiKey: 33e44eac-ce99-46df-7f4e-9ac39446a66e'
```

We are using 'apiKey: 33e44eac-ce99-46df-7f4e-9ac39446a66e' to authentication.

Most probably, my json file is incorrect, but the error message is too little to debug.
is there any better way to debug when my connector failed to connect?

**Comment by gbshankar07** [comment] 2022-12-14 03:22
I'm having the same issue, any updates on this thread? Thanks :)
![image](https://user-images.githubusercontent.com/120540772/207497418-c9150e94-48e3-4a72-9c5f-964904a8bd27.png)

**Comment by v-rbajaj** [comment] 2023-06-07 12:44
We wanted to check on the status of Issue https://github.com/Azure/Azure-Sentinel/issues/6156. The issue is pending for more than expected days. Please let us know if you need any assistance to review this Issue. As per our standard operating procedures if no response is received in the next 7 business days, we will close this Issue. Thank you for your cooperation.

**Comment by v-vdixit** [comment] 2023-06-15 05:25
Since we have not received a response in the last 7 days, we are closing your issue as per our standard operating procedures. If you still need support for this issue, feel free to re-open at any time. Thank you for your co-operation.

**Closed by v-vdixit** 2023-06-15 05:25 UTC
Labels: Codeless Connector Platform (CCP) Connector
