### ISSUE TITLE
Integrating InsightVM with Sentinel

### ISSUE THREAD

**Issue by ojomanuel** [Azure/Azure-Sentinel#11233] opened 2024-10-08 10:00 UTC
**Describe the bug**
The playbook from InsightVM to run scan runs and present to team, however the "select Scan Engine" and "Select asset" doesn't have dropdowns.

**To Reproduce**
1. Go to sentinel, select incident and 
2. Click on Run Playbook then select the Rapid7 Run Scan playbook
3. On the teams select the dropdown for either "select Scan Engine" and "Select asset"
4. See error - There is nothing to select on the drop down.

**Expected behavior**
The dropdown should have data. 

**Screenshots**
![image](https://github.com/user-attachments/assets/f8512ae4-a7e9-46f5-9c00-d0d898c146d0)

**Comment by v-rusraut** [comment] 2024-10-09 06:55
Hi @ojomanuel, Thanks for flagging this issue, we will investigate this issue and get back to you with some updates. Thanks!

**Comment by v-rusraut** [comment] 2024-10-15 08:44
Hi @ojomanuel, it looks like there’s an issue with the API key. Ensure the API key used has sufficient permissions to access scan engines and assets in InsightVM. The key should be generated by a user with Global Administrator or Site Owner permissions in InsightVM.

**Comment by ojomanuel** [comment] 2024-10-15 09:25
Hello, the user that generated the API Key is a global admin on InsightVM. The other playbooks are working as expected with the same API Key.

**Comment by v-rusraut** [comment] 2024-10-15 12:11
Hi @ojomanuel , do you have a test account for InsightVM? We need an API key to reproduce this issue.

**Comment by ojomanuel** [comment] 2024-10-15 12:50
Hello, I don't have a test account, but I can setup a call with the global administrator of InsightVM.

**Comment by v-rusraut** [comment] 2024-10-18 12:28
Hi @ojomanuel , Please test the below API using the Postman tool to check if you are able to retrieve data:
API: /v4/integration/scan/engine
For API documentation, please refer to the following link: https://help.rapid7.com/insightvm/en-us/api/integrations.html#tag/Scan/operation/getScanEngines

**Comment by v-rusraut** [comment] 2024-10-21 06:12
Hi @ojomanuel , we are waiting for response.

**Comment by v-rusraut** [comment] 2024-10-23 04:39
Hi @ojomanuel ,  we are waiting for your response on this issue. If you still need to keep this issue active, please respond to it in the next 2 days. If we don't receive a response by 25-10-2024 date, we will be closing this issue.

**Comment by ojomanuel** [comment] 2024-10-23 09:04
Hello,

We are reviewing internally, the suggestions given.

Feedback will be given when complete.

Regards

Get Outlook for Android<https://aka.ms/AAb9ysg>

Avwerosuo Ojo-Manuel
Team Lead
Cybersecurity Operations Center - Blue Team
8022721787
***@***.***
www.fidelitybank.ng
https://loyalty.fidelitybank.ng/
​Please think before you print this email.
The information contained in this email and any attachments may be legally privileged and confidential
________________________________

**Comment by v-rusraut** [comment] 2024-10-25 06:47
Hi @ojomanuel , we are waiting for your response.

**Comment by ojomanuel** [comment] 2024-10-25 18:40
Hello, we have tested the API with the global key, and we got a 200 OK response.

**Comment by v-rusraut** [comment] 2024-10-28 05:41
Hi @ojomanuel , We are working with respective team , we will update you.

**Comment by v-rusraut** [comment] 2024-10-30 06:24
Hi @ojomanuel , as discussed over the call, we found an issue with the API response. Did you get a chance to check that API issue?

**Comment by v-rusraut** [comment] 2024-11-07 10:36
Hi @ojomanuel ,  we are waiting for your response on this issue. If you still need to keep this issue active, please respond to it in the next 2 days. If we don't receive a response by 11-11-2024 date, we will be closing this issue.

**Comment by v-rusraut** [comment] 2024-11-12 10:55
Hi @ojomanuel , since we have not received a response in the last 5 days, we are closing your issue as per our standard operating procedures. If you still need support for this issue, feel free to re-open at any time. Thank you for your co-operation.

**Closed by v-rusraut** 2024-11-12 10:55 UTC
Labels: Playbook
