### ISSUE TITLE
Logicapp Action: Add entities

### ISSUE THREAD

**Issue by ETMRidge** [Azure/Azure-Sentinel#6356] opened 2022-10-11 07:41 UTC
**Is your feature request related to a problem? Please describe.**
I am looking at integration with various threat detections sources, which may be able to aggregate more entities into Sentinel for each incident.  However, there is no action in the logic app for this.

**Describe the solution you'd like**
Add a new action for the Azure Sentinel Logicapp section to add entities.  

**Describe alternatives you've considered**
Using comments, however, this does not display as well.  I have also considered adding additional alerts, though this feature does not exist either.

**Additional context**
N/A

**Comment by v-rbajaj** [comment] 2023-06-07 12:46
Hi @ETMRidge, We wanted to check on the status of Issue https://github.com/Azure/Azure-Sentinel/issues/6356. The issue is pending for more than expected days. Please let us know if you need any assistance to review this Issue. As per our standard operating procedures if no response is received in the next 7 business days, we will close this Issue. Thank you for your cooperation.

**Comment by v-rbajaj** [comment] 2023-06-15 05:28
Hi @ETMRidge, Since we have not received a response in the last 7 days, we are closing your issue https://github.com/Azure/Azure-Sentinel/issues/6356 as per our standard operating procedures. If you still need support for this issue, feel free to re-open at any time. Thank you for your co-operation.

**Closed by v-rbajaj** 2023-06-15 05:28 UTC
Labels: enhancement
