### ISSUE TITLE
OneLogin Data Code fails due to 'InvalidDataFormat' and 'InvalidOperation'

### ISSUE THREAD

**Issue by vimz123** [Azure/Azure-Sentinel#3544] opened 2021-11-25 07:57 UTC
Onelogin code when execution throws some of the errors  (please see  the error output). 
The first error occured in the line 'Invoke-WebRequest' and since this doesn't execute properly, the following code lines for POST throws an error too.

Currently used code is from here: https://github.com/Azure/Azure-Sentinel/blob/master/DataConnectors/OneLogin/OneLogin/run.ps1

2021-11-25T07:55:50.192 [Information] Executing 'Functions.OneLogin' (Reason='This function was programmatically called via the host APIs.', Id=43657418-b950-4e79-84c8-7e665dacb2bd)
2021-11-25T07:55:50.290 [Error] ERROR: Invoke-WebRequest : {"Error":"InvalidDataFormat","Message":null}At D:\home\site\wwwroot\OneLogin\run.ps1:50 char:17+ ... $response = Invoke-WebRequest -Uri $uri -Method $method -ContentType  ...+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~+ CategoryInfo          : InvalidOperation: (Method: POST, Reque\u2026application/json}:HttpRequestMessage) [Invoke-WebRequest], HttpResponseException+ FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommandScript stack trace:at Post-LogAnalyticsData, D:\home\site\wwwroot\OneLogin\run.ps1: line 50at <ScriptBlock>, D:\home\site\wwwroot\OneLogin\run.ps1: line 57Microsoft.PowerShell.Commands.HttpResponseException: Response status code does not indicate success: 400 (Bad Request).at System.Management.Automation.MshCommandRuntime.ThrowTerminatingError(ErrorRecord errorRecord)Microsoft.Azure.WebJobs.Script.Workers.Rpc.RpcException : Result: ERROR: Invoke-WebRequest : {"Error":"InvalidDataFormat","Message":null}At D:\home\site\wwwroot\OneLogin\run.ps1:50 char:17+ ... $response = Invoke-WebRequest -Uri $uri -Method $method -ContentType  ...+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~+ CategoryInfo          : InvalidOperation: (Method: POST, Reque\u2026application/json}:HttpRequestMessage) [Invoke-WebRequest], HttpResponseException+ FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommandScript stack trace:at Post-LogAnalyticsData, D:\home\site\wwwroot\OneLogin\run.ps1: line 50at <ScriptBlock>, D:\home\site\wwwroot\OneLogin\run.ps1: line 57Microsoft.PowerShell.Commands.HttpResponseException: Response status code does not indicate success: 400 (Bad Request).at System.Management.Automation.MshCommandRuntime.ThrowTerminatingError(ErrorRecord errorRecord)Exception: Response status code does not indicate success: 400 (Bad Request).Stack:    at System.Management.Automation.MshCommandRuntime.ThrowTerminatingError(ErrorRecord errorRecord)
2021-11-25T07:55:50.373 [Error] ERROR: Trace-PipelineObject : Cannot bind argument to parameter 'InputObject' because it is null.+ CategoryInfo          : InvalidData: (:) [Trace-PipelineObject], ParameterBindingValidationException+ FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.Azure.Functions.PowerShellWorker.Commands.TracePipelineObjectCommandScript stack trace:at Post-LogAnalyticsData, D:\home\site\wwwroot\OneLogin\run.ps1: line 52at <ScriptBlock>, D:\home\site\wwwroot\OneLogin\run.ps1: line 57System.Management.Automation.ParameterBindingValidationException: Cannot bind argument to parameter 'InputObject' because it is null.at System.Management.Automation.CmdletParameterBinderController.BindValueFromPipeline(PSObject inputToOperateOn, MergedCompiledCommandParameter parameter, ParameterBindingFlags flags)at System.Management.Automation.CmdletParameterBinderController.BindUnboundParametersForBindingStateInParameterSet(PSObject inputToOperateOn, CurrentlyBinding currentlyBinding, UInt32 validParameterSets)at System.Management.Automation.CmdletParameterBinderController.BindUnboundParametersForBindingState(PSObject inputToOperateOn, CurrentlyBinding currentlyBinding, UInt32 validParameterSets)at System.Management.Automation.CmdletParameterBinderController.BindPipelineParametersPrivate(PSObject inputToOperateOn)at System.Management.Automation.CmdletParameterBinderController.BindPipelineParameters(PSObject inputToOperateOn)at System.Management.Automation.CommandProcessor.Read()Microsoft.Azure.WebJobs.Script.Workers.Rpc.RpcException : Result: ERROR: Trace-PipelineObject : Cannot bind argument to parameter 'InputObject' because it is null.+ CategoryInfo          : InvalidData: (:) [Trace-PipelineObject], ParameterBindingValidationException+ FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.Azure.Functions.PowerShellWorker.Commands.TracePipelineObjectCommandScript stack trace:at Post-LogAnalyticsData, D:\home\site\wwwroot\OneLogin\run.ps1: line 52at <ScriptBlock>, D:\home\site\wwwroot\OneLogin\run.ps1: line 57System.Management.Automation.ParameterBindingValidationException: Cannot bind argument to parameter 'InputObject' because it is null.at System.Management.Automation.CmdletParameterBinderController.BindValueFromPipeline(PSObject inputToOperateOn, MergedCompiledCommandParameter parameter, ParameterBindingFlags flags)at System.Management.Automation.CmdletParameterBinderController.BindUnboundParametersForBindingStateInParameterSet(PSObject inputToOperateOn, CurrentlyBinding currentlyBinding, UInt32 validParameterSets)at System.Management.Automation.CmdletParameterBinderController.BindUnboundParametersForBindingState(PSObject inputToOperateOn, CurrentlyBinding currentlyBinding, UInt32 validParameterSets)at System.Management.Automation.CmdletParameterBinderController.BindPipelineParametersPrivate(PSObject inputToOperateOn)at System.Management.Automation.CmdletParameterBinderController.BindPipelineParameters(PSObject inputToOperateOn)at System.Management.Automation.CommandProcessor.Read()Exception: Cannot bind argument to parameter 'InputObject' because it is null.Stack:    at System.Management.Automation.CmdletParameterBinderController.BindValueFromPipeline(PSObject inputToOperateOn, MergedCompiledCommandParameter parameter, ParameterBindingFlags flags)at System.Management.Automation.CmdletParameterBinderController.BindUnboundParametersForBindingStateInParameterSet(PSObject inputToOperateOn, CurrentlyBinding currentlyBinding, UInt32 validParameterSets)at System.Management.Automation.CmdletParameterBinderController.BindUnboundParametersForBindingState(PSObject inputToOperateOn, CurrentlyBinding currentlyBinding, UInt32 validParameterSets)at System.Management.Automation.CmdletParameterBinderController.BindPipelineParametersPrivate(PSObject inputToOperateOn)at System.Management.Automation.CmdletParameterBinderController.BindPipelineParameters(PSObject inputToOperateOn)at System.Management.Automation.CommandProcessor.Read()
2021-11-25T07:55:50.433 [Information] Executed 'Functions.OneLogin' (Succeeded, Id=43657418-b950-4e79-84c8-7e665dacb2bd, Duration=242ms)

**Comment by vimz123** [comment] 2021-12-06 08:36
Hi Team,

We have this observation that when explicitly converting to JSON post function eventlogs, the code is working and the events are forwarded to LogAnalytics and with the original code without having any json convert, the code is throwing the errors:
Please find the screenshot for two of the scenarios and let us know your findings.

Output 1: POST Function eventlogs without JSON convert:
 
![image](https://user-images.githubusercontent.com/95017817/144813552-65b8b109-108a-4065-8e31-daf80876dad0.png)

Output 2: POST Function eventlogs with JSON convert:
 
![image](https://user-images.githubusercontent.com/95017817/144813598-da6f4642-7fb0-44fb-ab90-ebb4e4f7aefc.png)

**Comment by v-mchatla** [comment] 2022-10-28 07:39
Hi @vimz123,
Are you still seeing the issue? I have tried reproducing the issue, but not able to do as I don't have bearer token. 
![image](https://user-images.githubusercontent.com/108806639/198530731-f45d2973-77d3-454c-9984-88f8adfd5156.png)

![image](https://user-images.githubusercontent.com/108806639/198530529-8622ecbe-3668-4255-a0c5-e9727dd73c72.png)

**Comment by v-amolpatil** [comment] 2023-01-31 14:05
Since we have not received a response in the last 5 days, we are closing your issue #3544 as per our standard operating procedures. If you still need support for this issue, feel free to re-open at any time. Thank you for your co-operation.

**Closed by v-amolpatil** 2023-01-31 14:05 UTC
Labels: Connector
