### ISSUE TITLE
Parser File chnages

### ISSUE THREAD

**Issue by IH2by2** [Azure/Azure-Sentinel#2970] opened 2021-09-06 13:31 UTC
Hello,

I believe there are three lines in the parser file causes the data connector to fail.  This is the file that is added by the setup script
There is a blank line at line 1

Both project-rename lines don't seem to be able to be resolved.
ThreatName=threat_s
EventSubType=origin_s 

Thanks,

**Comment by oshezaf** [comment] 2021-09-06 18:15
@IH2by2 : working by phone, so might have missed something,  but i cant see which file you refer to.

Thanks for raising the issue!
~ Ofer

**Comment by IH2by2** [comment] 2021-09-07 08:00
Hi Ofer no worries,

the main file is https://github.com/Azure/Azure-Sentinel/blob/master/Solutions/SophosEP/Parsers/SophosEPEvent.txt.  I'm guessing there is some code that copies and saves it as a function and this is where a blank line is added to the top.

Martin

**Comment by oshezaf** [comment] 2021-09-12 07:47
Hi @IH2by2 ,

I am in charge of [ASIM](https://docs.microsoft.com/en-us/azure/sentinel/normalization), which does include many parsers, but not this one, so reassigned. Sorry for the added delay. 

@sarah-yo : FYI

**Comment by v-mchatla** [comment] 2022-11-10 06:46
Hi @IH2by2,
Sorry for the delay. we have started working on the issues recently.
I have verified the parser and didn't see any issue; seems the issue is resolved by now. 
Can you please confirm if you still see issue and need any help from us.
![image](https://user-images.githubusercontent.com/108806639/201018658-05a90ec6-5c2e-429d-b199-f576a64d7492.png)

**Comment by v-mchatla** [comment] 2022-11-16 11:56
Hi @IH2by2,
Closing the issue as its fixed. Please feel free to reopen if you still facing the issue.
Thanks

**Closed by v-mchatla** 2022-11-16 11:56 UTC
Labels: Parser
