### ISSUE TITLE
Unable to define Alert only Analytics Rules for solution

### ISSUE THREAD

**Issue by keyoke** [Azure/Azure-Sentinel#6544] opened 2022-11-02 14:24 UTC
**Describe the bug**
Unable to define Alert only Analytics Rules for solution

**To Reproduce**
1. Create Alert only Analytics Rule YAML file with the following configuration

incidentConfiguration:
  createIncident: false
  groupingConfiguration:
    enabled: false
2.  run ./Tools/Create-Azure-Sentinel-Solution/V2/createSolutionV2.ps1
3. verify in packages/maniTemplate.json that incidentConfiguration is not emitted in resulting ARM template

**Expected behavior**
ARM Template should contain

                "incidentConfiguration": {
                  "createIncident": false,
                  "groupingConfiguration": {
                    "enabled": false
                  }
                }

**Comment by v-rucdu** [comment] 2022-11-10 04:39
@keyoke: Thanks for fixing the issue, the PR having fix for this issue is merged and so closing this issue as well. Please feel free to reopen if the issue is still there... Thanks!!!

**Closed by v-rucdu** 2022-11-10 04:39 UTC
