### ISSUE TITLE
It seems that #4341 has reappeared in the isolate-MDEMachine playbook

### ISSUE THREAD

**Issue by TimGjerlufsen** [Azure/Azure-Sentinel#6691] opened 2022-11-21 13:16 UTC
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by v-laanjana** [comment] 2022-12-13 10:12
[@TimGjerlufsen please add description and created new issue ](https://github.com/Azure/Azure-Sentinel/issues/4341)

**Comment by v-laanjana** [comment] 2022-12-13 10:12
https://github.com/Azure/Azure-Sentinel/issues/4341

**Comment by v-rbajaj** [comment] 2023-06-07 12:48
We wanted to check on the status of Issue https://github.com/Azure/Azure-Sentinel/issues/6691. The issue is pending for more than expected days. Please let us know if you need any assistance to review this Issue. As per our standard operating procedures if no response is received in the next 7 business days, we will close this Issue. Thank you for your cooperation.

**Comment by v-vdixit** [comment] 2023-06-15 05:28
Since we have not received a response in the last 7 days, we are closing your issue as per our standard operating procedures. If you still need support for this issue, feel free to re-open at any time. Thank you for your co-operation.

**Closed by v-vdixit** 2023-06-15 05:28 UTC
Labels: Playbook
