### ISSUE TITLE
Parameters are inconsistely 

### ISSUE THREAD

**Issue by asheikh80** [Azure/Azure-Sentinel#8030] opened 2023-05-11 19:56 UTC
When we export the logic apps using this powershell script
it some time doesn't copy parameters but the other time it copies it.
it put all the logic apps in one single resource group and created duplicate logic apps

**Comment by v-rbajaj** [comment] 2023-05-15 13:05
Hi @asheikh80, can you please specify which powershell script are you using in order to perform the activity?

**Comment by asheikh80** [comment] 2023-05-15 15:52
Hi,

This is the one I am trying to execute.

***@***.***

Regards
Arshad Sheikh, Azure Solutions Architect Expert, Azure Security Engineer
AWS Solutions Architect, AWS SOA, MCAA Azure, MCMA O365, CCIE-DC
Senior Cloud Services Expert
Community& Government Services
Informatics Planning & Services
Address: P. O. Box 1000, Station 660
W. G. Brown Building

***@***.***

**Comment by v-vdixit** [comment] 2023-05-29 07:14
Hi @asheikh80 Please add some screenshots related to the exact error you're facing, it will help us in tracing the root cause better, thanks!

**Comment by v-rbajaj** [comment] 2023-06-05 04:55
Gentle Reminder: We are awaiting for your response on this issue. If you still need to keep this issue active please respond on it in the next 2 days. If we don't receive response, we will be close this issue.

**Comment by v-rbajaj** [comment] 2023-06-08 06:12
Since we have not received a response in the last 5 days, we are closing your issue https://github.com/Azure/Azure-Sentinel/issues/8030 as per our standard operating procedures. If you still need support for this issue, feel free to re-open at any time. Thank you for your co-operation.

**Closed by v-rbajaj** 2023-06-08 06:12 UTC
Labels: Tools
