### ISSUE TITLE
Cisco WSA parser not working with CiscoOS 12.5

### ISSUE THREAD

**Issue by PDarvMSFT** [Azure/Azure-Sentinel#4784] opened 2022-05-04 20:19 UTC
**Describe the bug**
Problem with the parser of Cisco WSA solution ( https://github.com/Azure/Azure-Sentinel/tree/master/Solutions/CiscoWSA ) . Our version of CiscoOS (12.5.2-011) seems to be adding an extra field at the beginning of the syslog message, like this:

**Info: XXX456XXX91.XXX XX 12X.X5X.X8X.XXX TCP_MISS_SSL/123 123 POST [https://www.xxxx](https://linkXXX) "ABC\abcd001@ABC" DIRECT/www.xxx.xx - DEFAULT_CASE_12-PAABC-IDMiro-NONE-NONE-NONE-DefaultGroup-NONE <"IW_comp",1.0,0,"-",0,0,0,-,"-",-,-,-,"-",-,-,"-","-",-,-,"IW_comp",-,"-","Computers and Internet","-","Unknown","Unknown","-","-",12.12,0,-,"Unknown","-",-,"-",-,-,"-","-",-,-,"-",-,-> - -**

Seems like all the fields are what is expected, except for the first part, which is " Info: ". We are able to modify the parser to trim the first part of the message like this:

**let cisco_wsa_access_logs =() {
Syslog
| where SyslogMessage matches regex @"\d{10}\.\d{3}\s\d+\s\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}"
| extend EventVendor = 'Cisco'
| extend EventProduct = 'Web Security Appliance'
| extend EventType = 'Access Log'
| extend TrimmedSyslogMessage = trim_start("Info: ", SyslogMessage)
| extend EventFields = split(TrimmedSyslogMessage, ' ')**

Unfortunately, this modification slows down the function quite a lot, and the associated Workbook takes 10 to 15 minutes to show data.

**To Reproduce**
1. CiscoWSA version is CiscoOS 12.5
2. Send logs to CEF log forwarder
3. Enable Cisco WSA content hub solution in Sentinel

**Comment by Minifab** [comment] 2022-05-10 15:35
Hi i also have this issue, any idea someone ?

**Comment by NikTripathi** [comment] 2022-05-24 12:34
@philippedarveauhot 

> @philippedarveauhot : we have further optimized the parser to trim the Info text from the start of the SyslogMessage, we would need your help to test this and let us know if it improves performance. The latest parser can be found [here](https://raw.githubusercontent.com/Azure/Azure-Sentinel/v-rucdu/CiscoWSAVersionUpdateToParserICM/Solutions/CiscoWSA/Parsers/CiscoWSAEvent.txt).... Thanks!!!

@philippedarveauhot Did you get a chance to check the latest parser? Can you please confirm if it is working as expected? Thanks!!!

**Comment by NikTripathi** [comment] 2022-05-26 12:49
@philippedarveauhot  Did you get a chance to check the latest parser? Can you please confirm if it is working as expected? Thanks!!!

**Comment by philippedarveauhot** [comment] 2022-05-26 17:56
> @philippedarveauhot Did you get a chance to check the latest parser? Can you please confirm if it is working as expected? Thanks!!!

I will test it tomorrow and get back to you then. Thanks!

**Comment by philippedarveauhot** [comment] 2022-05-27 20:20
Had a chance to test today and the parser is not working with our data. The problem is with the regular expression "SyslogMessage matches regex @"\A\d{10}\.\d{3}\s\d+\s\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}"" . If we remove the "\A" like this, it works: "\d{10}\.\d{3}\s\d+\s\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}" . For a time range of 6 days, query takes a little more than 7 seconds to run. We have modified the parser a bit and are able to cut this down to 5 seconds. Our parser is attached here. Thank you
[CiscoWSAEvent_VersionFrancis.txt](https://github.com/Azure/Azure-Sentinel/files/8789544/CiscoWSAEvent_VersionFrancis.txt)
.

**Comment by v-rucdu** [comment] 2022-05-30 13:26
@philippedarveauhot : Thanks for your response... we will check this updated parser and try to future optimize it if possible... Thanks!!

**Comment by v-rucdu** [comment] 2022-08-10 11:35
@PDarvMSFT : As there is no action needed from our end, i am closing this issue. Please feel free to reopen it if needed.... Thanks!!!

**Closed by v-rucdu** 2022-08-10 11:35 UTC
Labels: fix in progress

**Comment by rosemarvin** [comment] 2023-01-05 15:39
Hi @v-rucdu,
we deployed the Cisco WSA content hub solution in sentinel today and ingested some data.
Unfortunately the parser didn't work so I came across this issue here.

The content hub solution does not have the parser you linked [to](https://raw.githubusercontent.com/Azure/Azure-Sentinel/v-rucdu/CiscoWSAVersionUpdateToParserICM/Solutions/CiscoWSA/Parsers/CiscoWSAEvent.txt). Furthermore, as above described by @PDarvMSFT in the regex, I had to remove that "\A" so that the parser worked.

Is this conscious? Is there any particular reason why the parser is not yet deployed?
Thanks!
