### ISSUE TITLE
Playbook-ARM-Template-Generator - sanitize tags and arm api connector

### ISSUE THREAD

**Issue by seanstark** [Azure/Azure-Sentinel#6751] opened 2022-11-29 21:08 UTC
**Is your feature request related to a problem? Please describe.**

- The Playbook-ARM-Template-Generator doesn't currently remove existing tags from the generated arm template.
- The Playbook-ARM-Template-Generator doesn't currently sanitize subscription ids from specific arm connections.

**Describe the solution you'd like**
Add support to remove all tag properties and values

**Example**
![example](https://user-images.githubusercontent.com/84108246/204647835-39ccab3a-57db-43c3-9d4d-ec33a3f77dc3.png)

**Comment by v-vdixit** [comment] 2023-06-08 10:24
Hi @seanstark We wanted to check on the status of Issue #6751. The issue is pending for more than expected days. Please let us know if you need any assistance to review this Issue. As per our standard operating procedures if no response is received in the next 7 business days, we will close this Issue. Thank you for your cooperation.

**Comment by v-vdixit** [comment] 2023-06-15 05:31
Since we have not received a response in the last 7 days, we are closing your issue as per our standard operating procedures. If you still need support for this issue, feel free to re-open at any time. Thank you for your co-operation.

**Closed by v-vdixit** 2023-06-15 05:31 UTC
Labels: enhancement, Tools
