### ISSUE TITLE
Playbook-ARM-Template-Generator - setting unique file name

### ISSUE THREAD

**Issue by csplighthouse** [Azure/Azure-Sentinel#5603] opened 2022-07-12 23:26 UTC
When using ARM template generator to export multiple playbooks they land in the folders with the correct playbook name but the JSON files name is the same for all exports i.e azuredeploy.json

This then causes issues when we try to upload our ARM templates to Gibhub for syncing back to Sentinel. Would it be possible to also set the json file name to match the playbook name?

Thanks

**Comment by v-rbajaj** [comment] 2023-06-07 12:43
We wanted to check on the status of Issue https://github.com/Azure/Azure-Sentinel/issues/5603 . The issue is pending for more than expected days. Please let us know if you need any assistance to review this Issue. As per our standard operating procedures if no response is received in the next 7 business days, we will close this Issue. Thank you for your cooperation.

**Comment by v-rbajaj** [comment] 2023-06-15 05:24
Since we have not received a response in the last 5 days, we are closing your issue https://github.com/Azure/Azure-Sentinel/issues/5603 as per our standard operating procedures. If you still need support for this issue, feel free to re-open at any time. Thank you for your co-operation.

**Closed by v-rbajaj** 2023-06-15 05:24 UTC
Labels: enhancement, Playbook, Tools
