### ISSUE TITLE
TI map IP entity to FrontDoorHTTPLogs

### ISSUE THREAD

**Issue by Jeremyp87** [Azure/Azure-Sentinel#5292] opened 2022-06-13 13:51 UTC
**Describe the solution you'd like**
I would like to be able to map TI to log analytics for traffic allowed trough Frontdoor without a Firewall rule hit. Traffic is already logged in FrontDoor Diagnostics and logging from AppService as well is pointless.

**Describe alternatives you've considered**
Log from AppServiceHTTPLogs as well, would increase costs.

Relevant Analytic Rule: "TI map IP entity to AppServiceHTTPLogs"

**Comment by v-rbajaj** [comment] 2023-06-07 12:19
Hi @Jeremyp87, We wanted to check on the status of Issue https://github.com/Azure/Azure-Sentinel/issues/5292 . The issue is pending for more than expected days. Please let us know if you need any assistance to review this Issue. As per our standard operating procedures if no response is received in the next 7 business days, we will close this Issue. Thank you for your cooperation.

**Comment by v-vdixit** [comment] 2023-06-15 05:21
Since we have not received a response in the last 7 days, we are closing your issue as per our standard operating procedures. If you still need support for this issue, feel free to re-open at any time. Thank you for your co-operation.

**Closed by v-vdixit** 2023-06-15 05:21 UTC
Labels: enhancement, Detection
