### ISSUE TITLE
Unable to remove Syslog via Legacy Agent data connector

### ISSUE THREAD

**Issue by thom2804** [Azure/Azure-Sentinel#11154] opened 2024-09-19 15:05 UTC
I currently still have the Syslog via Legacy Agent dataconnector active in a couple of different Sentinel environments, however this dataconnector has been renamed in an update to Syslog where the connectivity criteria has been updated to exclude the logs from the new AMA agent, therefore it still detects logs coming in on the legacy agent while those are actually coming from the AMA agent.
his results in having a duplication of dataconnectors.

Is it possible to rename this Syslog dtaconnector back to the original name where it was called: Syslog via Legacy Agent so people with that stuck like me can remove it from their environments.

**Comment by v-rusraut** [comment] 2024-09-23 09:47
Hi @thom2804,

As the connectivity criteria updated to exclude the logs from the new AMA agent, so that Syslog via legacy data connector showing as disconnected then we can delete Syslog via legacy data connector with below steps.

- Search Syslog via Legacy dataconnector in Data Connector section.

![image](https://github.com/user-attachments/assets/7afa2ce2-7042-4727-ad75-95bc7b407324)

- Click on delete button to delete data connector.
 
![image](https://github.com/user-attachments/assets/beb661a1-303f-480e-83dd-af33c707cd2a)

- Please confirm delete , after that legacy data connector will be deleted.
 
![image](https://github.com/user-attachments/assets/10f3e36b-479c-4b58-bde6-4e22944a8be4)
Please let us know that your issue resolved or not.

**Comment by v-rusraut** [comment] 2024-09-24 09:17
Hi @thom2804, we reached out to respective team for this issue, and as a team mentioned that you need to raise a support case for this issue, as support team have the backend access to find the root cause of this issue. and if required the support team can forward the ticket to respective teams. So, we are closing this issue from GitHub. If you still need support for this issue, feel free to re-open it any time. Thank you for your co-operation.

**Closed by v-rusraut** 2024-09-24 09:17 UTC
Labels: AMA_Connector
