### ISSUE TITLE
%%2089 Value Resolution in password_never_expires.yaml clarification

### ISSUE THREAD

**Issue by kaovd** [Azure/Azure-Sentinel#1399] opened 2020-12-03 14:33 UTC
Describe the bug

The resolved value of User account properties of %%2089 in the "password_never_expires.yaml" rule apparently resolves to "Don't expire password" setting being disabled, however it seems some sources dispute this? 

For example - [this source ](https://books.google.co.uk/books?id=oEJRDwAAQBAJ&pg=PA152&dq=%22%25%252089%22+%22Enabled%22&hl=en&sa=X&ved=2ahUKEwje_P-ggLLtAhU9QUEAHUVOD7kQ6AEwAHoECAYQAg#v=onepage&q=%22%25%252089%22%20%22Enabled%22&f=false)explicitly states that 2089 resolves to Don't Expire Password - Enabled, meaning password never expires is set. This is slightly confusing. See below:

`// 2089 value indicates the Don't Expire Password value has been set
  | where UserAccountControl has "%%2089" 
  | extend Value_2089 = iff(UserAccountControl has "%%2089","'Don't Expire Password' - Disabled", "Not Changed")`

**Comment by shainw** [comment] 2020-12-06 17:45
@kaovd - I believe this is a typo and it should be "'Don't Expire Password' - Enabled".  We will test and confirm.

**Comment by kaovd** [comment] 2020-12-10 21:26
Additonally to mention I believe the "has in" on line 27 `| where UserAccountControl has "%%2089" ` excludes everything that dosen't have that in the query? I.e if only password not required is set on a user account, this will not show up within the query.

**Comment by shainw** [comment] 2020-12-25 01:46
@kaovd - this is fixed in PR #1532.  In relation to the line 27, this is by design, we only want events with 2089, but often the UAC value will have other value accompanying the 2089, so we parse and label those for context.

**Closed** 2020-12-25 01:46 UTC
