### ISSUE TITLE
Cisco ASA/FTD via AMA doesn't forward FTD logs via eNcore eSteamer

### ISSUE THREAD

**Issue by cyberpope** [Azure/Azure-Sentinel#10938] opened 2024-08-07 13:04 UTC
**Describe the bug**
Syslog forwarder is configured to receive syslog messages from multiple devices and forward to Sentinel via AMA using syslog-ng.
DCR is configured for Cisco ASA/FTD via AMA connector to parse all messages from local2 facility.
FTDs logs are being parsed by eNcore eStreamer and forwarded to syslog server. The logs are forwarded on the correct facility via eNcore eStreamer adapter configuration change.
However when parsed via syslog connector logs available in syslog table, hence the issue has to be ASA/FTD via AMA connector.

**To Reproduce**
Configure eNcore eSteamer to forward logs on local2 facility
Configure DCR to accepts ASA/FTD cef logs from syslog server on local2 facility.

**Expected behavior**
FTD logs parsed and available in CommonSecurityLog table

**Screenshots**
TCP dump
![image](https://github.com/user-attachments/assets/b88142d5-4bec-4ebb-8600-ae2af75e79be)
Syslog table with FTD message when parsed via syslog connector.
![image](https://github.com/user-attachments/assets/674c5865-44ff-4469-9060-cb0789397579)

**Desktop (please complete the following information):**
 - OS: Syslog server Ubuntu
 - Browser N/A
 - Syslog version 3.27

**Smartphone (please complete the following information):**
N/A

**Additional context**
Logs are parsed and in the right table if forwarded via eNcore eSteamer via legacy MMA.

**Comment by v-sudkharat** [comment] 2024-08-12 06:00
Hi @cyberpope, Thanks for flagging this issue, we will investigate this issue and get back to you with some updates. Thanks!

**Comment by cyberpope** [comment] 2024-08-20 13:47
Hi @v-sudkharat we have confirmed the configuration for syslog data directly from FMC and it behaves the as when forwarded via eNcore eStreamer.

**Comment by v-rusraut** [comment] 2024-09-05 08:50
Hi @cyberpope,
Could you please help us with the details of the DCR that you're using for this, thanks!

**Comment by cyberpope** [comment] 2024-09-05 08:56
Hello @v-rusraut,

It's a simple DCR created via Sentinel's Data Connectors page.
![AMA DCR for ASAFTD](https://github.com/user-attachments/assets/25971807-ac32-4706-8fa2-68d7d1b6aa2e)
![image](https://github.com/user-attachments/assets/a6e6d48d-6385-4bc8-a136-5d859e126458)


All the data goes via syslog forwarder and it's collected from it.

**Comment by v-rusraut** [comment] 2024-09-05 10:20
Hi @cyberpope,
Please check what is the value of stream in data collection rule.
Please refer below steps

- On marketplace search data collection rule
![image](https://github.com/user-attachments/assets/579f6bd0-8d4c-4d81-b3e7-cbb35704f1b8)

- Search your Data collection Rule 
![Cisco1](https://github.com/user-attachments/assets/f8934404-368f-47e4-aa98-bde21378664a)

- Click on json view 
![image](https://github.com/user-attachments/assets/140ad626-6b8f-4070-84d5-0395ec1b9796)

- Check the value of stream

![image](https://github.com/user-attachments/assets/71397fe2-e28a-46c0-b7dd-5d048413dae2)

**Comment by cyberpope** [comment] 2024-09-05 10:36
@v-rusraut Ah my apologies
The data stream is Microsoft-CIscoAsa
![image](https://github.com/user-attachments/assets/ab281259-3f76-46f7-98d5-dbf83d70b199)

**Comment by v-rusraut** [comment] 2024-09-05 12:06
Hi @cyberpope,
Please provide few sample logs to below email id, we will try to reproduce this issue.
Email ID : v-rusraut@microsoft.com

Thanks

**Comment by v-rusraut** [comment] 2024-09-09 04:56
Hi @cyberpope, Gentle Reminder: We are waiting for your response on this issue. If you still need to keep this issue active, please respond to it in the next 2 days. If we don't receive a response by 11-09-2024 date, we will be closing this issue.
Thanks!

**Comment by cyberpope** [comment] 2024-09-11 08:16
Hello @v-rusraut sorry I was on annual leave, I'll provide you with the logs today.

**Comment by cyberpope** [comment] 2024-09-11 10:11
Hello @v-rusraut, Apologies I won't be able to submit the data today as there is a priority matter in my workplace to take care off, please give me a couple more days to work on it.

**Comment by Oraclese-cyber** [comment] 2024-09-13 22:59
Im having similar issues.

@cyberpope - It appears you are trying to bring in CEF-formatted estreamer logs.  I believe the Cisco ASA/FTD via AMA data connector is used to bring in SYSLOG messages from these devices (logs staring with "%ASA-" or "%FTD-"), and format them for ingestion into the CommonSecurityLog table.  This is similar to how ingestion worked with the Legacy agent, except ASA/FTD was handled with a string eval in a configuration file for the OMS agent.

https://learn.microsoft.com/en-us/azure/sentinel/unified-connector-cef-device

The above link identifies that FirePower (FTD) devices should be configured using the CEF via AMA data connector.  This has the following data stream defined:

"streams": [
                                "Microsoft-CommonSecurityLog"
                            ],

Now, obviously your DCR (or another generic Syslog DCR?) is still picking up these Firepower estreamer logs.  This is the issue I'm having - I'm getting these Firepower estreamer logs in both my Syslog and CommonSecurityLog tables.  This is due to me having 2 DCRs applied to the EnCore server - one for Syslog via AMA to capture the actual system logs from the EnCore server, and one for CEF via AMA data connector to get the estreamer logs.  The issue is I have need for the "user" facility logs from the Syslog messages (primarily for tracking user-caused system changes), but the Firepower estreamer logs also come in with the "user" facility.  I can't just drop the facility from my Syslog via AMA DCR, so I get logs in both tables.

I'd also like to change the facility of the logs coming from estreamer/encore (preferably to local7).  Can you explain how you were able to do that on EnCore?  Did you simply modify the estreamer.conf (and if so, how), or was this configured elsewhere?

We are going to be putting in a support ticket with Cisco for this as well, but thought I would share my experience.  If I make any progress, I'll try to come back here to share.

**Comment by cyberpope** [comment] 2024-09-16 11:07
@Oraclese-cyber 
I just confirmed on both of the scenarios.
When forwarding logs directly from firewalls via FMC config the logs still do not show in CommonEventLog table.
When forwarding logs via eNcore they indeed show in CommonEventLog when forwarded to CEF DCR, this is already a big improvement as now we can get rid of legacy MMA syslogers.
Thank you.

**Comment by Oraclese-cyber** [comment] 2024-09-16 13:34
@cyberpope - did this have any impact on how the facility ingested into sentinel?  Is your re-write to local2 now being picked up by the DCR?

**Comment by cyberpope** [comment] 2024-09-16 13:36
@Oraclese-cyber yes, the rewrite using syslog-ng happens prior to logs being shipped to AMA so the re-write works as intended and AMA picks the logs with correct facility.

**Comment by v-rusraut** [comment] 2024-09-17 07:00
Hi @cyberpope, after rewrite using syslog-ng, did it resolve your issue or still logs not coming?

**Comment by cyberpope** [comment] 2024-09-17 08:00
Hello @v-rusraut, we were already re-writing the log messages prior to me submitting this GitHub issue.
However now we are only struggling with FTDs forwarding the logs to AMA directly rather than via eNcore.
We are able to push FTD logs via eNcore using CEF data connector, but still not directly.
The logs which I sent you are direct logs rather than via eNcore.

**Comment by v-rusraut** [comment] 2024-09-18 06:49
Hi @cyberpope,
We are working with respective team, we will update you.
Thanks

**Comment by v-rusraut** [comment] 2024-09-19 13:12
Hi @cyberpope,
We reached out to respective team for this issue, and as a team mentioned that you need to raise a support case for this issue, as support team have the backend access to find the root cause of this issue. and if required the support team can forward the ticket to respective teams. So, we are closing this issue from GitHub. If you still need support for this issue, feel free to re-open it any time. Thank you for your co-operation.

**Closed by v-rusraut** 2024-09-19 13:12 UTC
Labels: AMA_Connector

**Comment by Oraclese-cyber** [comment] 2024-09-25 17:06
Update:  Changed the facility of logs in estreamer.conf to local7 (code 23) on the EnCore server - no credit to Cisco (we ended up just closing the ticket).  Estreamer logs are being properly captured by our CEF via AMA DCR, which only captures local7.  This is going into the CommonSecurityLog table.

We removed Local7 from our generic Syslog via AMA DCR, and estreamer logs do not come into the Syslog table.  We removed our 'just in case' transform to drop all Syslog with ProcessName == "CEF", and the logs still don't show up in the Syslog table (as expected/desired).

Only long-term planning we need now is avoiding using Facilities designated internally for CEF in other types of Syslog.  Worst case, we would have to separate our collector servers further.

**Comment by yusufozturk** [comment] 2025-02-15 21:52
If there are people who are looking for an easy eStream integration instead of the relic eNcore, then they can check this out:
https://vdocs.virtualmetric.com/administration/devices/estreamer

**Comment by UncleMonty** [comment] 2025-02-19 20:19
Sorry if I'm asking a repeated question: 

What is the correct way forward to get Cisco ASA/FTD to ingest as CEF logs into the CommonSecurityLog table in Sentinel?

What data connectors do I need to have the admin team configure, what DCR, what needs to be configured in the DCR, etc.?

Currently, we are only seeing traffic logs come in via Syslog. (not seeing admin auth logs, admin commands, reboots, etc.)

We have log collectors in between the Cisco devices that run on Linux VMs.
