### ISSUE TITLE
All of these rules fail with the same error when you try to create them

### ISSUE THREAD

**Issue by anfisher1967** [Azure/Azure-Sentinel#6363] opened 2022-10-12 01:08 UTC
Attempting to Create Rule: Dev-0530 IOC - July 2022
Error Creating Rule: Error in EntityMappings: The given column 'FileHashCustomEntity' does not exist.

Attempting to Create Rule: ACTINIUM AV hits - Feb 2022
Error Creating Rule: Error in EntityMappings: The given column 'FileHashType' does not exist.

Attempting to Create Rule: Tarrask malware IOC - April 2022
Error Creating Rule: Error in EntityMappings: The given column 'FileHashCustomEntity' does not exist.

Attempting to Create Rule: KNOTWEED File Hashes July 2022
Error Creating Rule: Error in EntityMappings: The given column 'FileHashCustomEntity' does not exist.

Attempting to Create Rule: Hive Ransomware IOC - July 2022
Error Creating Rule: Error in EntityMappings: The given column 'FileHashCustomEntity' does not exist.
  
Attempting to Create Rule: Zinc Actor IOCs files - October 2022
Error Creating Rule: Error in EntityMappings: The given column 'AlgorithmCustomEntity' does not exist.

**Comment by anfisher1967** [comment] 2022-10-12 01:09
These too
Attempting to Create Rule: ACTINIUM Actor IOCs - Feb 2022
Error Creating Rule: Error in EntityMappings: The given column 'FileHashType' does not exist.

Attempting to Create Rule: Mercury - Domain, Hash and IP IOCs - August 2022
Error Creating Rule: Error in EntityMappings: The given column 'FileHashCustomEntity' does not exist.

Attempting to Create Rule: Europium - Hash and IP IOCs - September 2022
Error Creating Rule: Error in EntityMappings: The given column 'FileHashCustomEntity' does not exist.

**Comment by Phrozyn** [comment] 2022-10-12 17:30
How are you attempting to deploy/create these rules?
Through the UI? API? Or TF provider?

**Comment by anfisher1967** [comment] 2022-10-12 22:51
UI

On Oct 12, 2022, at 1:30 PM, A Smith ***@***.***> wrote:

﻿

How are you attempting to deploy/create these rules?
Through the UI? API? Or TF provider?

**Comment by richlilly2004** [comment] 2022-10-13 17:01
+1 on this as well

**Comment by abaddon82** [comment] 2022-11-03 14:24
Any news on this issue?

**Comment by akmatthewsuk** [comment] 2022-11-07 17:11
This is pure speculation but if you read the YAML for these rules the FileHashCustomEntity is a SHA256 algorithm value

| extend timestamp = TimeGenerated, HostCustomEntity = Hostname , AccountCustomEntity = AccountName,  FileHashCustomEntity = SHA256

The correct entry in the YAML for the entity mapping is probably

  - entityType: FileHash
    fieldMappings:
      - identifier: Algorithm
        columnName: SHA256
      - identifier: Value
        columnName: FileHashCustomEntity

**Comment by v-amolpatil** [comment] 2023-01-31 11:46
Hi @anfisher1967, 
Sorry for the delayed response. 
We are able to create analytic rules for the above mentioned items. Could you please re-verify again if its working at your end or not?
Thanks!

**Comment by anfisher1967** [comment] 2023-01-31 15:15
Same error in two different tenants. Let me know if you want a screen shot.

**Comment by v-rbajaj** [comment] 2023-06-07 12:17
Hi @anfisher1967, We wanted to check on the status of Issue https://github.com/Azure/Azure-Sentinel/issues/6363. The issue is pending for more than expected days. Please let us know if you need any assistance to review this Issue. As per our standard operating procedures if no response is received in the next 7 business days, we will close this Issue. Thank you for your cooperation.

**Comment by v-vdixit** [comment] 2023-06-15 05:16
Since we have not received a response in the last 7 days, we are closing your issue as per our standard operating procedures. If you still need support for this issue, feel free to re-open at any time. Thank you for your co-operation

**Closed by v-vdixit** 2023-06-15 05:16 UTC
Labels: Analytic Rules
