### ISSUE TITLE
Workbook - VMware ESXi "VM status" is not found results

### ISSUE THREAD

**Issue by jeffrywu28** [Azure/Azure-Sentinel#9468] opened 2023-11-24 08:28 UTC
**Describe the bug**

**To Reproduce**
1. Go to 'VMWare ESXi built-in dashboard'
2. Click on 'view the VMStatus'
3. Click edit the Query

VMwareESXi
| where SyslogMessage has ('VmPoweredOffEvent')
| extend DstHostname = extract(@'\[\d+\]\s+\[(.*?)\s+on', 1, SyslogMessage)
| summarize off_t = max(TimeGenerated) by DstHostname
| project DstHostname, Status=strcat(iff(isnotempty(off_t), '❌ - Powered Off', '✅ - Running'))
4. See no result

**Screenshots**
<img width="822" alt="image" src="https://github.com/Azure/Azure-Sentinel/assets/47622164/912355c4-ba19-4759-86a8-64c9b493308b">

**Expected behavior**
The vm status timeline is Running or poweroff data is showing.

**Expected Screenshots filtered**
![WhatsApp Image 2023-11-24 at 13 42 24](https://github.com/Azure/Azure-Sentinel/assets/47622164/c6d7d80b-0779-4821-89c4-b8eaf431ea12)

**Comment by v-muuppugund** [comment] 2023-11-24 12:28
Hi @jeffrywu28 , Thanks for flagging this issue, we will investigate this issue and get back to you with some updates by 29Nov23. Thanks!

**Comment by v-sudkharat** [comment] 2023-11-29 09:54
Hi @jeffrywu28, we are unable to reproduce this issue, could you please share the sample data with us? so, we can check it from our end. Thanks!

**Comment by v-sudkharat** [comment] 2023-12-01 08:56
Hi @jeffrywu28, we are waiting for your response on above comment. thanks!

**Comment by v-sudkharat** [comment] 2023-12-05 08:40
Hi @jeffrywu28, Gentle Reminder: We are waiting for your response on this issue. If you still need to keep this issue active, please respond to it in the next 2 days. If we don't receive a response by 07-12-2023 date, we will be closing this issue. 		
Thanks!

**Comment by jeffrywu28** [comment] 2023-12-05 10:34
sure which platform i can send u the sample?

**Comment by v-sudkharat** [comment] 2023-12-05 11:27
Hi @jeffrywu28, you can provide sample data with us over GitHub itself or sent on this mail id - [v-sudkharat@microsoft.com](mailto:v-sudkharat@microsoft.com)

**Comment by v-sudkharat** [comment] 2023-12-07 07:02
Hi @jeffrywu28, we are waiting for sample data from you. could you please have a look at above comment and sent on that mail id or you can share it over this GitHub chat as well. 

Thanks!

**Comment by v-sudkharat** [comment] 2023-12-11 11:32
Hi @jeffrywu28, Gentle Reminder: We are waiting for your response on this issue. If you still need to keep this issue active, please respond to it in the next 2 days. If we don't receive a response by 13-12-2023 date, we will be closing this issue. 		
Thanks!

**Comment by v-sudkharat** [comment] 2023-12-13 12:43
Hi @jeffrywu28, thanks for sharing the logs with us. we will check on this issue and get back to you by - 20-12-2023. Thanks!

**Comment by v-sudkharat** [comment] 2023-12-18 14:39
Hi @jeffrywu28, we have made few modifications below workbook, could you please custom add it and let us know you are getting expected result. 
Workbook Template Here - [VMWareESXi.json](https://github.com/Azure/Azure-Sentinel/files/13704984/VMWareESXi.json)

1. Go to Standalone Workbook -
 
![image](https://github.com/Azure/Azure-Sentinel/assets/132428394/1ccd84f0-3239-47db-9312-1596580872f8)

3. Click Add workbook - 

![image](https://github.com/Azure/Azure-Sentinel/assets/132428394/b3249d0b-2332-4d58-a0fb-745ac7e54a00)

5.click advance edit - 

![image](https://github.com/Azure/Azure-Sentinel/assets/132428394/c6f9c4c1-0339-4bdb-a25a-04c9566dab26)

6. Past our shared template there and click on apply - 
![image](https://github.com/Azure/Azure-Sentinel/assets/132428394/c2831b7e-4c01-4d98-b6a1-40b889c69deb)



Thanks!

**Comment by v-sudkharat** [comment] 2023-12-20 13:30
Hi @jeffrywu28, hope you are doing well. Could you please check on above comment? and share feedback with us. Thanks!

**Comment by v-sudkharat** [comment] 2023-12-26 12:45
Hi @jeffrywu28, since we have not received a response in the last 5 days, we are closing your issue #9468 as per our standard operating procedures. If you still need support for this issue, feel free to re-open at any time. Thank you for your co-operation.

**Closed by v-sudkharat** 2023-12-26 12:45 UTC
Labels: Workbook
