### ISSUE TITLE
Access metrics for Sentinel(SIEM)

### ISSUE THREAD

**Issue by shipothana** [Azure/Azure-Sentinel#7819] opened 2023-04-14 10:50 UTC
Hi Team,

Can you suggest me custom role access Sentinel from best practice SOC team.

Thanks,
Siva Pothana

**Comment by v-vdixit** [comment] 2023-04-17 09:34
Hi @shipothana Could you please provide some additional details or clarify the question further? This would help me better understand the issue and provide a more comprehensive answer.

**Comment by shipothana** [comment] 2023-04-17 09:53
Custom role information different device roles(Windows,Linux,Appcaction,etc), an incident response protocol, a specific security profile, Please provide me additional information about creating unique roles.

**Comment by v-vdixit** [comment] 2023-04-17 10:44
Hi @shipothana, here are some best practices for creating custom roles in Azure Sentinel:

1) Identify the responsibilities and access requirements of each role: Start by identifying the roles and responsibilities within your organization and what level of access each role requires. You should consider the type of data the role needs to access, the level of permission needed, and the scope of the access.
2) Follow the principle of least privilege: Only grant the minimum permissions necessary to complete the task. This principle helps reduce the risk of accidental or malicious activity and helps prevent access to sensitive data.
3) Use role-based access control (RBAC): RBAC allows you to assign permissions to users, groups, or applications based on their role in the organization. This approach makes it easier to manage access and control who can do what within Azure Sentinel.
4) Create custom roles: Create custom roles based on the identified responsibilities and access requirements of each role. You can use built-in roles as a starting point, but be sure to tailor them to fit your organization's needs.
5) Test and refine: Test the roles to ensure they work as intended and refine them based on feedback from the users. It's important to regularly review and update roles as needed to ensure they remain effective and relevant.
6) Consider using Azure Policy: Azure Policy can help enforce organizational compliance and governance by defining rules for resources and services in Azure Sentinel. You can use policy to enforce specific security controls or configurations and ensure that users are following best practices.
7) Document roles and permissions: Document the roles and permissions granted to each user or group. This documentation can be used to audit access and demonstrate compliance with regulatory requirements.

Based on my understanding of your query, I am sending this response to provide the information you requested. If you were looking for something else, please do let me know, and I'll be happy to assist you further.

**Comment by v-vdixit** [comment] 2023-04-24 04:52
Hi @shipothana Gentle Reminder: We are waiting for your response on this issue. If you still need to keep this issue active, please respond on it in the next 2 days. If we don't receive response by given date we will close this issue as per our standard procedure, thanks!

**Comment by v-vdixit** [comment] 2023-04-26 10:21
Hi @shipothana, since we have not received a response in the last 5 days, we are closing your issue #7819, as per our standard operating procedures. If you still need support for this issue, feel free to re-open at any time. Thank you for your co-operation.

**Closed by v-vdixit** 2023-04-26 10:21 UTC
Labels: question
