### ISSUE TITLE
Module 2 - Data Connectors option is not available

### ISSUE THREAD

**Issue by aalborz** [Azure/Azure-Sentinel#4414] opened 2022-03-15 13:46 UTC
In the very step of Module 2, in the workspace, there is no "Data Connectors" under Configuration section to enable. In fact, there's no Configuration section or other sections such as Threat Management, etc. When I type in "Data Connectors" in the top bar, nothing is displayed either.
How do I select Data Connectors for this workspace then?

**Comment by samikroy** [comment] 2022-03-15 13:54
@aalborz - Could you please share a screenshot of the mentioned details !

**Comment by v-rucdu** [comment] 2023-01-11 10:05
@aalborz : Request you to please attach the screenshot of the issue and also would like to know the steps that you followed to reproduce it... Thanks!!

**Comment by v-amolpatil** [comment] 2023-01-31 14:02
Since we have not received a response in the last 5 days, we are closing your issue #4414 as per our standard operating procedures. If you still need support for this issue, feel free to re-open at any time. Thank you for your co-operation.

**Closed by v-amolpatil** 2023-01-31 14:02 UTC
Labels: Connector
