### ISSUE TITLE
Can't install Deception Technology Solution

### ISSUE THREAD

**Issue by jean0828** [Azure/Azure-Sentinel#8924] opened 2023-08-31 21:14 UTC
**Describe the bug**
I can't install Deception technology solution because it dropdown menu for selecting workspaces when creating.

**To Reproduce**
1. Go to 'Sentinel' --> Content hub --> create --> I select the resource group where it's sentinel but in the workspace dropdown menu, there is nothing. therefore, I can't install the solution

**Expected behavior**
I should be able to see Log analytics workspace of Sentinel

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: Laptop
 - OS: Windows 10
 - Browser chrome 116.0.5845.112 and Edge 116.0.1938.62

**Additional context**
I have the Azure AD role called security administrator and I have installed other solution without problems. My problem is specific with icrosoft Sentinel Deception (Honey Tokens) Solution.

**Comment by v-sudkharat** [comment] 2023-09-01 04:37
Hi @jean0828, thanks for flagging this issue, we will soon get back to you on this. Thanks!

**Comment by jean0828** [comment] 2023-09-18 15:58
Hi, any update on this? I still have the issue and I can't deploy the solution

**Comment by v-muuppugund** [comment] 2023-09-29 05:29
Hi @jean0828 , Apologies for the delayed response,Could you please share screen shot of the error details,so we can look in to the issue,Thanks

**Comment by v-muuppugund** [comment] 2023-10-09 08:43
Hi @jean0828 ,Could you please share screen shot of the error details,so we can look in to the issue

**Comment by jean0828** [comment] 2023-10-09 15:12
Yes, here you can see the screenshots https://imgur.com/a/wJOJXkl

**Comment by v-muuppugund** [comment] 2023-10-12 03:01
Hi @jean0828, could you please check log analytics workspace intended to add in honey tokens is there any log analytics workspace present or not, if not add please create a log analytics workspace and use it by adding to sentinel workspace, please let us know if any information needed.

Please refer below screen shot for reference issue replicated.
![image](https://github.com/Azure/Azure-Sentinel/assets/139563098/09f251af-6527-42ac-81d7-8cea24eae054)

Step1: 
Create a Log analytics workspace in that resource group
![image](https://github.com/Azure/Azure-Sentinel/assets/139563098/a2d3b20f-a75a-4771-8e67-f1091a0a3047)

Step 2:
Add that log analytics workspace to sentinel workspace and use it. 
![image](https://github.com/Azure/Azure-Sentinel/assets/139563098/31913434-701f-475c-bff4-0c89c4df784f)

**Comment by jean0828** [comment] 2023-10-13 20:38
Hello,

Yes, I have the Log analytics workspace. I want to select the log analytics workspace of Sentinel but it didn't show

![law](https://i.imgur.com/09cPCm7.png)

in the image, you can see the log analytic workspace is in the resource group called inov-sentinel. however, when I try to deploy the solution in the same resource group, there is no option to select

![solution](https://i.imgur.com/DoLTxRt.png)

what else can I do? 

thanks.

**Comment by jean0828** [comment] 2023-10-18 01:44
can you give me the email to suggest you few schedule times? thanks

**Comment by v-muuppugund** [comment] 2023-10-18 04:41
@jean0828  Please find my email details v-muuppugund@microsoft.com and let me know convenient for detailed troubleshooting on this issue.

**Comment by v-muuppugund** [comment] 2023-10-25 19:06
@jean0828 ,As discussed over call, unblocked the issue with different RG and workspace approach, meanwhile during the call replicated the same issue in one of my rg for the existing workspace issue based on issue details, will investigate and get back to you for another scenario.

![image](https://github.com/Azure/Azure-Sentinel/assets/139563098/13ed2031-63c1-4e55-9581-2c58fd4657df)

**Comment by v-muuppugund** [comment] 2023-10-30 17:31
@jean0828  after replicating the issue,I did analysis and found the issue is due to some characters in the RG Name,Please find below screen shots for reference
![image](https://github.com/Azure/Azure-Sentinel/assets/139563098/bfd47534-a100-46d6-b2e1-edb89ac70d12)

![image](https://github.com/Azure/Azure-Sentinel/assets/139563098/8e2cb437-bfab-41ab-b32f-ff384d565c1c)

Please try creating RG inovsentinel with out special characters and create a log analytic work space and add it to sentinel ,use it, Please let me know if you have any issues

**Comment by v-muuppugund** [comment] 2023-11-03 04:32
Hi @jean0828 , Since we have not received a response in the last 5 days, we are closing your issue https://github.com/Azure/Azure-Sentinel/issues/8924 as per our standard operating procedures. If you still need support for this issue, feel free to re-open at any time. Thank you for your co-operation.

**Closed by v-muuppugund** 2023-11-03 04:32 UTC
Labels: Solution

**Comment by jean0828** [comment] 2023-11-15 13:59
Hi, sorry for my late answer. it worked. However, is there any way to report this bug? because the idea is to have everything in the same workspace and in the documentation doesn't say anything about the workspace name.

thanks.
