### ISSUE TITLE
Workbook - VMware ESXi "Root Sessions" is not found results

### ISSUE THREAD

**Issue by jeffrywu28** [Azure/Azure-Sentinel#9469] opened 2023-11-24 08:36 UTC
**Describe the bug**
Please fix your built-in dashboard about Vmware ESXi, the 1 of the panel that titled Root Sessions never showing any result.

**To Reproduce**

    Go to 'VMWare ESXi built-in dashboard'
    Click on 'view the VMStatus'
    Click edit the Query

currently built-in query:
    VMwareESXi
    | where SyslogMessage has_all ('UserLoginSessionEvent', 'denis', 'logged in')
    //| extend SrcUsername = extract(@'User\s(.*?)@\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}', 1, SyslogMessage)
    | extend SrcIpAddr = extract(@'@(\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3})', 1, SyslogMessage)
    | order by TimeGenerated
    | project EventTime = TimeGenerated, SourceAddress = SrcIpAddr

it must be : 

VMwareESXi
| where SyslogMessage has_all ('root', 'logged in')
//| extend SrcUsername = extract(@'User\s(.*?)@\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}', 1, SyslogMessage)
| extend SrcIpAddr = extract(@'@(\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3})', 1, SyslogMessage)
| order by TimeGenerated
| project EventTime = TimeGenerated, SourceAddress = SrcIpAddr

**Expected behavior**
there is value at there and it must showing the result.

**Screenshots**
<img width="922" alt="image" src="https://github.com/Azure/Azure-Sentinel/assets/47622164/57b04ba8-4d9c-4ed6-899b-e6ac50fb8c3c">

**Expected Screenshots**
<img width="884" alt="image" src="https://github.com/Azure/Azure-Sentinel/assets/47622164/89f1285e-232b-4767-8d4d-dc2c608853c7">

**Comment by v-sudkharat** [comment] 2023-11-24 11:03
Hi @jeffrywu28, Thanks for flagging this issue, we will investigate this issue and get back to you with some updates by 29-11-2023. Thanks!

**Comment by v-sudkharat** [comment] 2023-11-29 09:53
Hi @jeffrywu28, we are unable to reproduce this issue, could you please share the sample data with us? so, we can check it from our end. Thanks!

**Comment by v-sudkharat** [comment] 2023-12-05 08:42
Hi @jeffrywu28, Gentle Reminder: We are waiting for your response on this issue. If you still need to keep this issue active, please respond to it in the next 2 days. If we don't receive a response by 07-12-2023 date, we will be closing this issue. 		
Thanks!

**Comment by jeffrywu28** [comment] 2023-12-05 10:32
@v-sudkharat sure, what platform or email you can provide to me?

**Comment by v-sudkharat** [comment] 2023-12-05 11:25
Hi @jeffrywu28m, you can provide sample data with us over github itself or sent on this mail id - v-sudkharat@microsoft.com

**Comment by v-sudkharat** [comment] 2023-12-07 07:03
Hi @jeffrywu28, we are waiting for sample data from you. could you please have a look at above comment and sent on that mail id or you can share it over this GitHub chat as well.

Thanks!

**Comment by v-sudkharat** [comment] 2023-12-11 11:33
Hi @jeffrywu28, Gentle Reminder: We are waiting for your response on this issue. If you still need to keep this issue active, please respond to it in the next 2 days. If we don't receive a response by 13-12-2023 date, we will be closing this issue. 		
Thanks!

**Comment by v-sudkharat** [comment] 2023-12-13 12:43
Hi @jeffrywu28, thanks for sharing the logs with us. we will check on this issue and get back to you by - 20-12-2023. Thanks!

**Comment by v-sudkharat** [comment] 2023-12-18 14:41
Hi @jeffrywu28, we are working on ingesting the data shared by you, meanwhile could you please check on our shared comment- 
https://github.com/Azure/Azure-Sentinel/issues/9468
Thanks!

**Comment by v-sudkharat** [comment] 2023-12-26 09:39
Hi @jeffrywu28, could you please custom add workbook and let us know you are getting expected result.
Workbook Template Here - [VMWareESXi.json](https://github.com/Azure/Azure-Sentinel/files/13704984/VMWareESXi.json)

1. Go to Standalone Workbook -
 
![image](https://github.com/Azure/Azure-Sentinel/assets/132428394/1ccd84f0-3239-47db-9312-1596580872f8)

3. Click Add workbook - 

![image](https://github.com/Azure/Azure-Sentinel/assets/132428394/b3249d0b-2332-4d58-a0fb-745ac7e54a00)

5.click advance edit - 

![image](https://github.com/Azure/Azure-Sentinel/assets/132428394/c6f9c4c1-0339-4bdb-a25a-04c9566dab26)

6. Past our shared template there and click on apply - 
![image](https://github.com/Azure/Azure-Sentinel/assets/132428394/c2831b7e-4c01-4d98-b6a1-40b889c69deb)



Thanks!

**Comment by v-sudkharat** [comment] 2023-12-28 08:44
Hi @jeffrywu28, I hope you are doing well. Thanks for sharing data with us. We are getting issue while ingest the data into LAW due to large volume, so it would be great if you check our recent comment and let us know your get the expected result. So we can procced on that. 

Thanks!

**Comment by v-sudkharat** [comment] 2024-01-03 10:43
Hi @jeffrywu28, Gentle Reminder: We are waiting for your response on this issue. If you still need to keep this issue active, please respond to it in the next 2 days. If we don't receive a response by 05-01-2024 date, we will be closing this issue. 		
Thanks!

**Comment by v-sudkharat** [comment] 2024-01-05 08:48
Hi @jeffrywu28, since we have not received a response in the last 5 days, we are closing your issue #9469 as per our standard operating procedures. If you still need support for this issue, feel free to re-open at any time. Thank you for your co-operation.

**Closed by v-sudkharat** 2024-01-05 08:48 UTC
Labels: Workbook, Solution
