### ISSUE TITLE
ConfigAwsConnector.ps1 throws errors and then quits after 3 retries. See #8293

### ISSUE THREAD

**Issue by bobsyourmom** [Azure/Azure-Sentinel#9120] opened 2023-09-28 19:11 UTC
Describe the bug
***********
Note: this was never fixed in #8293 so I'm opening a new ticket.
Although I didn't see you asked for logs, another person provided logs and he was ignored.
Reproducing this error should be easy, the scripts are entirely broken.
I've provided my log output in the comment below.
***********

Location of script(s):
https://github.com/Azure/Azure-Sentinel/tree/master/DataConnectors/AWS-S3
When running this script from powershell (on Windows 11, fully patched), the following errors are consistently seen, before the script quits:
.\ConfigAwsConnector.ps1
Starting ConfigAwsConnector at: 06/16/2023 21:13:33
Log created: C:\users\bob\aws\Logs\AwsS3-06162113.csv

To begin you will choose the AWS logs to configure.

Please enter the AWS log type to configure (VPC, CloudTrail, GuardDuty, CustomLog): CloudTrail

Checking AWS CLI configuration...

This script creates an Assume Role with minimal permissions to grant Azure Sentinel access to your logs in a designated S3 bucket & SQS of your choice, enable CloudTrail Logs, S3 bucket, SQS Queue, and S3 notifications.

Notes:

You can find more information about the script in https://github.com/Azure/Azure-Sentinel/blob/master/DataConnectors/AWS-S3/README.md
If a resource name(like: S3, Sqs, Kms) already exists, the script will use the available one and not create a new resource
Assume role definition

Please enter role name. If you have already configured an assume role for Azure Sentinel, use the same role name: Sentinel
Using role name: Sentinel
ConvertFrom-Json : Invalid JSON primitive: ROLE.
At C:\users\bob\aws\ConfigCloudTrailDataConnector.ps1:244 char:30

$roleArn = ($roleArnObject | ConvertFrom-Json ).Role.Arn
                         ~~~~~~~~~~~~~~~~
CategoryInfo : NotSpecified: (:) [ConvertFrom-Json], ArgumentException
FullyQualifiedErrorId : System.ArgumentException,Microsoft.PowerShell.Commands.ConvertFromJsonCommand
Write-Log : Cannot bind argument to parameter 'Message' because it is null.
At C:\users\bob\aws\ConfigCloudTrailDataConnector.ps1:245 char:20

Write-Log -Message $roleArn -LogFileName $LogFileName -Severity Verbo ...
               ~~~~~~~~
CategoryInfo : InvalidData: (:) [Write-Log], ParameterBindingValidationException
FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Write-Log
To Reproduce
Steps to reproduce the behavior:
Follow the instructions as presented here:
https://github.com/Azure/Azure-Sentinel/tree/master/DataConnectors/AWS-S3

See error as shown above.

Expected behavior
no errors should be shown during the execution of the powershell script.

Screenshots
n/a

Desktop (please complete the following information):

OS: windows 11, fully patched.
Latest version of powershell and the AWS cli.

**Comment by bobsyourmom** [comment] 2023-09-28 19:16
Time,Message,Severity
9/28/2023 1:22 PM,Starting ConfigAwsConnector at: 09/28/2023 13:22:55,Information
9/28/2023 1:22 PM,Log created: C:\Users\bob\Downloads\AWS\Logs\AwsS3-09281322.csv,Information
9/28/2023 1:22 PM,To begin you will choose the AWS logs to configure.,Information
9/28/2023 1:23 PM,Checking AWS CLI configuration...,Information
9/28/2023 1:23 PM,Starting CloudTrail data connector configuration script,Verbose
9/28/2023 1:23 PM,"This script creates an Assume Role with minimal permissions to grant Azure Sentinel access to your logs in a designated S3 bucket & SQS of your choice, enable CloudTrail Logs, S3 bucket, SQS Queue, and S3 notifications.",Information
9/28/2023 1:23 PM,Notes:,Information
9/28/2023 1:23 PM,* You can find more information about the script in https://github.com/Azure/Azure-Sentinel/blob/master/DataConnectors/AWS-S3/README.md,Information
9/28/2023 1:23 PM,"* If a resource name(like: S3, Sqs, Kms) already exists, the script will use the available one and not create a new resource",Information
9/28/2023 1:23 PM,Assume role definition,Information
9/28/2023 1:23 PM,Executing Set-RetryAction,Verbose
9/28/2023 1:23 PM,Using role name: TestSentinel1,Information
9/28/2023 1:23 PM,Executing: aws iam get-role --role-name TestSentinel1 2>&1| Out-Null,Verbose
9/28/2023 1:23 PM,You must specify the the Azure Sentinel Workspace ID. This is found in the Azure Sentinel portal.,Information
9/28/2023 1:23 PM,Using Azure Sentinel Workspace ID: 3f12847d-f69c-4c91-a4b0-be670c650299,Information
9/28/2023 1:23 PM,"Executing: aws iam create-role --role-name TestSentinel1 --assume-role-policy-document {
            \""Version\"": \""2012-10-17\"",
            \""Statement\"": [
                {
                    \""Effect\"": \""Allow\"",
                    \""Principal\"": {
                        \""AWS\"": \""arn:aws:iam::197857026523:root\""
                    },
                    \""Action\"": \""sts:AssumeRole\"",
                    \""Condition\"": {
                        \""StringEquals\"": {
                            \""sts:ExternalId\"": \""3f12847d-f69c-4c91-a4b0-be670c650299\""
                        }
                    }
                }
            ]
        } --tags {\""Key\"": \""Operator\"", \""Value\"": \""Microsoft_Sentinel_Automation_Script\""} 2>&1",Verbose
9/28/2023 1:23 PM,"ROLE	arn:aws:iam::048346105924:role/TestSentinel1	2023-09-28T18:23:58+00:00	/	AROAQWQNHBBCN6WWALULD	TestSentinel1 ASSUMEROLEPOLICYDOCUMENT	2012-10-17 STATEMENT	sts:AssumeRole	Allow STRINGEQUALS	3f12847d-f69c-4c91-a4b0-be670c650299 PRINCIPAL	arn:aws:iam::197857026523:root TAGS	Operator	Microsoft_Sentinel_Automation_Script",Verbose
9/28/2023 1:23 PM,TestSentinel1 role created successfully,Information
9/28/2023 1:23 PM,Executing: aws iam get-role --role-name TestSentinel1,Verbose
9/28/2023 1:24 PM,Using S3 Bucket name: TestS3Bucket1,Information
9/28/2023 1:24 PM,current region configuration: us-east-1,Verbose
9/28/2023 1:24 PM,Executing: aws s3api head-bucket --bucket TestS3Bucket1 2>&1,Verbose
9/28/2023 1:24 PM,Creating new bucket: y ,Information
9/28/2023 1:24 PM,Executing: aws s3api create-bucket --bucket TestS3Bucket1 2>&1,Verbose
9/28/2023 1:24 PM,System.Management.Automation.RemoteException An error occurred (BucketAlreadyExists) when calling the CreateBucket operation: The requested bucket name is not available. The bucket namespace is shared by all users of the system. Please select a different name and try again.,Verbose
9/28/2023 1:24 PM,An error occurred (BucketAlreadyExists) when calling the CreateBucket operation: The requested bucket name is not available. The bucket namespace is shared by all users of the system. Please select a different name and try again.,Error
9/28/2023 1:24 PM,Retrying...,Information
9/28/2023 1:25 PM,Using S3 Bucket name: BrogBucket1,Information
9/28/2023 1:25 PM,current region configuration: us-east-1,Verbose
9/28/2023 1:25 PM,Executing: aws s3api head-bucket --bucket BrogBucket1 2>&1,Verbose
9/28/2023 1:25 PM,Creating new bucket: y ,Information
9/28/2023 1:25 PM,Executing: aws s3api create-bucket --bucket BrogBucket1 2>&1,Verbose
9/28/2023 1:25 PM,System.Management.Automation.RemoteException An error occurred (InvalidBucketName) when calling the CreateBucket operation: The specified bucket is not valid.,Verbose
9/28/2023 1:25 PM,Please see AWS bucket name documentation https://docs.aws.amazon.com/awscloudtrail/latest/userguide/cloudtrail-s3-bucket-naming-requirements.html,Error
9/28/2023 1:25 PM,An error occurred (InvalidBucketName) when calling the CreateBucket operation: The specified bucket is not valid.,Error
9/28/2023 1:25 PM,Retrying...,Information
9/28/2023 1:26 PM,Using S3 Bucket name: testbrogbucket1,Information
9/28/2023 1:26 PM,current region configuration: us-east-1,Verbose
9/28/2023 1:26 PM,Executing: aws s3api head-bucket --bucket testbrogbucket1 2>&1,Verbose
9/28/2023 1:26 PM,Executing: (aws sts get-caller-identity | ConvertFrom-Json).Account,Verbose
9/28/2023 1:26 PM,Executing: (aws sts get-caller-identity | ConvertFrom-Json).Account,Verbose
9/28/2023 1:26 PM,,Verbose
9/28/2023 1:26 PM,Creating SQS queue:,Information
9/28/2023 1:27 PM,Using Sqs name: testsqs1,Information
9/28/2023 1:27 PM,"Executing: aws sqs create-queue --queue-name testsqs1 --tags {\""Operator\"": \""Microsoft_Sentinel_Automation_Script\""} 2>&1",Verbose
9/28/2023 1:27 PM,https://sqs.us-east-1.amazonaws.com/048346105924/testsqs1,Verbose
9/28/2023 1:27 PM,Executing: ((aws sqs get-queue-url --queue-name testsqs1) | ConvertFrom-Json).QueueUrl,Verbose
9/28/2023 1:27 PM,Executing: (aws sts get-caller-identity | ConvertFrom-Json).Account,Verbose
9/28/2023 1:27 PM,Kms definition.,Information
9/28/2023 1:27 PM,Using Kms alias name: testkms1,Information
9/28/2023 1:27 PM,Executing: aws kms describe-key --key-id alias/testkms1 2>&1,Verbose
9/28/2023 1:27 PM,System.Management.Automation.RemoteException An error occurred (NotFoundException) when calling the DescribeKey operation: Alias arn:aws:kms:us-east-1:048346105924:alias/testkms1 is not found.,Verbose
9/28/2023 1:27 PM,"Executing: aws kms create-key --tags {\""TagKey\"": \""Operator\"", \""TagValue\"": \""Microsoft_Sentinel_Automation_Script\""}",Verbose
9/28/2023 1:27 PM,"KEYMETADATA	048346105924	arn:aws:kms:us-east-1:048346105924:key/0c160e0c-8b9d-4a96-94a7-4da768d63a00	2023-09-28T13:27:47.126000-05:00	SYMMETRIC_DEFAULT		True	0c160e0c-8b9d-4a96-94a7-4da768d63a00	CUSTOMER	SYMMETRIC_DEFAULT	Enabled	ENCRYPT_DECRYPT	False	AWS_KMS ENCRYPTIONALGORITHMS	SYMMETRIC_DEFAULT",Verbose
9/28/2023 1:27 PM,Executing: ws kms create-alias --alias-name alias/testkms1 --target-key-id  2>&1,Verbose
9/28/2023 1:27 PM,"System.Management.Automation.RemoteException usage: aws [options] <command> <subcommand> [<subcommand> ...] [parameters] To see help text, you can run: System.Management.Automation.RemoteException   aws help   aws <command> help   aws <command> <subcommand> help System.Management.Automation.RemoteException aws.exe: error: argument --target-key-id: expected one argument System.Management.Automation.RemoteException",Verbose
9/28/2023 1:27 PM,System.Management.Automation.RemoteException,Error
9/28/2023 1:27 PM,Retrying...,Information
9/28/2023 1:29 PM,Using Kms alias name: testkms1,Information
9/28/2023 1:29 PM,Executing: aws kms describe-key --key-id alias/testkms1 2>&1,Verbose
9/28/2023 1:29 PM,"KEYMETADATA	048346105924	arn:aws:kms:us-east-1:048346105924:key/8f021486-e94b-4014-bcac-1418d27f0c10	2023-09-28T13:29:17.951000-05:00	SYMMETRIC_DEFAULT		True	8f021486-e94b-4014-bcac-1418d27f0c10	CUSTOMER	SYMMETRIC_DEFAULT	Enabled	ENCRYPT_DECRYPT	False	AWS_KMS ENCRYPTIONALGORITHMS	SYMMETRIC_DEFAULT",Verbose
9/28/2023 1:29 PM,Updating KMS policy to allow Sentinel read the data.,Information
9/28/2023 1:29 PM,"Changes Role: Kms Encrypt, Decrypt, ReEncrypt*, GenerateDataKey* and DescribeKey  permissions to 'TestSentinel1' rule",Information
9/28/2023 1:29 PM,Changes CloudTrail: Kms GenerateDataKey to CloudTrail,Information
9/28/2023 1:29 PM,Executing: aws kms get-key-policy --policy-name default --key-id ,Verbose
9/28/2023 1:29 PM,"Executing: aws kms put-key-policy --policy-name default --key-id  --policy {
    \""Statement\"":  [
                      {
                          \""Sid\"":  \""Allow CloudTrail to encrypt logs\"",
                          \""Effect\"":  \""Allow\"",
                          \""Principal\"":  {
                                            \""Service\"":  \""cloudtrail.amazonaws.com\""
                                        },
                          \""Action\"":  \""kms:GenerateDataKey*\"",
                          \""Resource\"":  \""*\""
                      },
                      {
                          \""Sid\"":  \""Allow use of the key\"",
                          \""Effect\"":  \""Allow\"",
                          \""Principal\"":  {
                                            \""AWS\"":  [
                                                        \""\""
                                                    ]
                                        },
                          \""Action\"":  [
                                         \""kms:Decrypt\""
                                     ],
                          \""Resource\"":  \""*\""
                      }
                  ]
} | Out-Null",Verbose
9/28/2023 1:29 PM,"Updating the SQS policy to allow S3 notifications, and ARN to read/delete/change visibility of SQS messages and get queue url",Information
9/28/2023 1:29 PM,Changes S3: SQS SendMessage permission to 'testbrogbucket1' s3 bucket,Information
9/28/2023 1:29 PM,"Changes Role ARN: SQS ChangeMessageVisibility, DeleteMessage, ReceiveMessage and GetQueueUrl permissions to 'TestSentinel1' rule",Information
9/28/2023 1:29 PM,Executing: aws sqs get-queue-attributes --queue-url  --attribute-names Policy,Verbose
9/28/2023 1:29 PM,No results returned from: aws sqs get-queue-attributes --queue-url  --attribute-names Policy ,Verbose
9/28/2023 1:29 PM,Executing: ((aws organizations describe-account --account-id  ) | ConvertFrom-Json -ErrorAction SilentlyContinue).Account.Arn.Split('/')[1],Verbose
9/28/2023 1:29 PM,Unable to access AWS organization information. This could be a permissions or policy issue.,Information
9/28/2023 1:29 PM,Updating the S3 policy to allow Sentinel to read the data.,Information
9/28/2023 1:29 PM,Changes: S3 Get and List permissions to 'TestSentinel1' rule,Information
9/28/2023 1:29 PM,Executing: aws s3api get-bucket-policy --bucket testbrogbucket1 2>&1,Verbose
9/28/2023 1:29 PM,"Executing: aws s3api put-bucket-policy --bucket testbrogbucket1 --policy {
    \""Statement\"":  [
                      {
                          \""Sid\"":  \""Allow Arn read access S3 bucket\"",
                          \""Effect\"":  \""Allow\"",
                          \""Principal\"":  {
                                            \""AWS\"":  \""\""
                                        },
                          \""Action\"":  [
                                         \""s3:GetObject\""
                                     ],
                          \""Resource\"":  \""arn:aws:s3:::testbrogbucket1/*\""
                      },
                      {
                          \""Sid\"":  \""AWSCloudTrailAclCheck20150319\"",
                          \""Effect\"":  \""Allow\"",
                          \""Principal\"":  {
                                            \""Service\"":  \""cloudtrail.amazonaws.com\""
                                        },
                          \""Action\"":  \""s3:GetBucketAcl\"",
                          \""Resource\"":  \""arn:aws:s3:::testbrogbucket1\""
                      },
                      {
                          \""Sid\"":  \""AWSCloudTrailWrite20150319\"",
                          \""Effect\"":  \""Allow\"",
                          \""Principal\"":  {
                                            \""Service\"":  \""cloudtrail.amazonaws.com\""
                                        },
                          \""Action\"":  \""s3:PutObject\"",
                          \""Resource\"":  \""arn:aws:s3:::testbrogbucket1/AWSLogs//*\"",
                          \""Condition\"":  {
                                            \""StringEquals\"":  {
                                                                 \""s3:x-amz-acl\"":  \""bucket-owner-full-control\""
                                                             }
                                        }
                      },
                      {
                          \""Sid\"":  \""Deny unencrypted object uploads. This is optional\"",
                          \""Effect\"":  \""Deny\"",
                          \""Principal\"":  {
                                            \""Service\"":  \""cloudtrail.amazonaws.com\""
                                        },
                          \""Action\"":  \""s3:PutObject\"",
                          \""Resource\"":  \""arn:aws:s3:::testbrogbucket1/*\"",
                          \""Condition\"":  {
                                            \""StringNotEquals\"":  {
                                                                    \""s3:x-amz-server-side-encryption\"":  \""aws:kms\""
                                                                }
                                        }
                      },
                      {
                          \""Sid\"":  \""Deny incorrect encryption header. This is optional\"",
                          \""Effect\"":  \""Deny\"",
                          \""Principal\"":  {
                                            \""Service\"":  \""cloudtrail.amazonaws.com\""
                                        },
                          \""Action\"":  \""s3:PutObject\"",
                          \""Resource\"":  \""arn:aws:s3:::testbrogbucket1/*\"",
                          \""Condition\"":  {
                                            \""StringNotEquals\"":  {
                                                                    \""s3:x-amz-server-side-encryption-aws-kms-key-id\"":  \""\""
                                                                }
                                        }
                      }
                  ]
} | Out-Null",Verbose
9/28/2023 1:29 PM,Enabling S3 event notifications (for *.gz file),Information
9/28/2023 1:29 PM,Using event notification name: sentinel,Information
9/28/2023 1:29 PM,"Event notificaion prefix definition, to Limit the notifications to objects with key starting with specified characters.",Information
9/28/2023 1:30 PM,Executing: aws s3api get-bucket-notification-configuration --bucket testbrogbucket1,Verbose
9/28/2023 1:30 PM,Executing: aws s3api put-bucket-notification-configuration --bucket testbrogbucket1 --notification-configuration  2>&1,Verbose
9/28/2023 1:30 PM,"System.Management.Automation.RemoteException usage: aws [options] <command> <subcommand> [<subcommand> ...] [parameters] To see help text, you can run: System.Management.Automation.RemoteException   aws help   aws <command> help   aws <command> <subcommand> help System.Management.Automation.RemoteException aws.exe: error: argument --notification-configuration: expected one argument System.Management.Automation.RemoteException",Verbose
9/28/2023 1:30 PM,System.Management.Automation.RemoteException,Error
9/28/2023 1:30 PM,Retrying...,Information
9/28/2023 1:30 PM,Using event notification name: sentinel,Information
9/28/2023 1:30 PM,"Event notificaion prefix definition, to Limit the notifications to objects with key starting with specified characters.",Information
9/28/2023 1:30 PM,Using event notification prefix: sentinel,Information
9/28/2023 1:30 PM,Executing: aws s3api get-bucket-notification-configuration --bucket testbrogbucket1,Verbose
9/28/2023 1:30 PM,Executing: aws s3api put-bucket-notification-configuration --bucket testbrogbucket1 --notification-configuration  2>&1,Verbose
9/28/2023 1:30 PM,"System.Management.Automation.RemoteException usage: aws [options] <command> <subcommand> [<subcommand> ...] [parameters] To see help text, you can run: System.Management.Automation.RemoteException   aws help   aws <command> help   aws <command> <subcommand> help System.Management.Automation.RemoteException aws.exe: error: argument --notification-configuration: expected one argument System.Management.Automation.RemoteException",Verbose
9/28/2023 1:30 PM,System.Management.Automation.RemoteException,Error
9/28/2023 1:30 PM,Retrying...,Information
9/28/2023 1:30 PM,Using event notification name: sentinel,Information
9/28/2023 1:30 PM,"Event notificaion prefix definition, to Limit the notifications to objects with key starting with specified characters.",Information
9/28/2023 1:30 PM,Executing: aws s3api get-bucket-notification-configuration --bucket testbrogbucket1,Verbose
9/28/2023 1:30 PM,Executing: aws s3api put-bucket-notification-configuration --bucket testbrogbucket1 --notification-configuration  2>&1,Verbose
9/28/2023 1:30 PM,"System.Management.Automation.RemoteException usage: aws [options] <command> <subcommand> [<subcommand> ...] [parameters] To see help text, you can run: System.Management.Automation.RemoteException   aws help   aws <command> help   aws <command> <subcommand> help System.Management.Automation.RemoteException aws.exe: error: argument --notification-configuration: expected one argument System.Management.Automation.RemoteException",Verbose
9/28/2023 1:30 PM,System.Management.Automation.RemoteException,Error
9/28/2023 1:30 PM,Action was unsuccessful after 3 attempts. Please review the errors and try again.,Error

**Comment by v-rbajaj** [comment] 2023-10-10 17:28
Hi @bobsyourmom, we have reached out to concerned team, we will let you know by 17 Oct 2023.

**Comment by v-rbajaj** [comment] 2023-10-27 05:07
Hi @bobsyourmom, sorry for delay in response, We've checked the scripts, run it on our dev machine on different configuration and it worked fine.
We can't reproduce the script error. Can you please download the latest zip file and run the script again. if the problem still remain we will need to set up a meeting with the customer to debug it on his machine.

**Comment by v-rbajaj** [comment] 2023-10-31 10:06
Hi @bobsyourmom, Gentle Reminder: We are awaiting for your response on this issue. If you still need to keep this issue active please respond on it in the next 2 days .. If we don't receive response by given date we will be close this issue.

**Comment by v-rbajaj** [comment] 2023-11-02 08:54
Hi @bobsyourmom, Since we have not received a response in the last 5 days, we are closing your issue #9120 as per our standard operating procedures. If you still need support for this issue, feel free to re-open at any time. Thank you for your co-operation.

**Closed by v-rbajaj** 2023-11-02 08:54 UTC
Labels: Connector
