### ISSUE TITLE
Azure DDOS Workbook Error

### ISSUE THREAD

**Issue by SimoneFrigerio** [Azure/Azure-Sentinel#2615] opened 2021-07-01 17:32 UTC
**Describe the bug**
the AzureDiagnostic schema table is change and the workbook need a refresh
https://github.com/Azure/Azure-Sentinel/blob/master/Workbooks/AzDDoSStandardWorkbook.json

**To Reproduce**
many query are in error
this is an piece example of the query

|Extend TopAttackVector = tostring(parse_json(AttackVectors_s)[0])

how to fix it adding the new schema field "AdditionalField"
|Extend TopAttackVector = tostring(parse_json(AdditionalFields.AttackVectors_s)[0])

**Expected behavior**

**Screenshots**
![Error_DDOS](https://user-images.githubusercontent.com/82639336/124166324-fb439700-daa2-11eb-9a0a-2cb91b6ef7bf.PNG)
![Error_DDOS2](https://user-images.githubusercontent.com/82639336/124166383-0eeefd80-daa3-11eb-9b3c-259e6bbe7e03.PNG)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by v-rucdu** [comment] 2021-07-19 11:56
@SimoneFrigerio, Please refer updated the [workbook](https://github.com/Azure/Azure-Sentinel/blob/v-rucdu/AzureDDoSWorbookIssueFix/Workbooks/AzDDoSStandardWorkbook.json) queries to check for column existence and if does not exist referenced it from Additional fields. Can you please verify it once at your end and let us know if it works?
We cannot test it as the workbook is working fine at our end.

Also, if it is working for **TrafficOverview_s** and **AttackVectors_s** fields at your end as well. Do let us know if any other column needs to be updated.

Thanks,
Ruchita

**Comment by SimoneFrigerio** [comment] 2021-07-19 12:18
Thank you Ruchita let me check it and I will update you asap
Regards
Simone

**Comment by v-rucdu** [comment] 2021-07-22 09:09
> Thank you Ruchita let me check it and I will update you asap Regards Simone From: v-rucdu ***@***.***> Sent: lunedì 19 luglio 2021 13:56 To: Azure/Azure-Sentinel ***@***.***> Cc: Simone Frigerio ***@***.***>; Mention ***@***.***> Subject: Re: [Azure/Azure-Sentinel] Azure DDOS Workbook Error (#2615) @SimoneFrigerio<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FSimoneFrigerio&data=04%7C01%7CSimone.Frigerio%40microsoft.com%7Cf7b5ab55c8c84ed6fc6308d94aac38aa%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637622925871854300%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=CBynZmfEINCLMlfy0VZ6vjDK%2BU5rHAvSOdkwITbPJAM%3D&reserved=0>, Please refer updated the workbook<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAzure%2FAzure-Sentinel%2Fblob%2Fv-rucdu%2FAzureDDoSWorbookIssueFix%2FWorkbooks%2FAzDDoSStandardWorkbook.json&data=04%7C01%7CSimone.Frigerio%40microsoft.com%7Cf7b5ab55c8c84ed6fc6308d94aac38aa%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637622925871864256%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=e%2F26SDCgrWM%2F%2FfUEJbJhswUxiRcWiTxtt8f3zie%2Ftrw%3D&reserved=0> queries to check for column existence and if does not exist referenced it from Additional fields. Can you please verify it once at your end and let us know if it works? We cannot test it as the workbook is working fine at our end. Also, if it is working for TrafficOverview_s and AttackVectors_s fields at your end as well. Do let us know if any other column needs to be updated. Thanks, Ruchita - You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAzure%2FAzure-Sentinel%2Fissues%2F2615%23issuecomment-882487522&data=04%7C01%7CSimone.Frigerio%40microsoft.com%7Cf7b5ab55c8c84ed6fc6308d94aac38aa%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637622925871864256%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=fOHPQSkrm68DNP2yPI%2BooFsTONXLRW4SZsl%2F8CrUSzI%3D&reserved=0>, or unsubscribe<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FATWPT2BSOJTLSMHAOWUPZBDTYQHGHANCNFSM47VFC6VQ&data=04%7C01%7CSimone.Frigerio%40microsoft.com%7Cf7b5ab55c8c84ed6fc6308d94aac38aa%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637622925871874213%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=6%2BcShwQpZoivOSRQD0BYXPNogRu6Q6TjOME5Cgh1vgg%3D&reserved=0>.

Hey @SimoneFrigerio : Did you get a chance to verify the queries?

Thanks,
Ruchita

**Comment by v-rucdu** [comment] 2021-07-28 09:51
@SimoneFrigerio : I have raised a [PR](https://github.com/Azure/Azure-Sentinel/pull/2753) with the fix I shared with you earlier. Could you please verify once and provide approval if all is good?

**Comment by v-rucdu** [comment] 2021-08-10 08:54
Closing this incident as we didn't get any response on the proposed fix from @SimoneFrigerio from long time. Please reopen the if the issue is exist.

Thanks!!!

**Closed by v-rucdu** 2021-08-10 08:54 UTC

**Comment by SimoneFrigerio** [comment] 2021-09-16 08:57
Sorry to be late, but is not fixed, it give us everything 0 and some error...
Simone
