### ISSUE TITLE
GitHub API Throttling due to rate limitation in the GitHub function app. 

### ISSUE THREAD

**Issue by cybertechassociates** [Azure/Azure-Sentinel#9949] opened 2024-02-13 14:49 UTC
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by v-muuppugund** [comment] 2024-02-14 02:35
Hi @cybertechassociates , Thanks for flagging this issue, we will investigate this issue and get back to you with some updates by 16Feb24. Thanks!

**Comment by v-muuppugund** [comment] 2024-02-16 08:29
Hi @cybertechassociates ,As discussed yesterday completed the initial analysis for the proposed solution and working on POC ,will share updates over status call.

**Comment by v-muuppugund** [comment] 2024-02-21 00:53
Hi @cybertechassociates ,As discussed over teams yesterday, The following are done

1. Initial Analysis
2. Algorithm created
3. Working on creating the required components ,once done will start POC code changes

**Comment by v-muuppugund** [comment] 2024-02-25 04:13
Hi @cybertechassociates ,As discussed on last friday,Resolved the issue for JWT token generation and moved to next step,working on it

**Comment by v-muuppugund** [comment] 2024-03-08 02:14
Hi @cybertechassociates ,as discussed on last week over teams and yesterday ,the following is the status
1.able to generate jwt token
2.based on installation I'd able generate token and call an api
3.currently working on calling api although automatically getting installation I'd,

**Comment by v-muuppugund** [comment] 2024-03-14 03:14
Hi @cybertechassociates ,As discussed yesterday,Working on the following

1. Calling apis with installation token
2. Will share an update today

**Comment by v-muuppugund** [comment] 2024-03-15 17:48
Hi @cybertechassociates ,As discussed today,issue has been resolved and working on validations and integartions

**Comment by v-muuppugund** [comment] 2024-03-21 03:12
Hi @cybertechassociates ,As discussed yesterday,the following is the status

- Working on integrations and validations this week and will do testing next week starting and share results

**Comment by v-muuppugund** [comment] 2024-03-22 09:01
Hi @cybertechassociates ,as discussed yesterday,the following is the status
The following is the status
1.Worked on POC completion
2.Worked on integration with GitHub function 
The following are next steps
1.Local testing of Integrated function app
2.Deployment and testing
3.Any issues fixes during testig
4.Demo
5.ASDA integration

**Comment by v-muuppugund** [comment] 2024-03-28 15:29
Hi @cybertechassociates ,As discussed yesterday and today,the following is status

1. Working on integration testing locally
2. Once testing completed with no issues
3. Will work on deployement and testing

**Comment by v-muuppugund** [comment] 2024-04-11 02:16
Hi @cybertechassociates ,As discussed yesterday and earlier over teams,Please find current status

- Completed the changes
- Got the results in log analytics
- fixed the infinite loop issue
- Added null checks

Working on deployement and testing once done will update

**Comment by v-muuppugund** [comment] 2024-04-16 10:27
Hi @cybertechassociates ,As discussed with you ,demo is done and last Friday and PR has been raised(https://github.com/Azure/Azure-Sentinel/pull/10303)for this enhancement
Please find below screen shots for reference
![image](https://github.com/Azure/Azure-Sentinel/assets/139563098/8094807f-f14e-4ff2-abce-9fac9cf1b9da)
![image](https://github.com/Azure/Azure-Sentinel/assets/139563098/d70854ee-230a-4a2b-a943-074aaec2163f)

**Comment by v-muuppugund** [comment] 2024-04-19 08:43
Hi @cybertechassociates , As discussed over call this week and completed the changes and demonstrated the same, PR review is progress, as the issue is resolved, so closing the issue, please let me know if you have issues, we can connect and close it.

**Closed by v-muuppugund** 2024-04-19 08:43 UTC
Labels: enhancement, Connector
