### ISSUE TITLE
JumpCloud Data Connector: Unexpected Lack of 'mdm' and 'software' Log Retrieval

### ISSUE THREAD

**Issue by sbmatrosov** [Azure/Azure-Sentinel#8310] opened 2023-06-20 12:26 UTC
Describe the bug
I have an Azure Function App that utilizes a PowerShell script to call the JumpCloud Directory Insights API and retrieves logs from different services. However, despite proper configuration, the script is not retrieving logs from some services (mdm and software).

To Reproduce

1.Configure the Azure Function App with necessary bindings and environment variables.
2. Specify the services for log retrieval in the JumpCloudEventTypes environment variable.
3.The script is supposed to retrieve logs from the mdm and software services among others.
4. The script runs without any errors but does not retrieve logs from mdm and software services.

Expected behavior
I expected the script to retrieve logs from all specified services, including mdm and software, and post them to the Log Analytics workspace.

Additional context
We have already checked the configuration of the Azure Function App and verified that it is set up correctly to retrieve logs from the specified services. We have also tested the API separately and confirmed that it is capable of retrieving logs from the mdm and software services. This seems to be an issue with the PowerShell script or the way the Azure Function App is processing the script.
link to connector
https://github.com/Azure/Azure-Sentinel/tree/449788b130a598fc381ec07f967e91ee3df62787/DataConnectors/JumpCloud%20Single%20Sign%20On

**Comment by sbmatrosov** [comment] 2023-06-27 18:38
Hello,

Is there any update

**Comment by v-vdixit** [comment] 2023-07-04 05:48
Hi @sbmatrosov thanks for flagging this, we will discuss this with the concerned team and update you shortly.

**Comment by v-vdixit** [comment] 2023-07-06 08:47
Hi @sbmatrosov can you please provide execution logs for the function app, it will help us in tracing the root cause better, thanks!

**Comment by sbmatrosov** [comment] 2023-07-06 09:29
Hi, @v-vdixit I attached verbose logs and errors separately. Please take a look and tell me what you think. 

[2023-07-06T08:56:09Z [Verbose] Poll for.txt ](https://github.com/Azure/Azure-Sentinel/files/11966722/2023-07-06T08.56.09Z.Verbose.Poll.for.txt)
[2023-07-06T09:00:37Z [Error] ERROR: Cann.txt](https://github.com/Azure/Azure-Sentinel/files/11966723/2023-07-06T09.00.37Z.Error.ERROR.Cann.txt)

**Comment by sbmatrosov** [comment] 2023-07-07 07:54
HI @v-vdixit disregard my last message

**Comment by sbmatrosov** [comment] 2023-07-07 08:23
I collected logs from the log stream. In case you need something else, please leave a comment, and I will provide the information asap. 
[2023-07-07T08:56:09Z [Verbose] Poll for.txt ](https://github.com/Azure/Azure-Sentinel/files/11979755/2023-07-07T08.56.09Z.Verbose.Poll.for.txt)

**Comment by v-vdixit** [comment] 2023-07-10 13:30
Hi @sbmatrosov thanks for providing the data, we'll discuss with the team and update you shortly.

**Comment by v-vdixit** [comment] 2023-07-12 09:22
Hi @sbmatrosov we are working on this with the team, will update you shortly, thanks!

**Comment by v-vdixit** [comment] 2023-07-17 11:35
Hi @sbmatrosov we have reached out to the concerned team, will update you once we get update from them, thanks!

**Comment by v-vdixit** [comment] 2023-07-21 04:57
Hi @sbmatrosov we are still waiting for update from the concerned team, thanks!

**Comment by v-vdixit** [comment] 2023-07-24 11:17
Hi @sbmatrosov we are still waiting for update from concerned team, will update you once we hear back from them, thanks!

**Comment by v-rbajaj** [comment] 2023-07-27 10:56
Hi @sbmatrosov, waiting for update from concerned team.

**Comment by v-rbajaj** [comment] 2023-07-31 12:11
Hi @sbmatrosov, waiting for update from concerned team.

**Comment by v-rbajaj** [comment] 2023-08-03 16:23
Hi @sbmatrosov, waiting for update from concerned team.

**Comment by v-rbajaj** [comment] 2023-08-07 12:59
Hi @sbmatrosov, can you please change the runtime version to 4 and restart the function app then check the invocation logs?
![image](https://github.com/Azure/Azure-Sentinel/assets/120547590/fcc9c6ef-693c-4803-92ec-9c61dac248c7)

**Comment by sbmatrosov** [comment] 2023-08-07 15:00
> Hi @sbmatrosov, can you please change the runtime version to 4 and restart the function app then check the invocation logs? ![image](https://user-images.githubusercontent.com/120547590/258808325-fcc9c6ef-693c-4803-92ec-9c61dac248c7.png)

I applied these changes and received a number of errors: 
<img width="804" alt="Screenshot 2023-08-07 at 18 53 05" src="https://github.com/Azure/Azure-Sentinel/assets/135113986/12bed367-8306-46ef-a1e2-47d17dca8ea4">

Also, the Azure App stopped working at all, so I need to turn back the runtime version to 3

**Comment by sbmatrosov** [comment] 2023-08-08 10:40
I guess you need to update host.json with the following: 

{
  "version": "2.0",
  "extensionBundle": {
    "id": "Microsoft.Azure.Functions.ExtensionBundle",
    "version": "[2.6.1,3.0.0)"
  }
}

**Comment by v-rbajaj** [comment] 2023-08-09 11:49
Hi @sbmatrosov, we are checking on this and we will get back to you.

**Comment by v-rbajaj** [comment] 2023-08-17 14:17
Hi @sbmatrosov, we are checking on this and we will get back to you.

**Comment by acidvelvet** [comment] 2023-08-23 07:58
Hi, is there any update on this? It has been two months since this ticket was created.

**Comment by v-rbajaj** [comment] 2023-08-29 13:03
Hi @acidvelvet, I understand your concern, but we trying to reach out to the concerned team for this issue, will get back to you ASAP on this.

**Comment by sbmatrosov** [comment] 2023-09-11 10:32
Hi, 
It seems that the issue has been forgotten. Is there any update on this?

**Comment by v-rbajaj** [comment] 2023-09-14 11:38
Hi @sbmatrosov, we have reached out to the concerned team, we are waiting for response on it, once we get an update we will reach out to you.

**Comment by v-rbajaj** [comment] 2023-09-28 10:39
Hi @sbmatrosov, we have reached out to the concerned team, we are waiting for response on it, once we get an update we will reach out to you.

**Comment by v-rbajaj** [comment] 2023-10-05 11:35
Hi @sbmatrosov, we have reached out to the concerned team, we are waiting for response on it, once we get an update we will reach out to you.

**Comment by v-rbajaj** [comment] 2023-10-09 17:34
Hi @sbmatrosov, we have reached out to the concerned team, we are waiting for response on it. Will provide you an update by 11 Oct 2023

**Comment by sbmatrosov** [comment] 2023-10-09 19:07
Great thanks! Looking forward to it! 
I hope we can fix this year!

**Comment by v-rbajaj** [comment] 2023-10-12 12:15
Hi @sbmatrosov, sure, we are our trying our best to resolve this issue at earliest. Please provide us more time till  17 Oct 2023.

**Comment by v-rbajaj** [comment] 2023-10-16 13:03
Hi @sbmatrosov, we are still investigation on this issue, please provide us more time till 20 Oct 2023.

**Comment by v-rbajaj** [comment] 2023-10-26 11:44
Hi @sbmatrosov, we have tried from our end to reproduce this issue but unfortunately we are not able to achieve that, we would require your help in this case, can you please share us your availability?
My email ID - v-rbajaj@microsoft.com

**Comment by v-rbajaj** [comment] 2023-11-01 03:27
Hi @sbmatrosov, Gentle Reminder: We are awaiting for your response on this issue. If you still need to keep this issue active please respond on it in the next 2 days .. If we don't receive response, we will be close this issue.

**Comment by sbmatrosov** [comment] 2023-11-01 09:49
Hi, I send you an email.

**Comment by v-rbajaj** [comment] 2023-11-02 13:50
Hi @sbmatrosov, I have scheduled for 3:30 PM IST time, please let me know if you are available. Thanks. 
You can ping me on Microsoft Teams as well to discuss further on availabilty.

**Comment by v-rbajaj** [comment] 2023-11-07 06:26
Hi @sbmatrosov, we have reached out to concerned team, and we will get back to you by 9 Nov 2023.

**Comment by v-rbajaj** [comment] 2023-11-09 17:52
Hi @sbmatrosov, we have reached out to concerned team, and we will get back to you by 15 Nov 2023.

**Closed** 2023-11-14 14:15 UTC
Labels: Connector

**Comment by v-sudkharat** [comment] 2024-08-28 11:54
Hey @RahulGGupta, Can you check it once by setting up below configurations: 
1. Select the Runtime version as - 4 
![image](https://github.com/user-attachments/assets/280ace29-4eee-4b31-817c-039d7f8c9f73)

2. Select the PoweShell version 7.4
![image](https://github.com/user-attachments/assets/ad5c1ea6-76af-43f8-8f5f-b262ac073f69)

Save the changes and restart the function App

**Comment by RahulGGupta** [comment] 2024-08-28 12:17
28/8/2024, 5:29:59 pm
Information
Executing 'Functions.JCTimerTrigger' (Reason='Timer fired at 2024-08-28T11:59:59.9988841+00:00', Id=4e3d9112-9d32-438b-b94e-4db7eb2aa9ad)
28/8/2024, 5:30:00 pm
Information
INFORMATION: JumpCloud timer triggered and is running on time! TIME: 08/28/2024 12:00:00
28/8/2024, 5:30:01 pm
Warning
The Function app may be missing a module containing the 'New-AzStorageContext' command definition. If this command belongs to a module available on the PowerShell Gallery, add a reference to this module to requirements.psd1. Make sure this module is compatible with PowerShell 7. For more details, see https://aka.ms/functions-powershell-managed-dependency. If the module is installed but you are still getting this error, try to import the module explicitly by invoking Import-Module just before the command that produces the error: this will not fix the issue but will expose the root cause.
28/8/2024, 5:30:01 pm
Error
28/8/2024, 5:30:01 pm
Error
ERROR: The term 'New-AzStorageContext' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again. Exception : Type : System.Management.Automation.CommandNotFoundException ErrorRecord : Exception : Type : System.Management.Automation.ParentContainsErrorRecordException Message : The term 'New-AzStorageContext' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again. HResult : -2146233087 TargetObject : New-AzStorageContext CategoryInfo : ObjectNotFound: (New-AzStorageContext:String) [], ParentContainsErrorRecordException FullyQualifiedErrorId : CommandNotFoundException InvocationInfo : ScriptLineNumber : 22 OffsetInLine : 15 HistoryId : 1 ScriptName : C:\home\site\wwwroot\JCTimerTrigger\run.ps1 Line : $JCstorage = New-AzStorageContext -ConnectionString $AzureWebJobsStorage PositionMessage : At C:\home\site\wwwroot\JCTimerTrigger\run.ps1:22 char:15 + $JCstorage = New-AzStorageContext -ConnectionString $AzureWebJobsSto … + ~~~~~~~~~~~~~~~~~~~~ PSScriptRoot : C:\home\site\wwwroot\JCTimerTrigger PSCommandPath : C:\home\site\wwwroot\JCTimerTrigger\run.ps1 InvocationName : New-AzStorageContext CommandOrigin : Internal ScriptStackTrace : at <ScriptBlock>, C:\home\site\wwwroot\JCTimerTrigger\run.ps1: line 22 CommandName : New-AzStorageContext TargetSite : Name : LookupCommandInfo DeclaringType : System.Management.Automation.CommandDiscovery, System.Management.Automation, Version=7.0.12.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 MemberType : Method Module : System.Management.Automation.dll StackTrace : at System.Management.Automation.CommandDiscovery.LookupCommandInfo(String commandName, CommandTypes commandTypes, SearchResolutionOptions searchResolutionOptions, CommandOrigin commandOrigin, ExecutionContext context) at System.Management.Automation.CommandDiscovery.TryModuleAutoDiscovery(String commandName, ExecutionContext context, String originalCommandName, CommandOrigin commandOrigin, SearchResolutionOptions searchResolutionOptions, CommandTypes commandTypes, Exception& lastError) at System.Management.Automation.CommandDiscovery.LookupCommandInfo(String commandName, CommandTypes commandTypes, SearchResolutionOptions searchResolutionOptions, CommandOrigin commandOrigin, ExecutionContext context) at System.Management.Automation.CommandDiscovery.LookupCommandProcessor(String commandName, CommandOrigin commandOrigin, Nullable`1 useLocalScope) at System.Management.Automation.ExecutionContext.CreateCommand(String command, Boolean dotSource) at System.Management.Automation.PipelineOps.AddCommand(PipelineProcessor pipe, CommandParameterInternal[] commandElements, CommandBaseAst commandBaseAst, CommandRedirection[] redirections, ExecutionContext context) at System.Management.Automation.PipelineOps.InvokePipeline(Object input, Boolean ignoreInput, CommandParameterInternal[][] pipeElements, CommandBaseAst[] pipeElementAsts, CommandRedirection[][] commandRedirections, FunctionContext funcContext) at System.Management.Automation.Interpreter.ActionCallInstruction`6.Run(InterpretedFrame frame) at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame) at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame) Message : The term 'New-AzStorageContext' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again. Data : System.Collections.ListDictionaryInternal Source : System.Management.Automation HResult : -2146233087 TargetObject : New-AzStorageContext CategoryInfo : ObjectNotFound: (New-AzStorageContext:String) [], CommandNotFoundException FullyQualifiedErrorId : CommandNotFoundException InvocationInfo : ScriptLineNumber : 22 OffsetInLine : 15 HistoryId : 1 ScriptName : C:\home\site\wwwroot\JCTimerTrigger\run.ps1 Line : $JCstorage = New-AzStorageContext -ConnectionString $AzureWebJobsStorage PositionMessage : At C:\home\site\wwwroot\JCTimerTrigger\run.ps1:22 char:15 + $JCstorage = New-AzStorageContext -ConnectionString $AzureWebJobsSto … + ~~~~~~~~~~~~~~~~~~~~ PSScriptRoot : C:\home\site\wwwroot\JCTimerTrigger PSCommandPath : C:\home\site\wwwroot\JCTimerTrigger\run.ps1 InvocationName : New-AzStorageContext CommandOrigin : Internal ScriptStackTrace : at <ScriptBlock>, C:\home\site\wwwroot\JCTimerTrigger\run.ps1: line 22
28/8/2024, 5:30:02 pm
Warning
The Function app may be missing a module containing the 'Get-AzstorageQueue' command definition. If this command belongs to a module available on the PowerShell Gallery, add a reference to this module to requirements.psd1. Make sure this module is compatible with PowerShell 7. For more details, see https://aka.ms/functions-powershell-managed-dependency. If the module is installed but you are still getting this error, try to import the module explicitly by invoking Import-Module just before the command that produces the error: this will not fix the issue but will expose the root cause.
28/8/2024, 5:30:02 pm
Error
28/8/2024, 5:30:02 pm
Error
ERROR: The term 'Get-AzstorageQueue' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again. Exception : Type : System.Management.Automation.CommandNotFoundException ErrorRecord : Exception : Type : System.Management.Automation.ParentContainsErrorRecordException Message : The term 'Get-AzstorageQueue' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again. HResult : -2146233087 TargetObject : Get-AzstorageQueue CategoryInfo : ObjectNotFound: (Get-AzstorageQueue:String) [], ParentContainsErrorRecordException FullyQualifiedErrorId : CommandNotFoundException InvocationInfo : ScriptLineNumber : 25 OffsetInLine : 6 HistoryId : 1 ScriptName : C:\home\site\wwwroot\JCTimerTrigger\run.ps1 Line : if(( Get-AzstorageQueue -context $JCStorage -Name $JCQueuename -ErrorAction SilentlyContinue ).name ){ PositionMessage : At C:\home\site\wwwroot\JCTimerTrigger\run.ps1:25 char:6 + if(( Get-AzstorageQueue -context $JCStorage -Name $JCQueuename -Error … + ~~~~~~~~~~~~~~~~~~ PSScriptRoot : C:\home\site\wwwroot\JCTimerTrigger PSCommandPath : C:\home\site\wwwroot\JCTimerTrigger\run.ps1 InvocationName : Get-AzstorageQueue CommandOrigin : Internal ScriptStackTrace : at <ScriptBlock>, C:\home\site\wwwroot\JCTimerTrigger\run.ps1: line 25 CommandName : Get-AzstorageQueue TargetSite : Name : LookupCommandInfo DeclaringType : System.Management.Automation.CommandDiscovery, System.Management.Automation, Version=7.0.12.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 MemberType : Method Module : System.Management.Automation.dll StackTrace : at System.Management.Automation.CommandDiscovery.LookupCommandInfo(String commandName, CommandTypes commandTypes, SearchResolutionOptions searchResolutionOptions, CommandOrigin commandOrigin, ExecutionContext context) at System.Management.Automation.CommandDiscovery.TryModuleAutoDiscovery(String commandName, ExecutionContext context, String originalCommandName, CommandOrigin commandOrigin, SearchResolutionOptions searchResolutionOptions, CommandTypes commandTypes, Exception& lastError) at System.Management.Automation.CommandDiscovery.LookupCommandInfo(String commandName, CommandTypes commandTypes, SearchResolutionOptions searchResolutionOptions, CommandOrigin commandOrigin, ExecutionContext context) at System.Management.Automation.CommandDiscovery.LookupCommandProcessor(String commandName, CommandOrigin commandOrigin, Nullable`1 useLocalScope) at System.Management.Automation.ExecutionContext.CreateCommand(String command, Boolean dotSource) at System.Management.Automation.PipelineOps.AddCommand(PipelineProcessor pipe, CommandParameterInternal[] commandElements, CommandBaseAst commandBaseAst, CommandRedirection[] redirections, ExecutionContext context) at System.Management.Automation.PipelineOps.InvokePipeline(Object input, Boolean ignoreInput, CommandParameterInternal[][] pipeElements, CommandBaseAst[] pipeElementAsts, CommandRedirection[][] commandRedirections, FunctionContext funcContext) at System.Management.Automation.Interpreter.ActionCallInstruction`6.Run(InterpretedFrame frame) at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame) at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame) Message : The term 'Get-AzstorageQueue' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again. Data : System.Collections.ListDictionaryInternal Source : System.Management.Automation HResult : -2146233087 TargetObject : Get-AzstorageQueue CategoryInfo : ObjectNotFound: (Get-AzstorageQueue:String) [], CommandNotFoundException FullyQualifiedErrorId : CommandNotFoundException InvocationInfo : ScriptLineNumber : 25 OffsetInLine : 6 HistoryId : 1 ScriptName : C:\home\site\wwwroot\JCTimerTrigger\run.ps1 Line : if(( Get-AzstorageQueue -context $JCStorage -Name $JCQueuename -ErrorAction SilentlyContinue ).name ){ PositionMessage : At C:\home\site\wwwroot\JCTimerTrigger\run.ps1:25 char:6 + if(( Get-AzstorageQueue -context $JCStorage -Name $JCQueuename -Error … + ~~~~~~~~~~~~~~~~~~ PSScriptRoot : C:\home\site\wwwroot\JCTimerTrigger PSCommandPath : C:\home\site\wwwroot\JCTimerTrigger\run.ps1 InvocationName : Get-AzstorageQueue CommandOrigin : Internal ScriptStackTrace : at <ScriptBlock>, C:\home\site\wwwroot\JCTimerTrigger\run.ps1: line 25
28/8/2024, 5:30:02 pm
Error
28/8/2024, 5:30:02 pm
Error
ERROR: You cannot call a method on a null-valued expression. Exception : Type : System.Management.Automation.RuntimeException ErrorRecord : Exception : Type : System.Management.Automation.ParentContainsErrorRecordException Message : You cannot call a method on a null-valued expression. HResult : -2146233087 CategoryInfo : InvalidOperation: (:) [], ParentContainsErrorRecordException FullyQualifiedErrorId : InvokeMethodOnNull InvocationInfo : ScriptLineNumber : 41 OffsetInLine : 9 HistoryId : -1 ScriptName : C:\home\site\wwwroot\JCTimerTrigger\run.ps1 Line : $JCqueue.CloudQueue.AddMessageAsync($QueueMessage) PositionMessage : At C:\home\site\wwwroot\JCTimerTrigger\run.ps1:41 char:9 + $JCqueue.CloudQueue.AddMessageAsync($QueueMessage) + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ PSScriptRoot : C:\home\site\wwwroot\JCTimerTrigger PSCommandPath : C:\home\site\wwwroot\JCTimerTrigger\run.ps1 CommandOrigin : Internal ScriptStackTrace : at <ScriptBlock>, C:\home\site\wwwroot\JCTimerTrigger\run.ps1: line 41 at <ScriptBlock>, C:\home\site\wwwroot\JCTimerTrigger\run.ps1: line 38 TargetSite : System.Object CallSite.Target(System.Runtime.CompilerServices.Closure, System.Runtime.CompilerServices.CallSite, System.Object, System.Object) StackTrace : at CallSite.Target(Closure , CallSite , Object , Object ) at <ScriptBlock>(Closure , FunctionContext ) Message : You cannot call a method on a null-valued expression. Source : Anonymously Hosted DynamicMethods Assembly HResult : -2146233087 CategoryInfo : InvalidOperation: (:) [], RuntimeException FullyQualifiedErrorId : InvokeMethodOnNull InvocationInfo : ScriptLineNumber : 41 OffsetInLine : 9 HistoryId : -1 ScriptName : C:\home\site\wwwroot\JCTimerTrigger\run.ps1 Line : $JCqueue.CloudQueue.AddMessageAsync($QueueMessage) PositionMessage : At C:\home\site\wwwroot\JCTimerTrigger\run.ps1:41 char:9 + $JCqueue.CloudQueue.AddMessageAsync($QueueMessage) + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ PSScriptRoot : C:\home\site\wwwroot\JCTimerTrigger PSCommandPath : C:\home\site\wwwroot\JCTimerTrigger\run.ps1 CommandOrigin : Internal ScriptStackTrace : at <ScriptBlock>, C:\home\site\wwwroot\JCTimerTrigger\run.ps1: line 41 at <ScriptBlock>, C:\home\site\wwwroot\JCTimerTrigger\run.ps1: line 38
28/8/2024, 5:30:02 pm
Error
28/8/2024, 5:30:02 pm
Error
ERROR: You cannot call a method on a null-valued expression. Exception : Type : System.Management.Automation.RuntimeException ErrorRecord : Exception : Type : System.Management.Automation.ParentContainsErrorRecordException Message : You cannot call a method on a null-valued expression. HResult : -2146233087 CategoryInfo : InvalidOperation: (:) [], ParentContainsErrorRecordException FullyQualifiedErrorId : InvokeMethodOnNull InvocationInfo : ScriptLineNumber : 41 OffsetInLine : 9 HistoryId : -1 ScriptName : C:\home\site\wwwroot\JCTimerTrigger\run.ps1 Line : $JCqueue.CloudQueue.AddMessageAsync($QueueMessage) PositionMessage : At C:\home\site\wwwroot\JCTimerTrigger\run.ps1:41 char:9 + $JCqueue.CloudQueue.AddMessageAsync($QueueMessage) + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ PSScriptRoot : C:\home\site\wwwroot\JCTimerTrigger PSCommandPath : C:\home\site\wwwroot\JCTimerTrigger\run.ps1 CommandOrigin : Internal ScriptStackTrace : at <ScriptBlock>, C:\home\site\wwwroot\JCTimerTrigger\run.ps1: line 41 at <ScriptBlock>, C:\home\site\wwwroot\JCTimerTrigger\run.ps1: line 38 TargetSite : System.Object CallSite.Target(System.Runtime.CompilerServices.Closure, System.Runtime.CompilerServices.CallSite, System.Object, System.Object) StackTrace : at CallSite.Target(Closure , CallSite , Object , Object ) at <ScriptBlock>(Closure , FunctionContext ) Message : You cannot call a method on a null-valued expression. Source : Anonymously Hosted DynamicMethods Assembly HResult : -2146233087 CategoryInfo : InvalidOperation: (:) [], RuntimeException FullyQualifiedErrorId : InvokeMethodOnNull InvocationInfo : ScriptLineNumber : 41 OffsetInLine : 9 HistoryId : -1 ScriptName : C:\home\site\wwwroot\JCTimerTrigger\run.ps1 Line : $JCqueue.CloudQueue.AddMessageAsync($QueueMessage) PositionMessage : At C:\home\site\wwwroot\JCTimerTrigger\run.ps1:41 char:9 + $JCqueue.CloudQueue.AddMessageAsync($QueueMessage) + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ PSScriptRoot : C:\home\site\wwwroot\JCTimerTrigger PSCommandPath : C:\home\site\wwwroot\JCTimerTrigger\run.ps1 CommandOrigin : Internal ScriptStackTrace : at <ScriptBlock>, C:\home\site\wwwroot\JCTimerTrigger\run.ps1: line 41 at <ScriptBlock>, C:\home\site\wwwroot\JCTimerTrigger\run.ps1: line 38
28/8/2024, 5:30:02 pm
Error
28/8/2024, 5:30:02 pm
Error
ERROR: You cannot call a method on a null-valued expression. Exception : Type : System.Management.Automation.RuntimeException ErrorRecord : Exception : Type : System.Management.Automation.ParentContainsErrorRecordException Message : You cannot call a method on a null-valued expression. HResult : -2146233087 CategoryInfo : InvalidOperation: (:) [], ParentContainsErrorRecordException FullyQualifiedErrorId : InvokeMethodOnNull InvocationInfo : ScriptLineNumber : 41 OffsetInLine : 9 HistoryId : -1 ScriptName : C:\home\site\wwwroot\JCTimerTrigger\run.ps1 Line : $JCqueue.CloudQueue.AddMessageAsync($QueueMessage) PositionMessage : At C:\home\site\wwwroot\JCTimerTrigger\run.ps1:41 char:9 + $JCqueue.CloudQueue.AddMessageAsync($QueueMessage) + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ PSScriptRoot : C:\home\site\wwwroot\JCTimerTrigger PSCommandPath : C:\home\site\wwwroot\JCTimerTrigger\run.ps1 CommandOrigin : Internal ScriptStackTrace : at <ScriptBlock>, C:\home\site\wwwroot\JCTimerTrigger\run.ps1: line 41 at <ScriptBlock>, C:\home\site\wwwroot\JCTimerTrigger\run.ps1: line 38 TargetSite : System.Object CallSite.Target(System.Runtime.CompilerServices.Closure, System.Runtime.CompilerServices.CallSite, System.Object, System.Object) StackTrace : at CallSite.Target(Closure , CallSite , Object , Object ) at <ScriptBlock>(Closure , FunctionContext ) Message : You cannot call a method on a null-valued expression. Source : Anonymously Hosted DynamicMethods Assembly HResult : -2146233087 CategoryInfo : InvalidOperation: (:) [], RuntimeException FullyQualifiedErrorId : InvokeMethodOnNull InvocationInfo : ScriptLineNumber : 41 OffsetInLine : 9 HistoryId : -1 ScriptName : C:\home\site\wwwroot\JCTimerTrigger\run.ps1 Line : $JCqueue.CloudQueue.AddMessageAsync($QueueMessage) PositionMessage : At C:\home\site\wwwroot\JCTimerTrigger\run.ps1:41 char:9 + $JCqueue.CloudQueue.AddMessageAsync($QueueMessage) + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ PSScriptRoot : C:\home\site\wwwroot\JCTimerTrigger PSCommandPath : C:\home\site\wwwroot\JCTimerTrigger\run.ps1 CommandOrigin : Internal ScriptStackTrace : at <ScriptBlock>, C:\home\site\wwwroot\JCTimerTrigger\run.ps1: line 41 at <ScriptBlock>, C:\home\site\wwwroot\JCTimerTrigger\run.ps1: line 38
28/8/2024, 5:30:02 pm
Error
28/8/2024, 5:30:02 pm
Error
ERROR: You cannot call a method on a null-valued expression. Exception : Type : System.Management.Automation.RuntimeException ErrorRecord : Exception : Type : System.Management.Automation.ParentContainsErrorRecordException Message : You cannot call a method on a null-valued expression. HResult : -2146233087 CategoryInfo : InvalidOperation: (:) [], ParentContainsErrorRecordException FullyQualifiedErrorId : InvokeMethodOnNull InvocationInfo : ScriptLineNumber : 41 OffsetInLine : 9 HistoryId : -1 ScriptName : C:\home\site\wwwroot\JCTimerTrigger\run.ps1 Line : $JCqueue.CloudQueue.AddMessageAsync($QueueMessage) PositionMessage : At C:\home\site\wwwroot\JCTimerTrigger\run.ps1:41 char:9 + $JCqueue.CloudQueue.AddMessageAsync($QueueMessage) + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ PSScriptRoot : C:\home\site\wwwroot\JCTimerTrigger PSCommandPath : C:\home\site\wwwroot\JCTimerTrigger\run.ps1 CommandOrigin : Internal ScriptStackTrace : at <ScriptBlock>, C:\home\site\wwwroot\JCTimerTrigger\run.ps1: line 41 at <ScriptBlock>, C:\home\site\wwwroot\JCTimerTrigger\run.ps1: line 38 TargetSite : System.Object CallSite.Target(System.Runtime.CompilerServices.Closure, System.Runtime.CompilerServices.CallSite, System.Object, System.Object) StackTrace : at CallSite.Target(Closure , CallSite , Object , Object ) at <ScriptBlock>(Closure , FunctionContext ) Message : You cannot call a method on a null-valued expression. Source : Anonymously Hosted DynamicMethods Assembly HResult : -2146233087 CategoryInfo : InvalidOperation: (:) [], RuntimeException FullyQualifiedErrorId : InvokeMethodOnNull InvocationInfo : ScriptLineNumber : 41 OffsetInLine : 9 HistoryId : -1 ScriptName : C:\home\site\wwwroot\JCTimerTrigger\run.ps1 Line : $JCqueue.CloudQueue.AddMessageAsync($QueueMessage) PositionMessage : At C:\home\site\wwwroot\JCTimerTrigger\run.ps1:41 char:9 + $JCqueue.CloudQueue.AddMessageAsync($QueueMessage) + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ PSScriptRoot : C:\home\site\wwwroot\JCTimerTrigger PSCommandPath : C:\home\site\wwwroot\JCTimerTrigger\run.ps1 CommandOrigin : Internal ScriptStackTrace : at <ScriptBlock>, C:\home\site\wwwroot\JCTimerTrigger\run.ps1: line 41 at <ScriptBlock>, C:\home\site\wwwroot\JCTimerTrigger\run.ps1: line 38
28/8/2024, 5:30:02 pm
Error
28/8/2024, 5:30:02 pm
Error
ERROR: You cannot call a method on a null-valued expression. Exception : Type : System.Management.Automation.RuntimeException ErrorRecord : Exception : Type : System.Management.Automation.ParentContainsErrorRecordException Message : You cannot call a method on a null-valued expression. HResult : -2146233087 CategoryInfo : InvalidOperation: (:) [], ParentContainsErrorRecordException FullyQualifiedErrorId : InvokeMethodOnNull InvocationInfo : ScriptLineNumber : 41 OffsetInLine : 9 HistoryId : -1 ScriptName : C:\home\site\wwwroot\JCTimerTrigger\run.ps1 Line : $JCqueue.CloudQueue.AddMessageAsync($QueueMessage) PositionMessage : At C:\home\site\wwwroot\JCTimerTrigger\run.ps1:41 char:9 + $JCqueue.CloudQueue.AddMessageAsync($QueueMessage) + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ PSScriptRoot : C:\home\site\wwwroot\JCTimerTrigger PSCommandPath : C:\home\site\wwwroot\JCTimerTrigger\run.ps1 CommandOrigin : Internal ScriptStackTrace : at <ScriptBlock>, C:\home\site\wwwroot\JCTimerTrigger\run.ps1: line 41 at <ScriptBlock>, C:\home\site\wwwroot\JCTimerTrigger\run.ps1: line 38 TargetSite : System.Object CallSite.Target(System.Runtime.CompilerServices.Closure, System.Runtime.CompilerServices.CallSite, System.Object, System.Object) StackTrace : at CallSite.Target(Closure , CallSite , Object , Object ) at <ScriptBlock>(Closure , FunctionContext ) Message : You cannot call a method on a null-valued expression. Source : Anonymously Hosted DynamicMethods Assembly HResult : -2146233087 CategoryInfo : InvalidOperation: (:) [], RuntimeException FullyQualifiedErrorId : InvokeMethodOnNull InvocationInfo : ScriptLineNumber : 41 OffsetInLine : 9 HistoryId : -1 ScriptName : C:\home\site\wwwroot\JCTimerTrigger\run.ps1 Line : $JCqueue.CloudQueue.AddMessageAsync($QueueMessage) PositionMessage : At C:\home\site\wwwroot\JCTimerTrigger\run.ps1:41 char:9 + $JCqueue.CloudQueue.AddMessageAsync($QueueMessage) + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ PSScriptRoot : C:\home\site\wwwroot\JCTimerTrigger PSCommandPath : C:\home\site\wwwroot\JCTimerTrigger\run.ps1 CommandOrigin : Internal ScriptStackTrace : at <ScriptBlock>, C:\home\site\wwwroot\JCTimerTrigger\run.ps1: line 41 at <ScriptBlock>, C:\home\site\wwwroot\JCTimerTrigger\run.ps1: line 38
28/8/2024, 5:30:02 pm
Information
Executed 'Functions.JCTimerTrigger' (Succeeded, Id=4e3d9112-9d32-438b-b94e-4db7eb2aa9ad, Duration=2756ms)

**Comment by v-sudkharat** [comment] 2024-08-28 12:27
@RahulGGupta, Based on the invocations, the logs, the function app still running on Poweshell version 7 or need to generate new logs with 7.4. 
Could you please verify the configuration again, and wait for some time to generate new logs

**Comment by RahulGGupta** [comment] 2024-08-28 13:17
i just verified its 7.4 only and in notification
![functionapp1](https://github.com/user-attachments/assets/0d1c8ee4-194b-4105-9940-54017489d26f)
 its also giving below errors
