### ISSUE TITLE
Microsoft Sentinel - Delay for Automation Rule execution

### ISSUE THREAD

**Issue by rtdamiani** [Azure/Azure-Sentinel#9890] opened 2024-02-02 19:36 UTC
For a few days I am analyzing a scenario in Sentinel incidents.

In the environment I have some Automation Rules for executing a playbook, closing an incident, adding a tag.

When an incident originates from Defender (Endpoint, Entra ID Protection, Office 365) the Automation Rule takes 5 or minutes to execute.

When an incident originates from Analytic Rules, the execution of the Automation Rule is practically instantaneous.

**Comment by rtdamiani** [comment] 2024-02-05 11:46
Hi @v-sudkharat , I have attached two files.

print1: incident created by an analytic rule
print2: incident created by Defender

When an incident originates from Defender, the Automation Rule presents a delay to execute the playbook, add a tag or close the incident.


![print2](https://github.com/Azure/Azure-Sentinel/assets/99505014/9c3358fe-c144-4d1c-8647-d0310e19132e)
![print1](https://github.com/Azure/Azure-Sentinel/assets/99505014/539dc6a8-547c-4f45-bc25-e1990112d4d1)

**Comment by rtdamiani** [comment] 2024-02-09 00:52
Hi @v-sudkharat. Is there any feedback on this issue?

**Comment by v-sudkharat** [comment] 2024-02-09 07:22
Hi @rtdamiani, We are still working on investigating this issue by checking the respective playbooks. Meantime, could you please share you mail id with us? so if required we can connect with you via a call. Thanks!

**Comment by v-sudkharat** [comment] 2024-02-13 06:30
Hi @rtdamiani. Hope you are doing well. We are waiting for your response on above comment. Thanks!

**Comment by rtdamiani** [comment] 2024-02-15 00:18
Hi, @v-sudkharat thanks for sharing your analysis.

Automarion rule is configured with the trigger "When incident is created".

![automation rule](https://github.com/Azure/Azure-Sentinel/assets/99505014/cca9df57-280d-49ce-92d4-bed65a9b0241)


The settings for LogicApp "Enrich-Incident-Alienvault-OTX" haven't been changed. Comment and tag are added by logicapp.

![logicapp](https://github.com/Azure/Azure-Sentinel/assets/99505014/338dc3b5-65b8-443c-9830-ce4fa95df4d7)


My email is rafael.damiani@hotmail.com

**Comment by v-sudkharat** [comment] 2024-02-15 12:58
@rtdamiani, thank you for your response. We will check in this and get back to you by - 20-02-2024. Thanks!

**Comment by v-sudkharat** [comment] 2024-02-20 11:35
Hi @rtdamiani, We have sent a mail to you. Could you please check it and share your response. Thanks!

**Comment by v-sudkharat** [comment] 2024-02-22 10:58
Hi @rtdamiani, we are waiting for your response on above comment. Thanks!

**Comment by v-sudkharat** [comment] 2024-02-29 07:36
Hi @rtdamiani, Could you please let us know if this issue gets resolved. So we can close this issue from GitHub. Thanks!

**Comment by rtdamiani** [comment] 2024-02-29 15:24
Hi @v-sudkharat 

Can you add here a print of an automation rule being executed in an incident originating from Defender in your environment?

**Comment by v-sudkharat** [comment] 2024-03-01 06:43
Hi @rtdamiani, currently our environment does not have that playbook configured, so due to that we can't add print over github. Thanks!

**Comment by rtdamiani** [comment] 2024-03-01 11:57
Hi @v-sudkharat 

I recommend you read again the email I sent to you on 02-02 at 08:53 AM.

In the email I explain and provide evidence that the delay to execute automations isn't related to the playbook execution, but to any Automation Rule executed in Defender incidents. The evidence contains a print of an incident originating from Entra ID Identity Protection. An Automation Rule has been configured in the environment to just add a comment and close the incident.

The print shows the Activity Log of the incident, when the Defender Automation Rule originates, it takes an average of 7 minutes to start. In another print with Activity Log of an incident generated by Analytic Rule, the Automation Rule is executed in the same minute.

The delay I'm talking about isn't related to any automation rule (with or without a playbook) in the 3 tenants I manage.

Again I ask: Is this behavior normal or is it a possible problem in Microsoft Sentinel?

Below are the prints:

Incident created by analytic rule

![teste1](https://github.com/Azure/Azure-Sentinel/assets/99505014/f67b5f3a-3d32-4978-a608-50c24e063b03)

![teste2](https://github.com/Azure/Azure-Sentinel/assets/99505014/b9bf3340-b956-41ed-a449-14cd57ad34f5)



Incident created by Defender

![teste4](https://github.com/Azure/Azure-Sentinel/assets/99505014/77dde2e7-bf6e-45bb-98f0-d98efd19d9f3)

![teste3](https://github.com/Azure/Azure-Sentinel/assets/99505014/ecc4b39a-6a8a-475b-8191-0536c76e4536)

**Comment by v-sudkharat** [comment] 2024-03-04 12:19
Hi @rtdamiani, we will check on it and get back to you with some updates via a GitHub comment or Mail. Thanks!

**Comment by v-sudkharat** [comment] 2024-03-08 12:59
Hi @rtdamiani, After our last call, we have replicated this issue in our environment, please find below screenshot for reference in which there is delay up to 10 min after creating an incident by Microsoft Defender XDR.  
  
![image](https://github.com/Azure/Azure-Sentinel/assets/132428394/1f55eca4-c707-4517-b844-32c810ab9005)

Sharing the MS doc screenshot and link for reference - 
Link - https://learn.microsoft.com/en-us/azure/sentinel/microsoft-365-defender-sentinel-integration
![image](https://github.com/Azure/Azure-Sentinel/assets/132428394/780ea7ee-b649-4d0a-9609-867f013143aa)

Please let us know if you still have any queries further.

**Comment by Kaloszer** [comment] 2024-03-11 08:10
@v-sudkharat The issue isn't about the **_incident taking 10 minutes to show up within Sentinel_**, but that it **_takes >5 minutes to start executing an automation rule_**. It should be instantaneous as for other sources. We are seeing the same behavior. If this is working as designed please confirm that.

Over that 5 minute period an incident can be picked up by an agent wasting time because it would be handled by an automation rule otherwise.

**Comment by v-sudkharat** [comment] 2024-03-12 11:49
Hey @rtdamiani /@Kaloszer, We have shared this feedback with our respective concern team, Once we receive the update from them, will update you. Thanks!

**Comment by rahul0216** [comment] 2024-03-13 16:15
Hi @rtdamiani / @Kaloszer. Thanks for the patience so far. Even we had this issue puzzled, so we reached out to Automation team for the clarification.  
This confusion is caused because the timestamp for the first activity log "Incident was created"  is the timestamp when this incident is created in Microsoft Defender. Let me explain from above screenshot that you have shared.
1. An incident is created in Microsoft Defender at 5.02 PM
2. Through Microsoft Defender connector it took around 6 minutes to appear in Microsoft Sentinel at 5.08 PM
3. This generated activity log "Incident was created" but timestamp used 5.02 PM when it was created in Microsoft Defender 
4. At the same time automation rule triggered. 

So there is no delay in automation trigger. 
The choice to use the Microsoft Defender incident timestamp is intentional, to keep data at both the places Defender and Sentinel coherent.

**Comment by rtdamiani** [comment] 2024-03-14 01:03
Hi, @rahul0216 thanks for your feedback.

I understood what you explained about the time the incident is created in Defender being different from the time the incident is created in Sentinel.

But the time that appears in "Incident was created" in "Incident activity log" is the "CreatedTime" of the incident in Sentinel. The time the incident was created in Defender is the "FirstActivityTime".

Using the SecurityIncident table to collect the data:

Title: Email messages containing malicious file removed after delivery​
IncidentNumber: 19019
FirstActivityTime: 3/12/2024, 10:13:56.891 AM
CreatedTime: 3/12/2024, 10:31:49.940 AM
TimeToSyncSentinel: 18 minutes

![tableincident](https://github.com/Azure/Azure-Sentinel/assets/99505014/a51f6ae6-f022-4053-a60f-f6b592f74e51)




Now showing the incident and Activity log:

Incident was created: 03/12/24, 10:31 AM == CreatedTime: 3/12/2024, 10:31:49.940 AM

![activity](https://github.com/Azure/Azure-Sentinel/assets/99505014/28ff2455-bc59-479e-b563-645f30847db9)



Automation rule executed only to close the incident, without playbook execution.

![automation rule](https://github.com/Azure/Azure-Sentinel/assets/99505014/9e9139f6-96b5-4cc9-a14d-7eb7723ebbd8)



Again, I'm showing that Delay is related to the execution of any automation in Defender incidents.

The time to synchronize the incident between Defender and Sentinel was 18 minutes and the delay to start the automation was 7 minutes.

**Comment by rahul0216** [comment] 2024-03-14 05:39
No exactly,
![image](https://github.com/Azure/Azure-Sentinel/assets/8243910/3bf69bff-de42-499b-b7c4-729e017732bb)

**Comment by v-sudkharat** [comment] 2024-03-15 13:20
Hi @rtdamiani / @Kaloszer, We understand your question, The Creation time which you see after the Incident get generated it is Incident creation time in Defender, not the incident created into the sentinel. 
As mentioned into the MS doc, the sync having upto 10 min of delay. So once the Incident is fully created into the Sentinel, the automation rule will run without having any delay. 
as @rahul0216, added into above comment, to keep this data sync in both the places, the timestamp has been chosen for it. 

Hope we have clear this. Let us know if your issue gets resolved so we can close this issue from GitHub. 
Thanks!

**Comment by v-sudkharat** [comment] 2024-03-18 09:27
@rtdamiani / @Kaloszer, We are closing this issue. If you still need support for this issue, feel free to re-open it any time. Thank you for your co-operation.

**Closed by v-sudkharat** 2024-03-18 09:27 UTC
Labels: Playbook
