### ISSUE TITLE
HTTP Response Error due to invalid input from Sentinel Workbook (Get-SentinelAlertsEvidence)

### ISSUE THREAD

**Issue by LautrecSec** [Azure/Azure-Sentinel#4133] opened 2022-02-08 22:09 UTC
**Describe the bug**
Failed to get HTTP response because of invalid input (DRAFT, queryData). Bad request input. Please Check user input parameters (query syntax, chart type or other resource input)\r\nclientRequestId: 932a4abb-503d-47e4-bc09-f23735a44bd3"

**To Reproduce**
Go to 'Sentinel Incident - View full details - Alerts - View Playbook'
Click on RUN
Go Back to automation, Active Playbook and in overview we can see last execution failed
See error in Run details

**Expected behavior**
Suppose to have a copy of the incident and the related entities in Event Hub

**Screenshots**

![Sentinel Alert Output](https://user-images.githubusercontent.com/47429862/153083851-c6bcbd25-a936-4720-95c6-3b2984e8144a.PNG)

**Comment by samikroy** [comment] 2022-02-09 04:44
@simonkudla - Could you please try the steps mentioned in #4055 
Please revert for any queries.

**Comment by simonkudla** [comment] 2022-02-09 16:13
Hi @samikroy,

I have updated and confirmed the steps mentioned in #4055, but I am now having an additional error in my logic app:

![image](https://user-images.githubusercontent.com/47429862/153241881-0752ec7a-d729-4c72-90e7-4adff62b6224.png)


InvalidTemplate. Unable to process template language expressions in action 'Parse_JSON' inputs at line '0' and column '0': 'Required property 'content' expects a value but got null. Path ''.'.

Thanks.

**Comment by simonkudla** [comment] 2022-02-09 16:39
Hi @samikroy,

I have tried the steps mentioned in #4055 and tried to trigger the playbook within sentinel again, but i'm now seeing a different error in the workflow:

![image](https://user-images.githubusercontent.com/47429862/153246837-f6ea90b7-145d-4531-a09e-8ea160219398.png)

Error: InvalidTemplate. Unable to process template language expressions in action 'Parse_JSON' inputs at line '0' and column '0': 'Required property 'content' expects a value but got null. Path ''.'.

Thanks.

**Comment by samikroy** [comment] 2022-02-09 18:50
@simonkudla - Thank you for sharing the error details.
Alert evidence is gathered / applicable for the scheduled alerts with and extended property being available 
Please run this for a alert-incident generated though a scheduled query having extended property.

![image](https://user-images.githubusercontent.com/20562985/153269452-e8f2d9ff-224e-4d8a-877a-3309b51d5713.png)

**Comment by simonkudla** [comment] 2022-02-14 22:49
Hi @samikroy, apologies for the delayed response as I was away for a few days.
I'm a little confused with your instructions... where should this extended property be added? into the existing Parse JSON action?

Thanks.

**Comment by simonkudla** [comment] 2022-03-09 20:33
Hi,

Could I please get some assistance with this?

**Comment by samikroy** [comment] 2022-03-10 10:54
> Hi,
> 
> Could I please get some assistance with this?

@simonkudla - As the logic app says it is expected to bring the the evidence for an alert.
If we consider the schema of the SecurityAlert table
1. ExtendedProperty  is a column inside table which stores the query used with time stamp.
2. There are columns like Actual Query & Query which are parsed in this step to call them from the logic app.
![image](https://user-images.githubusercontent.com/20562985/157646639-ed7c4353-3e8d-402e-bc94-10f1f03a37a0.png)

![image](https://user-images.githubusercontent.com/20562985/157646820-ce1b4667-877d-4aa5-8788-95193729260f.png)

3. Finally logic app get all the raw event data from the extracted query.

As part of troubleshooting we need to fix the connections.

**Comment by v-amolpatil** [comment] 2023-02-08 17:10
Hi @LautrecSec , thank you for flagging this. Apologies for the delayed response. If you still need assistance, please reply here within 5 business days.

**Comment by v-amolpatil** [comment] 2023-02-27 08:02
Since we have not received a response in the last 5 days, we are closing your issue #4133 as per our standard operating procedures. If you still need support for this issue, feel free to re-open at any time. Thank you for your co-operation.

**Closed by v-amolpatil** 2023-02-27 08:02 UTC
Labels: Playbook
