### ISSUE TITLE
Proofpoint POD Function App Issue

### ISSUE THREAD

**Issue by djkapur** [Azure/Azure-Sentinel#8184] opened 2023-06-01 20:53 UTC
We are intermittently seeing issue with Proofpoint Function app where it retrieves mail logs, but doesn't pull any message logs and sometimes vice-versa. We also did follow-up with Proofpoint support for this issue and they confirmed that there is no issue at their end and logs are also available.  They always ask for network trace logs which is not possible to have with this app.

We are stuck at how troubleshooting should be done and what is the exact issue.

 

![image](https://github.com/Azure/Azure-Sentinel/assets/113426281/28512f9b-6e94-4bae-b880-9fe8a021499a)

**Comment by v-vdixit** [comment] 2023-06-09 05:37
Hi @djkapur thanks for flagging this, we are working on this, will update you shortly, thanks!

**Comment by djkapur** [comment] 2023-06-12 08:28
Hi @v-vdixit Please let me know if you need any details.

**Comment by v-vdixit** [comment] 2023-06-19 05:54
Hi @djkapur we are working on tracing the root cause for this with the team, can you please provide execution logs for this, as it will help us better in troubleshooting, thanks!

**Comment by v-vdixit** [comment] 2023-06-19 08:49
Yes @djkapur we are looking for trace logs only, thanks!

**Comment by v-vdixit** [comment] 2023-06-26 11:27
Hi @djkapur thanks for providing us the logs, we are working with the team on this issue and will provide you update by the end of this week, thanks!

**Comment by v-vdixit** [comment] 2023-07-06 10:07
Hi @djkapur we are testing the updates we have made in the function app, will publish changes once testing is completed, thanks!

**Comment by v-vdixit** [comment] 2023-07-10 13:28
Hi @djkapur we are still working on updates we have made in the function app, will publish changes once testing is completed, thanks!

**Comment by v-vdixit** [comment] 2023-07-12 11:02
We are still working on updates in the function app, will publish changes once testing is completed, thanks!

**Comment by v-vdixit** [comment] 2023-07-14 03:13
Hi @djkapur as the 'connection failed' error is not a direct failure and requires deep troubleshooting we are looking at the function execution files to trace the root cause of error, we will provide you next update by Thursday, 20th July 2023, thanks!

**Comment by v-vdixit** [comment] 2023-07-19 08:48
Hi @djkapur we are still looking into this, will update by Thursday, 20th July 2023, thanks!

**Comment by v-vdixit** [comment] 2023-07-21 09:36
Hi @djkapur we have recently made some updates in this, can you please try to restart the function app once and let us know if you are still facing this issue, thanks!

**Comment by djkapur** [comment] 2023-07-24 10:43
Hi @v-vdixit, I have restarted the function app. And, we are still using Runtime version 3 with app. do you think it will make any difference.

<img width="323" alt="image" src="https://github.com/Azure/Azure-Sentinel/assets/113426281/fa3712c5-494b-4a77-bb23-2e0b1d300df4">

**Comment by v-vdixit** [comment] 2023-07-24 11:40
Hi @djkapur thanks for the update, can you please deploy the latest function app from GitHub and run at version 4, thanks!

**Comment by v-sudkharat** [comment] 2023-07-26 12:28
Hello @djkapur, as per previous comment please can you deploy the latest function app from GitHub and run at version 4. Thanks!

**Comment by djkapur** [comment] 2023-07-27 11:33
Hello @v-sudhkarat, I'm working on it and will confirm you once done. Since it is Prod app, It will take some time as approval is required to do it.

**Comment by v-sudkharat** [comment] 2023-07-27 12:38
Hi @djkapur, ok let us know once you done. Thanks!

**Comment by v-sudkharat** [comment] 2023-08-02 10:17
Hi @djkapur, Gentle Reminder: We are waiting for your response on this issue. If you still need to keep this issue active, please respond on it in the next 2 days. If we don't receive response by 04-08-2023 date, we will be close this issue.

**Comment by djkapur** [comment] 2023-08-04 09:42
Hi @v-sudkharat, we are working on reinstalling function app. It's taking some time to get approval.

**Comment by v-sudkharat** [comment] 2023-08-04 09:56
Hello, @djkapur, ok let us know once you done. Thanks!

**Comment by 0ccupi3R** [comment] 2023-08-06 07:37
Hello @djkapur 

As suggested by @v-sudkharat , it might be good to consider reinstalling the app. However, there are some important aspects to consider:

Firstly, the `ws.settimeout(20)` configuration could lead to an automatic closure of the connection, so the error messages looks expected. During testing, I received the expected results using the same function app code. Hence, it's worth checking if any logs are available for the specified type - message.

## Successful Logs
```
Websocket connection established to cluster_id=*********, event_type=maillog
maillog 501
maillog 501
maillog 501
maillog 501
Error while receiving data1: Connection to remote host was lost.
Error while receiving data2: Connection to remote host was lost.
maillog
Total events sent: 2176. Type: maillog. Period(UTC): 2023-08-06T05:00:00.000000 - 2023-08-06T05:59:59.999999
Websocket connection established to cluster_id=*********, event_type=message
message 501
Error while receiving data1: Connection to remote host was lost.
Error while receiving data2: Connection to remote host was lost.
message
Total events sent: 848. Type: message. Period(UTC): 2023-08-06T05:00:00.000000 - 2023-08-06T05:59:59.999999
```


You can also try running the code only with `message` in below code.
https://github.com/Azure/Azure-Sentinel/blob/5856875ca52f9c43ed15cff3ccf906442a870505/Solutions/Proofpoint%20On%20demand(POD)%20Email%20Security/Data%20Connectors/ProofpointSentinelConnector/__init__.py#L24

## Trace Log Details
Upon examining the provided trace logs, it is evident that the events for the `message` log type do exist, indicating that your app is functioning correctly. However, it's still recommended to verify if there are any missing logs on Sentinel by comparing the data.

```
"6/12/2023, 5:02:50.881 PM",Total events sent: 46541. Type: maillog. Period(UTC): 2023-06-12T16:00:00.000000 - 2023-06-12T16:59:59.999999,1,trace,"{""InvocationId"":""d3c2ff88-cbee-442d-bfba-a1e471b49b38"",""Category"":""Function.ProofpointSentinelConnector.User"",""LogLevel"":""Information"",""HostInstanceId"":""103d3602-28d5-4d4d-bf0e-c2ca616ee12b"",""ProcessId"":""57""}",,ProofpointSentinelConnector,d8974c87e8c9164a895448a23f3f74e0,2f53706ce5d7b349,,,,,,,PC,,,0.0.0.0,,,,,proofpointmailnapfuncapp01,F6C34226-638221853294296477,293f6086-d8ef-4a71-94e4-b7cd1daef8b0,/subscriptions/xxxx/providers/microsoft.insights/components/sennapappinst01,116fab5c-777e-419e-b750-6b5ba7a3d4c6,azurefunctions: 3.19.2.0,0befb560-0943-11ee-a66a-000d3af56632,1,/subscriptions/xxxx/providers/microsoft.insights/components/sennapappinst01
"6/12/2023, 6:04:38.446 PM",Total events sent: 16651. Type: message. Period(UTC): 2023-06-12T17:00:00.000000 - 2023-06-12T17:59:59.999999,1,trace,"{""InvocationId"":""b65cd4fb-62f8-4e2f-9c7c-abb42544336b"",""Category"":""Function.ProofpointSentinelConnector.User"",""LogLevel"":""Information"",""HostInstanceId"":""f42b7030-9d27-48a6-a528-da79d86006f6"",""ProcessId"":""58""}",,ProofpointSentinelConnector,6acb1c8889e2f54f9925b61fc7a9e7d9,c0c6b2bba0055b47,,,,,,,PC,,,0.0.0.0,,,,,proofpointmailnapfuncapp01,F6C34226-638221891350200237,293f6086-d8ef-4a71-94e4-b7cd1daef8b0,/subscriptions/xxxx/providers/microsoft.insights/components/sennapappinst01,116fab5c-777e-419e-b750-6b5ba7a3d4c6,azurefunctions: 3.19.2.0,d288c221-094b-11ee-a66c-000d3af5643d,1,/subscriptions/xxxx/providers/microsoft.insights/components/sennapappinst01
"6/12/2023, 6:04:38.637 PM",Total events sent: 41935. Type: maillog. Period(UTC): 2023-06-12T17:00:00.000000 - 2023-06-12T17:59:59.999999,1,trace,"{""Category"":""Host.Function.Console"",""LogLevel"":""Information"",""HostInstanceId"":""f42b7030-9d27-48a6-a528-da79d86006f6"",""ProcessId"":""58"",""prop__{OriginalFormat}"":""Total events sent: 41935. Type: maillog. Period(UTC): 2023-06-12T17:00:00.000000 - 2023-06-12T17:59:59.999999""}",,,,,,,,,,,PC,,,0.0.0.0,,,,,proofpointmailnapfuncapp01,F6C34226-638221891350200237,293f6086-d8ef-4a71-94e4-b7cd1daef8b0,/subscriptions/xxxx/providers/microsoft.insights/components/sennapappinst01,116fab5c-777e-419e-b750-6b5ba7a3d4c6,azurefunctions: 3.19.2.0,d288c4eb-094b-11ee-a66c-000d3af5643d,1,/subscriptions/xxxx/providers/microsoft.insights/components/sennapappinst01
"6/12/2023, 6:04:38.703 PM",Total events sent: 16651. Type: message. Period(UTC): 2023-06-12T17:00:00.000000 - 2023-06-12T17:59:59.999999,1,trace,"{""Category"":""Host.Function.Console"",""LogLevel"":""Information"",""HostInstanceId"":""f42b7030-9d27-48a6-a528-da79d86006f6"",""ProcessId"":""58"",""prop__{OriginalFormat}"":""Total events sent: 16651. Type: message. Period(UTC): 2023-06-12T17:00:00.000000 - 2023-06-12T17:59:59.999999""}",,,,,,,,,,,PC,,,0.0.0.0,,,,,proofpointmailnapfuncapp01,F6C34226-638221891350200237,293f6086-d8ef-4a71-94e4-b7cd1daef8b0,/subscriptions/xxxx/providers/microsoft.insights/components/sennapappinst01,116fab5c-777e-419e-b750-6b5ba7a3d4c6,azurefunctions: 3.19.2.0,d288c605-094b-11ee-a66c-000d3af5643d,1,/subscriptions/xxxx/providers/microsoft.insights/components/sennapappinst01
"6/12/2023, 7:04:54.913 PM",Total events sent: 16345. Type: message. Period(UTC): 2023-06-12T18:00:00.000000 - 2023-06-12T18:59:59.999999,1,trace,"{""InvocationId"":""0ea3b0ad-53ca-4764-a5f8-c984932c3f36"",""Category"":""Function.ProofpointSentinelConnector.User"",""LogLevel"":""Information"",""HostInstanceId"":""527e42da-27b3-4e6a-846b-8cf55a4da2ef"",""ProcessId"":""58""}",,ProofpointSentinelConnector,9f3875dbcde57f4e9528e1a2a7a58282,f1131c5041dd704a,,,,,,,PC,,,0.0.0.0,,,,,proofpointmailnapfuncapp01,F6C34226-638221916150722145,293f6086-d8ef-4a71-94e4-b7cd1daef8b0,/subscriptions/xxxx/providers/microsoft.insights/components/sennapappinst01,116fab5c-777e-419e-b750-6b5ba7a3d4c6,azurefunctions: 3.19.2.0,37057f4e-0954-11ee-a66c-002248775efa,1,/subscriptions/xxxx/providers/microsoft.insights/components/sennapappinst01
"6/12/2023, 7:04:55.015 PM",Total events sent: 36114. Type: maillog. Period(UTC): 2023-06-12T18:00:00.000000 - 2023-06-12T18:59:59.999999,1,trace,"{""Category"":""Host.Function.Console"",""LogLevel"":""Information"",""HostInstanceId"":""527e42da-27b3-4e6a-846b-8cf55a4da2ef"",""ProcessId"":""58"",""prop__{OriginalFormat}"":""Total events sent: 36114. Type: maillog. Period(UTC): 2023-06-12T18:00:00.000000 - 2023-06-12T18:59:59.999999""}",,,,,,,,,,,PC,,,0.0.0.0,,,,,proofpointmailnapfuncapp01,F6C34226-638221916150722145,293f6086-d8ef-4a71-94e4-b7cd1daef8b0,/subscriptions/xxxx/providers/microsoft.insights/components/sennapappinst01,116fab5c-777e-419e-b750-6b5ba7a3d4c6,azurefunctions: 3.19.2.0,3705812d-0954-11ee-a66c-002248775efa,1,/subscriptions/xxxx/providers/microsoft.insights/components/sennapappinst01
"6/12/2023, 7:04:55.049 PM",Total events sent: 16345. Type: message. Period(UTC): 2023-06-12T18:00:00.000000 - 2023-06-12T18:59:59.999999,1,trace,"{""Category"":""Host.Function.Console"",""LogLevel"":""Information"",""HostInstanceId"":""527e42da-27b3-4e6a-846b-8cf55a4da2ef"",""ProcessId"":""58"",""prop__{OriginalFormat}"":""Total events sent: 16345. Type: message. Period(UTC): 2023-06-12T18:00:00.000000 - 2023-06-12T18:59:59.999999""}",,,,,,,,,,,PC,,,0.0.0.0,,,,,proofpointmailnapfuncapp01,F6C34226-638221916150722145,293f6086-d8ef-4a71-94e4-b7cd1daef8b0,/subscriptions/xxxx/providers/microsoft.insights/components/sennapappinst01,116fab5c-777e-419e-b750-6b5ba7a3d4c6,azurefunctions: 3.19.2.0,37058233-0954-11ee-a66c-002248775efa,1,/subscriptions/xxxx/providers/microsoft.insights/components/sennapappinst01
"6/12/2023, 4:02:49.086 PM",Total events sent: 44251. Type: maillog. Period(UTC): 2023-06-12T15:00:00.000000 - 2023-06-12T15:59:59.999999,1,trace,"{""InvocationId"":""ca5d90e8-f51c-4df9-8bc0-bc4c5d829cd2"",""Category"":""Function.ProofpointSentinelConnector.User"",""LogLevel"":""Information"",""HostInstanceId"":""dfac81b1-f97c-45dd-9b98-98db00d5ff86"",""ProcessId"":""55""}",,ProofpointSentinelConnector,87b79d7adfa086479a315c8425a6574d,1cf5e26b62cd1d49,,,,,,,PC,,,0.0.0.0,,,,,proofpointmailnapfuncapp01,F6C34226-638221817381674936,293f6086-d8ef-4a71-94e4-b7cd1daef8b0,/subscriptions/xxxx/providers/microsoft.insights/components/sennapappinst01,116fab5c-777e-419e-b750-6b5ba7a3d4c6,azurefunctions: 3.19.2.0,c4c2e891-093a-11ee-a66a-002248775e53,1,/subscriptions/xxxx/providers/microsoft.insights/components/sennapappinst01
"6/12/2023, 4:04:34.262 PM",Total events sent: 17051. Type: message. Period(UTC): 2023-06-12T15:00:00.000000 - 2023-06-12T15:59:59.999999,1,trace,"{""InvocationId"":""ca5d90e8-f51c-4df9-8bc0-bc4c5d829cd2"",""Category"":""Function.ProofpointSentinelConnector.User"",""LogLevel"":""Information"",""HostInstanceId"":""dfac81b1-f97c-45dd-9b98-98db00d5ff86"",""ProcessId"":""55""}",,ProofpointSentinelConnector,87b79d7adfa086479a315c8425a6574d,1cf5e26b62cd1d49,,,,,,,PC,,,0.0.0.0,,,,,proofpointmailnapfuncapp01,F6C34226-638221817381674936,293f6086-d8ef-4a71-94e4-b7cd1daef8b0,/subscriptions/xxxx/providers/microsoft.insights/components/sennapappinst01,116fab5c-777e-419e-b750-6b5ba7a3d4c6,azurefunctions: 3.19.2.0,011f5245-093b-11ee-a66c-000d3ac66bb5,1,/subscriptions/xxxx/providers/microsoft.insights/components/sennapappinst01
"6/12/2023, 4:04:34.494 PM",Total events sent: 44251. Type: maillog. Period(UTC): 2023-06-12T15:00:00.000000 - 2023-06-12T15:59:59.999999,1,trace,"{""Category"":""Host.Function.Console"",""LogLevel"":""Information"",""HostInstanceId"":""dfac81b1-f97c-45dd-9b98-98db00d5ff86"",""ProcessId"":""55"",""prop__{OriginalFormat}"":""Total events sent: 44251. Type: maillog. Period(UTC): 2023-06-12T15:00:00.000000 - 2023-06-12T15:59:59.999999""}",,,,,,,,,,,PC,,,0.0.0.0,,,,,proofpointmailnapfuncapp01,F6C34226-638221817381674936,293f6086-d8ef-4a71-94e4-b7cd1daef8b0,/subscriptions/xxxx/providers/microsoft.insights/components/sennapappinst01,116fab5c-777e-419e-b750-6b5ba7a3d4c6,azurefunctions: 3.19.2.0,011f55ee-093b-11ee-a66c-000d3ac66bb5,1,/subscriptions/xxxx/providers/microsoft.insights/components/sennapappinst01
"6/12/2023, 4:04:34.585 PM",Total events sent: 17051. Type: message. Period(UTC): 2023-06-12T15:00:00.000000 - 2023-06-12T15:59:59.999999,1,trace,"{""Category"":""Host.Function.Console"",""LogLevel"":""Information"",""HostInstanceId"":""dfac81b1-f97c-45dd-9b98-98db00d5ff86"",""ProcessId"":""55"",""prop__{OriginalFormat}"":""Total events sent: 17051. Type: message. Period(UTC): 2023-06-12T15:00:00.000000 - 2023-06-12T15:59:59.999999""}",,,,,,,,,,,PC,,,0.0.0.0,,,,,proofpointmailnapfuncapp01,F6C34226-638221817381674936,293f6086-d8ef-4a71-94e4-b7cd1daef8b0,/subscriptions/xxxx/providers/microsoft.insights/components/sennapappinst01,116fab5c-777e-419e-b750-6b5ba7a3d4c6,azurefunctions: 3.19.2.0,011f571c-093b-11ee-a66c-000d3ac66bb5,1,/subscriptions/xxxx/providers/microsoft.insights/components/sennapappinst01
"6/12/2023, 9:05:00.481 PM",Total events sent: 23419. Type: message. Period(UTC): 2023-06-12T20:00:00.000000 - 2023-06-12T20:59:59.999999,1,trace,"{""InvocationId"":""be9dee76-5443-44aa-8a91-dbeefa522c26"",""Category"":""Function.ProofpointSentinelConnector.User"",""LogLevel"":""Information"",""HostInstanceId"":""4e3e7f61-1b79-49bc-a9d3-07f140ae2c89"",""ProcessId"":""56""}",,ProofpointSentinelConnector,ec0b86b3c171e64d959e14decdb679f1,6e7cd7edbf3e1c4d,,,,,,,PC,,,0.0.0.0,,,,,proofpointmailnapfuncapp01,F6C34226-638221988187306568,293f6086-d8ef-4a71-94e4-b7cd1daef8b0,/subscriptions/xxxx/providers/microsoft.insights/components/sennapappinst01,116fab5c-777e-419e-b750-6b5ba7a3d4c6,azurefunctions: 3.19.2.0,e3f474f1-0964-11ee-a66a-002248775e53,1,/subscriptions/xxxx/providers/microsoft.insights/components/sennapappinst01
```

**Comment by v-sudkharat** [comment] 2023-08-09 09:53
Hi @djkapur, could you please let us know if previous comment helped you in resolving issue? Let us know you need any further assistance. Thanks!

**Comment by v-sudkharat** [comment] 2023-08-17 06:13
Hi @djkapur, Gentle Reminder: We are waiting for your response on this issue. If you still need to keep this issue active, please respond on it in the next 2 days. If we don't receive response by 22-08-2023 date, we will be close this issue. Thanks!

**Comment by v-sudkharat** [comment] 2023-08-22 09:05
Hi @djkapur, since we have not received a response in the last 5 days, we are closing your issue as per our standard operating procedures. If you still need support for this issue, feel free to re-open at any time. Thank you for your co-operation.

**Comment by v-sudkharat** [comment] 2023-08-22 09:05
Hi @djkapur, since we have not received a response in the last 5 days, we are closing your issue as per our standard operating procedures. If you still need support for this issue, feel free to re-open at any time. Thank you for your co-operation.

**Closed by v-sudkharat** 2023-08-22 09:05 UTC
Labels: Function
