### ISSUE TITLE
exportAzureSentinelRules.ps1 stopped working

### ISSUE THREAD

**Issue by sukster** [Azure/Azure-Sentinel#2413] opened 2021-06-07 08:27 UTC
**Describe the bug**
This script stopped working for us couple of days ago and is now returning this error.

WARNING: Either your Azure connection is invalid or your Azure Sentinel settings are incorrect
WARNING: Your Azure credentials have not been set up or have expired, please run Connect-AzAccount to set up your Azure
 credentials.

We did the Connect-AzAccount and Set-AzContext which worked fine. But still after this script is returning this error:

WARNING: Either your Azure connection is invalid or your Azure Sentinel settings are incorrect
WARNING: Internal server error

@tianderturpijn could you please try to use this script on your end to see if you are getting the same error as well?

Thanks, Ludek

**To Reproduce**
1. Run the Export script as per documentation in Readme.

**Expected behavior**
The script should export the analytic rules.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10 Enterprise Version 20H2 (OS Build 19042.985)
- Powershell: version 5.1.19041.906

**Additional context**

**Comment by tianderturpijn** [comment] 2021-06-11 12:30
@sukster , Ludek, I ran this script on a fresh installed Windows 10 Enterprise Version 20H2, using the latest Az.SecurityInsights module version 1.0.0 without any issues and cannot reproduce your issue. Are you sure your settings are correct?

**Comment by tianderturpijn** [comment] 2021-06-14 08:11
Closing this issue, not able to reproduce the error.

**Closed by tianderturpijn** 2021-06-14 08:11 UTC

**Comment by sukster** [comment] 2021-06-14 08:32
@tianderturpijn thank you for looking at this. I have to apologize. I was getting this error due to some new policy restrictions which were implemented in our company and I wasn't aware of them. When I used non-company workstation everything worked. My apologized again! Ludek

**Comment by tianderturpijn** [comment] 2021-06-14 08:34
@sukster  No worries Ludek, thanks for letting us know!
