### ISSUE TITLE
GWorkspaceReportsAPISentinelConnector - lacking 'login' activity from Workspace in Sentinel

### ISSUE THREAD

**Issue by Matias117** [Azure/Azure-Sentinel#7097] opened 2023-01-13 15:58 UTC
**Describe the bug**
Google Workspace connector for Sentinel seems not to populate the table connected with login activity properly. Only events that are present are  '2sv_enroll' and 'password_edit', other events are not loaded into the table. In Application Insights, the connector properly logs 'processing login activity - N events', where N is usually 0 (not counting 2 mentioned event types).

**To Reproduce**
1. Deploy the connector according to the provided instructions
2. Wait some time for the data to populate
3. In Sentinel Log Analytics check the table 'GWorkspace_ReportsAPI_login'
4. Only events that show in logs are those with event_name_s '2sv_enroll' and 'password_edit' (lacking for example 'login_success', 'login_failure', 'logout', 'login_verification', etc.)
5. The lacking events are still present and visible in Workspace Admin console

**Expected behavior**
All the events should be present in 'GWorkspace_ReportsAPI_login' table in Log Analytics.

**Additional context**
The problem is present for over 2-3 months.
After some analysis, our team suspects Workspace lag times to be responsible for the problem, but it's just our guess (https://support.google.com/a/answer/7061566?hl=en) and would need a confirmation.

**Comment by tomkeatingcroud** [comment] 2023-02-15 15:30
Also having the same issue in our workspace and similar issues around other Google Workspace logs (missing logs in Google Meet / Google Chat)

**Comment by tomkeatingcroud** [comment] 2023-03-21 09:50
Hi Team, is this going to be fixed as currently the solution isn't very useful as it misses quite a few events and it doesn't have the ability to go back and get them, it does seem like the issue is related to the lag time in Workspace events appearing in the API output

**Comment by v-amolpatil** [comment] 2023-03-21 09:53
@tomkeatingcroud , we will take it on priority and let you know the updates soon. Thanks!

**Comment by Matias117** [comment] 2023-05-30 07:15
Hello Team, is there any update on the matter?

**Comment by v-vdixit** [comment] 2023-05-31 05:46
Hi @Matias117 Can you please provide execution logs for this, it will help us better understand the root cause, thanks!

**Comment by v-vdixit** [comment] 2023-06-05 10:00
Gentle Reminder: We are waiting for your response on this issue. If you still need to keep this issue active, please respond on it in the next 2 days. If we don't receive response, we will be closing this issue as per our standard procedures, thanks!

**Comment by Matias117** [comment] 2023-06-05 11:17
Hello, it is not the matter of execution logs, there is nothing there to be found, the function executes properly. I already described the problem in detail on Jan 13th, together with providing the cause of the problem in a form of lag times, that the function does not take into consideration at the moment (https://support.google.com/a/answer/7061566?hl=en).

**Comment by v-vdixit** [comment] 2023-06-05 12:56
Hi @Matias117 we were asking for execution logs to look for any error messages, warnings, or indications of issues related to populating the login activity table. The logs may provide valuable insights into the root cause of the problem.
Regarding the suspicion of Workspace lag times being the cause, it would be beneficial to seek confirmation from the Google Workspace support team or documentation. They can provide insights into any potential delays in log availability and help determine if it aligns with the observed behavior. Thanks!

**Comment by Matias117** [comment] 2023-06-06 10:40
As I have already mentioned, the function executes properly. There is no sign of any error messages, warnings, or indications of issues related to populating the login activity table.
I provided you with a link to a Goole Support, containing information about the root cause of the issue - did you manage to open the link and read the contents?
The table is not getting populated, because logs are getting filtered based on time the original event is generated, and not by the time it is available to get using API. All the details needed to reproduce the problem are in my initial description of the issue. Have you tried reproducing it?

**Comment by v-vdixit** [comment] 2023-06-06 12:10
Hi @Matias117 we did follow the steps to reproduce it. However, at the moment, we do not have access to the necessary credentials (pickle string) required for testing and validating the issue further. As a result, we are unable to observe successful results after the deployment of the function app. Nevertheless, we are actively collaborating with the team to trace the root cause by debugging and investigating the situation. Our goal is to ensure that any necessary modifications or adjustments, if required, are implemented from our end to address the issue effectively.
We appreciate your understanding and patience as we work towards resolving this matter. If you have any additional insights or suggestions, please feel free to share them with us.

**Comment by tomkeatingcroud** [comment] 2023-06-09 11:58
We are having the same issue. Our login table has a few entries but hardly anything compared to the official google audit logs.
I manually altered the function to sync every 20 minutes which is how we got anything into the table in the first place, but I feel it might need to be longer due to the lag time between the event and the API showing logs. It would be good if the function could be updated with a custom timeframe parameter, as well as being able to overlap refreshes to pull in missing data (without creating duplicates in the log table). I'm going to further increase this to 30 minutes to see if it has a positive effect.

**Comment by v-vdixit** [comment] 2023-06-09 12:35
Hi @tomkeatingcroud thanks for your update, we are investigating this with the team and the insights you have provided will be helpful for us in our analysis, we will update you shortly, thanks!

**Comment by tomkeatingcroud** [comment] 2023-06-14 10:28
So I've just updated to the latest reports and data connector (these now seem to come with customisable delays for different logs), however, now the function crashes when attempting to sync drive logs (I get the following error):

Microsoft.Azure.WebJobs.Host.FunctionInvocationException: Exception while executing function: Functions.GWorkspaceReportsAPISentinelConnector
 ---> Microsoft.Azure.WebJobs.Script.Workers.WorkerProcessExitException: python exited with code 137 (0x89)
 ---> System.Exception
   --- End of inner exception stack trace ---
   at Microsoft.Azure.WebJobs.Script.Description.WorkerFunctionInvoker.InvokeCore(Object[] parameters, FunctionInvocationContext context) in /src/azure-functions-host/src/WebJobs.Script/Description/Workers/WorkerFunctionInvoker.cs:line 101
   at Microsoft.Azure.WebJobs.Script.Description.FunctionInvokerBase.Invoke(Object[] parameters) in /src/azure-functions-host/src/WebJobs.Script/Description/FunctionInvokerBase.cs:line 82
   at Microsoft.Azure.WebJobs.Host.Executors.VoidTaskMethodInvoker`2.InvokeAsync(TReflected instance, Object[] arguments) in D:\a\_work\1\s\src\Microsoft.Azure.WebJobs.Host\Executors\VoidTaskMethodInvoker.cs:line 20
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionInvoker`2.InvokeAsync(Object instance, Object[] arguments) in D:\a\_work\1\s\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionInvoker.cs:line 52
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.InvokeWithTimeoutAsync(IFunctionInvoker invoker, ParameterHelper parameterHelper, CancellationTokenSource timeoutTokenSource, CancellationTokenSource functionCancellationTokenSource, Boolean throwOnTimeout, TimeSpan timerInterval, IFunctionInstance instance) in D:\a\_work\1\s\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 581
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithWatchersAsync(IFunctionInstanceEx instance, ParameterHelper parameterHelper, ILogger logger, CancellationTokenSource functionCancellationTokenSource) in D:\a\_work\1\s\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 527
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithLoggingAsync(IFunctionInstanceEx instance, FunctionStartedMessage message, FunctionInstanceLogEntry instanceLogEntry, ParameterHelper parameterHelper, ILogger logger, CancellationToken cancellationToken) in D:\a\_work\1\s\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 306
   --- End of inner exception stack trace ---
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithLoggingAsync(IFunctionInstanceEx instance, FunctionStartedMessage message, FunctionInstanceLogEntry instanceLogEntry, ParameterHelper parameterHelper, ILogger logger, CancellationToken cancellationToken) in D:\a\_work\1\s\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 352
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.TryExecuteAsync(IFunctionInstance functionInstance, CancellationToken cancellationToken) in D:\a\_work\1\s\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 108

**Comment by v-vdixit** [comment] 2023-06-21 12:57
Hi @tomkeatingcroud thanks for providing these details, we will discuss this with the team and update you.

**Comment by tomkeatingcroud** [comment] 2023-06-21 12:59
Just to update on things we've tried now:

Moved the function to a premium rather than consumption basis. This seems to fix that particular crash as the function doesn't run out of memory. However, the function now times out after 10 minutes running, we think due to the size of logs it is trying to pull in. The only way to override he function max execution time seems to be in the host.json

**Comment by v-vdixit** [comment] 2023-06-22 13:11
Hi @tomkeatingcroud currently the 'max execution time' in host.json is the default value for all customers using this connector, we cannot update and publish this from our end however, we would suggest you update this value as per your requirement for testing at your end if you need assistance with that process please let us know. Thanks!
Hi @Matias117 the lagging issue can be curbed by switching to premium plan for the function, thanks!

**Comment by v-vdixit** [comment] 2023-07-03 07:54
Since we have not received a response in the last 5 days, we are closing your issue as per our standard operating procedures. If you still need support for this issue, feel free to re-open at any time. Thank you for your co-operation

**Closed** 2023-07-03 07:54 UTC
Labels: Connector
