### ISSUE TITLE
Oracle Cloud Infrastructure - Azure Function Error

### ISSUE THREAD

**Issue by TestAccountIT** [Azure/Azure-Sentinel#8216] opened 2023-06-07 14:38 UTC
**Describe the bug**
After deployment of connector via Sentinel i'm getting this error message 

Result: Failure Exception: InvalidConfig: {'user': 'malformed'} Stack: File "/azure-functions-host/workers/python/3.8/LINUX/X64/azure_functions_worker/dispatcher.py", line 406, in _handle__invocation_request call_result = await self._loop.run_in_executor( File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run result = self.fn(*self.args, **self.kwargs) File "/azure-functions-host/workers/python/3.8/LINUX/X64/azure_functions_worker/dispatcher.py", line 648, in _run_sync_func return ExtensionManager.get_sync_invocation_wrapper(context, File "/azure-functions-host/workers/python/3.8/LINUX/X64/azure_functions_worker/extension.py", line 215, in _raw_invocation_wrapper result = function(**args) File "/home/site/wwwroot/AzureFunctionOCILogs/main.py", line 39, in main oci.config.validate_config(config) File "/home/site/wwwroot/.python_packages/lib/site-packages/oci/config.py", line 163, in validate_config raise InvalidConfig(errors)

**To Reproduce**
Go to Sentinel
Go to Data Connectors
Oracle Cloud Infrastructure > Provide all necessary details >Deploy 

**Expected behavior**
Get OCI stream logs 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Edge 
 - Version 114.0.1823.37

**Comment by v-vdixit** [comment] 2023-06-08 05:21
Hi @TestAccountIT the error message suggests that there is an issue with the configuration parameters provided for the Oracle Cloud Infrastructure (OCI) connector deployed via Azure Sentinel. 
To troubleshoot this issue, you can consider the following steps:
1) Verify the configuration: Double-check the configuration settings for the OCI connector, particularly the "user" parameter. Ensure that the value provided for the "user" parameter is in the correct format and matches the required format for OCI authentication.
2) Check access and permissions: Ensure that the credentials provided for the OCI user are valid and have sufficient permissions to access the required OCI resources. Verify that the user has the necessary roles and policies assigned to perform the required operations.
I hope this resolves your issue, thanks!

**Comment by v-vdixit** [comment] 2023-06-13 13:38
Gentle Reminder: We are waiting for your response on this issue. If you still need to keep this issue active, please respond on it in the next 2 days. If we don't receive response, we will be closing this issue as per our standard procedures, thanks!

**Comment by TestAccountIT** [comment] 2023-06-14 11:41
Hello,
Currently OCI user have read permissions, do you know what kind of permissions it should have ?

Thanks

**Comment by v-vdixit** [comment] 2023-06-15 09:13
Hi @TestAccountIT user needs to have read and write permissions in order to successfully execute the function app, although in this case the error is highlighting the credentials as being incorrect, so please ensure the correct credentials are being used by you, thanks!

**Comment by TestAccountIT** [comment] 2023-06-15 13:02
Hello, as you probably know there is just username required for this connector, so there is no password - Microsoft Sentinel Workspace Id, Microsoft Sentinel Shared Key, User, Key_content, Pass_phrase, Fingerprint, Tenancy, Region, Message Endpoint, Stream Ocid so are you able to point out, which one is not correct ?

**Comment by TestAccountIT** [comment] 2023-06-15 13:06
Also, what do you mean by "user needs to have read and write permissions in order to successfully execute the function app" not really sure what user is executing function for Sentinel... i was asking for permissions in OCI for the stream. We never set up any user in Sentinel/Function app to execute anything.

**Comment by v-vdixit** [comment] 2023-06-19 05:31
> uired for this connector, so there is no password - Microsoft Sentinel Workspace Id, Microsoft Sentinel Shared Key, User, Key_content, Pass_phrase, Fingerprint, Tenancy, Region, Message Endpoint, Stream Ocid so are you able to point out, which one is not correct

Hi @TestAccountIT according to the error message you pasted above, we can deduce that the User parameter configuration are not as expected here, if possible, please send us the execution logs for this so that we can troubleshoot and find the root cause of this error, thanks!

**Comment by TestAccountIT** [comment] 2023-06-19 11:34
Hello, what execution logs ? where can i find them ?

**Comment by v-vdixit** [comment] 2023-06-19 11:36
Hi @TestAccountIT Execution Logs as in the trace logs where this error and other execution steps were found by you, please add screenshot of same here, thanks!

**Comment by TestAccountIT** [comment] 2023-06-19 11:46
![OCI](https://github.com/Azure/Azure-Sentinel/assets/125910380/abe8d765-25d2-4339-b9e1-5a08c6747962)

**Comment by TestAccountIT** [comment] 2023-06-19 12:08
![OCI1](https://github.com/Azure/Azure-Sentinel/assets/125910380/31a7a3fa-3a24-4c3d-9ce0-96a89b78053f)
Screenshot attached

**Comment by v-vdixit** [comment] 2023-06-21 06:30
Hi @TestAccountIT thanks for sharing this, we will discuss with the team and update you shortly.

**Comment by v-vdixit** [comment] 2023-06-23 12:12
Hi @TestAccountIT The error message suggests that there is an issue with the configuration of the Oracle Cloud Infrastructure Azure Function deployment. The error message indicates that the configuration is malformed, please refer the below documentation to the given documentation - [Troubleshoot Azure Function Errors](https://github.com/MicrosoftDocs/azure-docs/blob/main/articles/azure-functions/recover-python-functions.md)

**Comment by TestAccountIT** [comment] 2023-06-23 12:17
Wow, there are a lot of informations ... which part should i use to troubleshoot ?

**Comment by TestAccountIT** [comment] 2023-06-23 12:23
Also there is nothing related to invalid config or user and multiple python scripts are mentioned in error.

**Comment by v-vdixit** [comment] 2023-06-23 12:34
> Wow, there are a lot of informations ... which part should i use to troubleshoot ?

Hi @TestAccountIT you can refer to the issues with deployment part of this documentation to check on the configuration settings, you can also check the logs of your Azure Function deployment to see if there are any additional error messages that can help you identify the issue. Thanks!

**Comment by v-vdixit** [comment] 2023-06-23 12:50
> Hello, there are no additional logs in Azure Function, each logs are the same. Also Issues with Deployment part : Issue with deployment In the [Azure portal](https://portal.azure.com/), select Settings > Configuration, and then ensure that the AzureWebJobsFeatureFlags application setting has a value of EnableWorkerIndexing. If it's not found, add this setting to the function app. ::: zone-end
> 
> Settings part where is Azure portal we have "settings", to which kind of setting this refer ? Are those Azure Function Settings ?

Hi, @TestAccountIT azure function configuration settings are being referred here, thanks!

**Comment by TestAccountIT** [comment] 2023-06-23 12:57
Ok thanks, so i've added this AzureWebJobsFeatureFlags with value EnableWorkerIndexing but i can't see any difference

**Comment by v-vdixit** [comment] 2023-06-26 11:25
Hi @TestAccountIT can you please try reinstalling the function app with this latest change, thanks!

**Comment by TestAccountIT** [comment] 2023-06-26 17:24
Hello, @v-vdixit after removing and re-deploying connector/function from Sentinel > Data Connectors and applying additional setting from guide there is still same error.

**Comment by v-vdixit** [comment] 2023-06-28 13:06
Hi @TestAccountIT we have checked with the team for this error, it looks like it's system specific, please ensure you have admin permissions for the resource you are using.
If you have all the required permissions and correct account credentials, please raise a support ticket with Microsoft, thanks!

**Comment by TestAccountIT** [comment] 2023-06-28 13:11
Hello @v-vdixit by resource you mean resource group in Azure right ?

**Comment by v-vdixit** [comment] 2023-06-30 07:11
> Hello @v-vdixit by resource you mean resource group in Azure right ?

Yes

**Comment by v-vdixit** [comment] 2023-07-05 07:23
Gentle Reminder: We are waiting for your response on this issue. If you still need to keep this issue active, please respond on it in the next 2 days. If we don't receive response, we will be closing this issue as per our standard procedures, thanks!

**Comment by v-vdixit** [comment] 2023-07-10 10:19
Since we have not received a response in the last 5 days, we are closing your issue as per our standard operating procedures. If you still need support for this issue, feel free to re-open at any time. Thank you for your co-operation

**Closed by v-vdixit** 2023-07-10 10:19 UTC
Labels: Connector

**Comment by PCNZ** [comment] 2023-09-06 00:25
@TestAccountIT was this ever resolved? We are seeing the same problem.
