### ISSUE TITLE
Log Analytics Autoparsing Fail Fortinet Connector

### ISSUE THREAD

**Issue by jeffrywu28** [Azure/Azure-Sentinel#8237] opened 2023-06-12 03:11 UTC
**Describe the bug**
The source is Fortinet firewall (on prem) and the VM is on-prem as well, as this is the best practices for Rsyslog server.
I want to create dashboard but found at field DestinationUserName the parsing is not right. it's should be only email only. 
The fortinet CEF log it should be like this : https://docs.fortinet.com/document/fortigate/7.0.10/fortios-log-message-reference/949981

**To Reproduce**
1. Go to 'Fortinet Connector'
2. Connect your forti
3. Doing Default parsing like  using "CommonSecurityLog"

**Expected behavior**
It should be email only not cutted email or contains "]"
**Screenshots**
![image](https://github.com/Azure/Azure-Sentinel/assets/47622164/fcb57aa5-c250-4020-a68b-9ed2933d900d)

**Fortigate
 - Version 7.0.9

**Comment by v-vdixit** [comment] 2023-06-14 09:18
Hi @jeffrywu28 thanks for flagging this, we have updated the concerned team with this issue, we will update you as soon as we hear back from them.

**Comment by v-vdixit** [comment] 2023-06-15 05:56
Hi @jeffrywu28 can you please provide us the details and full screenshots of the output logs you are getting, it will help us in tracing the root cause better, thanks!

**Comment by jeffrywu28** [comment] 2023-06-21 06:57
hi @v-vdixit, here 
![image](https://github.com/Azure/Azure-Sentinel/assets/47622164/52206be1-e7b5-4ab4-8952-757338dcdf9f)
Currently i'm open my ticket internally via Azure Security. My ticket number : 2305290030001765

**Comment by v-vdixit** [comment] 2023-06-22 05:11
Hi @jeffrywu28 thanks for the screenshots, we are looking for the raw data. The message that is being sent before data gets collected by the agent, can you please share this, thanks!

**Comment by v-vdixit** [comment] 2023-06-28 12:13
Gentle Reminder: We are waiting for your response on this issue. If you still need to keep this issue active, please respond on it in the next 2 days. If we don't receive response, we will be closing this issue as per our standard procedures, thanks!

**Comment by v-vdixit** [comment] 2023-06-30 09:27
Since we have not received a response in the last 5 days, we are closing your issue as per our standard operating procedures. If you still need support for this issue, feel free to re-open at any time. Thank you for your co-operation.

**Closed by v-vdixit** 2023-06-30 09:27 UTC
Labels: Connector
