### ISSUE TITLE
`NRT New access credential added to Application or Service Principal` cannot be deployed.

### ISSUE THREAD

**Issue by rweirtbg** [Azure/Azure-Sentinel#8188] opened 2023-06-02 08:26 UTC
**Describe the bug**

`NRT New access credential added to Application or Service Principal` cannot be deployed.

**To Reproduce**
1. Add new rule from template
2. Select `NRT New access credential added to Application or Service Principal`
3. See error on rule logic page.  `NRT queries cannot use joins or unions, or query more than one table.`

<img width="1493" alt="Screenshot 2023-06-02 at 4 22 22 AM" src="https://github.com/Azure/Azure-Sentinel/assets/111534841/4125048e-110c-40b8-a08b-6b986305dc03">

**Comment by v-vdixit** [comment] 2023-06-05 06:11
Hi @rweirtbg this query comes as a part of Azure Active Directory Solution, we have tried from our end and it's working successfully for us
![image](https://github.com/Azure/Azure-Sentinel/assets/115772287/a7f93aac-900e-4a96-8f45-768543b4ad3e)
Can you please check again and provide more details from logs about the error you are facing, thanks!

**Comment by v-rbajaj** [comment] 2023-06-12 13:46
Gentle Reminder: We are awaiting for your response on this issue. If you still need to keep this issue active please respond on it in the next 2 days. If we don't receive response, we will be close this issue.

**Comment by rweirtbg** [comment] 2023-06-12 17:09
Hi @v-vdixit ,

What logs are you looking for?

**Comment by v-vdixit** [comment] 2023-06-13 13:44
Hi @rweirtbg I am looking for the screenshot of the error you are facing with the query while running it in Log Analytics, so that we can analyze the issue and assist you better, thanks!

**Comment by rweirtbg** [comment] 2023-06-15 06:01
Hi @v-vdixit 

Here is the screenshot:

![Screenshot 2023-06-15 at 2 00 52 AM](https://github.com/Azure/Azure-Sentinel/assets/111534841/610e82dc-2217-45bf-a772-bb9423f5939f)

**Comment by v-vdixit** [comment] 2023-06-19 05:48
> Hi @v-vdixit
> 
> Here is the screenshot:
> 
> ![Screenshot 2023-06-15 at 2 00 52 AM](https://user-images.githubusercontent.com/111534841/246008359-610e82dc-2217-45bf-a772-bb9423f5939f.png)

Hi @rweirtbg as we can see here the query is working fine in Logs, it seems like the issue is specific to your system, can you please raise a Microsoft Support request for same, thanks!

**Comment by v-vdixit** [comment] 2023-06-21 08:42
Hi @rweirtbg we are closing this issue as it is specific to your system, if you need assistance with something else please feel free to reopen this, thanks!

**Closed by v-vdixit** 2023-06-21 08:42 UTC
Labels: Detection
