### ISSUE TITLE
Unable to deploy Azure Activity solution via ```az deployment group create```

### ISSUE THREAD

**Issue by sshockley** [Azure/Azure-Sentinel#10526] opened 2024-05-23 20:23 UTC
**Describe the bug**
Unable to fully deploy Azure Activity solution via ```az deployment group create```
When I do, it appears to succeed and creates most of the ojbects, but it doesn't show as "installed" in Content Hub and the Data Connection isn't created.

Installing from the Content Hub works correctly.  What am I missing?  I'm using Azure Government, but I don't think that matters here.

I have successfully deployed the UEBA Essentials and Microsoft 365 solutions with this method.

**To Reproduce**
1. Check out repo
2. Create parameter json file
3. Deploy using az

**Expected behavior**
Azure Activity is installed and configured

**Additional context**
I've created a parameter file named Azure-Activity.parameters.json:
```json
{
    "$schema": "https://schema.management.azure.com/schemas/2019-04-01/deploymentParameters.json#",
    "contentVersion": "1.0.0.0",
    "parameters": {
        "location": {
            "value": "usgovvirginia"
        },
        "workspace-location": {
            "value": "usgovvirginia"
        },
        "workspace": {
            "value": "workspacename"
        },
        "workbook1-name": {
            "value": "Azure Activity"
        }
    }
}
```

I'm running the command:
```
az deployment group create --name Azure-Activity --resource-group rg-redacted--parameters Aras/Azure-Activity.parameters.json --template-file "Solutions/Azure Activity/Package/mainTemplate.json"
```

Deploying from Content Hub creates two deployments, ```azuresentinel.azure-sentinel-solution-azureactivi-20240523153831``` and ```pid-1f6369a4-223e-4c86-808c-1d26a17c4def-partnercenter```.

If I export the deployments from the resource group, the ```Azure-Activity``` and ```azuresentinel.azure-[...]``` files look the same except for some lines that are reordered (but still are valid json).

The ```pid-1f6369a4-223e-4c86-808c-1d26a17c4def-partnercenter``` deployment seems to be pretty much empty.

Any suggestions what I'm doing wrong here?  Thanks!

**Comment by v-sudkharat** [comment] 2024-05-27 06:03
Hi @sshockley, Thanks for flagging this issue, we will investigate this issue and get back to you with some updates by 03-06-2024. Thanks!

**Comment by v-rusraut** [comment] 2024-06-07 05:54
Hi @sshockley,
We are working with respective team, we will update you.
Thanks

**Comment by v-rusraut** [comment] 2024-06-11 12:22
Hi @sshockley,We have tried to reproduce the issue, but we have successfully deployed the solution using azure cli, please try with below command. 

az deployment group create --name Azure-Activity --resource-group rg-redacted --parameters **"C:/New folder/parameters.json"** --template-file **"C:/Github/Azure-Sentinel/Solutions/Azure Activity/Package/mainTemplate.json"**

Please add correct path of parameters.json and mainTemplate.json

Thanks

**Comment by v-rusraut** [comment] 2024-06-17 05:42
Hi @sshockley,
Please work on above comment, we are waiting for response.
Thanks

**Comment by v-rusraut** [comment] 2024-06-21 05:19
Hi @sshockley , Gentle Reminder: We are waiting for your response on this issue. If you still need to keep this issue active, please respond to it in the next 2 days. If we don't receive a response by 24-06-2024 date, we will be closing this issue. 		
Thanks!

**Comment by v-rusraut** [comment] 2024-06-26 11:26
Hi @sshockley, since we have not received a response from you, we are closing this issue as per our standard operating procedures. If you still need support for this issue, feel free to re-open at any time. Thank you for your co-operation.

**Closed by v-rusraut** 2024-06-26 11:26 UTC
Labels: Connector, Solution
