### ISSUE TITLE
Imperva function app error

### ISSUE THREAD

**Issue by Tajinder4477** [Azure/Azure-Sentinel#9133] opened 2023-10-03 00:28 UTC
We are getting below error on imperva function app
Could not find index file. Response code is 404

**Comment by v-sudkharat** [comment] 2023-10-03 09:28
Hi @Tajinder4477, thanks for flagging this issue, we will soon get back to you on this. Thanks!

**Comment by v-sudkharat** [comment] 2023-10-04 09:16
Hi @Tajinder4477, could you please share the invocation logs with us? so we can check the issue. Thanks!

**Comment by v-sudkharat** [comment] 2023-10-06 04:57
Hi @Tajinder4477, we are waiting for your response. Thanks!

**Comment by Tajinder4477** [comment] 2023-10-06 06:23
![image](https://github.com/Azure/Azure-Sentinel/assets/146788871/9e7c2c1c-eea1-4c55-a373-96e3e2e89449)
[imperva log stream.txt](https://github.com/Azure/Azure-Sentinel/files/12827620/imperva.log.stream.txt)

**Comment by Tajinder4477** [comment] 2023-10-06 06:23
Please check the logs

**Comment by v-sudkharat** [comment] 2023-10-06 12:50
Hi @Tajinder4477, thanks for sharing logs with us, we are investigating this issue, we will get back to you on this. Thanks!

**Comment by v-sudkharat** [comment] 2023-10-09 13:15
Hi @Tajinder4477, just want to know, have you entered the correct values while deploying the function app in below highlighted fileds? 
![image](https://github.com/Azure/Azure-Sentinel/assets/132428394/84a74f83-ec8b-426e-97bc-8e52cd7d88c9)

and After deployment of function app, please also check correct values field in `EnvironmentVariables` and restart the function app. 
![image](https://github.com/Azure/Azure-Sentinel/assets/132428394/22e60242-fdea-47da-b442-366d0be9ac44)

Kindly let us know the issue is still exist. Thanks!

**Comment by Tajinder4477** [comment] 2023-10-09 21:46
Hi Team,

The key value is correct but still getting same error. below is the screenshot.
![image](https://github.com/Azure/Azure-Sentinel/assets/146788871/3880b828-b6d5-4638-9050-d935c27cd3e3)

**Comment by v-sudkharat** [comment] 2023-10-10 13:04
Hi @Tajinder4477, Thanks for sharing details with us, we are checking this issue, and we will update you by 13-10-2023. Thanks!

**Comment by v-sudkharat** [comment] 2023-10-11 09:51
Hi @Tajinder4477, based on the function app error message, could you please check in `ImpervaLogServerURI `the `logs.index` is there. 
![image](https://github.com/Azure/Azure-Sentinel/assets/132428394/4e8dfc78-5b1b-4893-a4ac-bb8fba228f40)

please refer below link and screenshot for reference - 
`https://docs.imperva.com/bundle/cloud-application-security/page/settings/log-integration.htm`

![image](https://github.com/Azure/Azure-Sentinel/assets/132428394/91b49a55-8492-4a81-8529-428f0086d699)

Thanks!

**Comment by Tajinder4477** [comment] 2023-10-11 22:10
I have added log.index but still getting same error.
![image](https://github.com/Azure/Azure-Sentinel/assets/146788871/ed8fa09b-2a84-433c-a1b2-1957fade3ed0)

**Comment by v-sudkharat** [comment] 2023-10-12 10:43
> I have added log.index but still getting same error. ![image](https://user-images.githubusercontent.com/146788871/274429889-ed8fa09b-2a84-433c-a1b2-1957fade3ed0.png)

You have added the "ImpervaLogServerURI", but have you restarted the fuction app? If not, please restart the function app and let us know still facing the same issue. 
![image](https://github.com/Azure/Azure-Sentinel/assets/132428394/08a01fc5-2cfe-4513-9f2e-abc2f8001399)

Thanks!

**Comment by Tajinder4477** [comment] 2023-10-12 21:07
Hi Team,

Yes I have restarted the Function app but still the issue not resolved.

Regards,
Tajinder Singh
SIEM/Sentinel
Group Digital, Technology & Business Services
+91 9466444477
Shift timings: • 2:00 AM-11:30 AM IST, Mon – Fri
Leave alert: None
Asahi Beverages: ***@***.******@***.***>
Global Asahi : ***@***.******@***.***>
_______________________________________________________________________________________________
Asahi Beverages
asahi.com.au<https://asahi.com.au/>

[signature_1661977433]<https://asahi.com.au/>

**Comment by v-sudkharat** [comment] 2023-10-13 13:16
Hi @Tajinder4477, we are working on reproducing this issue, and we'll let you know by 19-10-2023 Thanks!

**Comment by v-sudkharat** [comment] 2023-10-18 06:43
Hi @Tajinder4477, hope you are doing well, just want to know, you have any demo account for Imperva? if yes, is it possible for you to share the credentials with us? it would be really helpful for us to troubleshoot the connector. Thanks!

**Comment by v-sudkharat** [comment] 2023-10-18 08:53
> I have added log.index but still getting same error. ![image](https://user-images.githubusercontent.com/146788871/274429889-ed8fa09b-2a84-433c-a1b2-1957fade3ed0.png)

Hi @Tajinder4477, I see that you added the complete URL, please refer the below screenshot and update the URL. 
After that restart the function app. 
Please let us know if still facing same issue. Thanks!
![image](https://github.com/Azure/Azure-Sentinel/assets/132428394/79b62e74-4058-4ff1-a1c5-03dd96b77077)

**Comment by v-sudkharat** [comment] 2023-10-20 09:12
Hi @Tajinder4477, we are waiting for your response on above comment. Thanks!

**Comment by Tajinder4477** [comment] 2023-10-20 09:13
It’s working now.

Thanks

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by v-sudkharat** [comment] 2023-10-20 09:19
@Tajinder4477, Thank you for confirmation. 
Closing this issue. If you still need support for this issue, feel free to re-open it any time. Thank you for your co-operation.

**Closed by v-sudkharat** 2023-10-20 09:19 UTC
Labels: Function
