### ISSUE TITLE
Parse-kv - DCR transformation error

### ISSUE THREAD

**Issue by FormindMPO** [Azure/Azure-Sentinel#9792] opened 2024-01-19 16:38 UTC
**Describe the bug**
I'm having issues with the parse-kv module when it comes to transform in a DCR.

**To Reproduce**
1. Create a `parse-kv` operation over a table in Azure Log Analytics
2. Make it work
3. Try to push this to the `transform` module in a DCR

**Expected behavior**

Apply the same result as in Log Analytics

**Screenshots**

![image](https://github.com/MicrosoftDocs/azure-docs/assets/127124531/b9734f94-5bdc-4476-bb74-ea1648d2ca2d)

![image](https://github.com/MicrosoftDocs/azure-docs/assets/127124531/05892c11-efbd-49b8-8a05-c9f258f21248)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Mozilla Firefox
 - Version 121.0.1

**Additional context**

If we look more closely to the `parse` and `parse-kv` modules, it seems that the DCR is mistaken the `parse-kv` and the `parse` module. 
It asks for a `parse-kv RawData with` or so, but not using `as` and hence creating this error.

Could someone help me to fix this ?
Thank you !
See also
- [parse-kv doc](https://learn.microsoft.com/en-us/azure/data-explorer/kusto/query/parse-kv-operator#specified-delimeter)
- [parse doc](https://learn.microsoft.com/en-us/azure/data-explorer/kusto/query/parse-operator#regex-mode)

**Comment by v-sudkharat** [comment] 2024-01-22 07:42
Hi @FormindMPO, Thanks for flagging this issue, we will investigate this issue and get back to you with some updates by 25-01-2024. 
Additionally, we want to know is there any sentinel solution you are getting this issue. Thanks!

**Comment by FormindMPO** [comment] 2024-01-22 14:42
Following this issue, I moved to regex for temporary fix, I've encountered this error which clearly proves that the `parse-kv` module doesn't exists in DCRs :
![image](https://github.com/Azure/Azure-Sentinel/assets/127124531/9b5f7427-052f-46b0-a928-67f9c0cae5a1)
> *We only have the parse function available...* 

___
Moreover, I was using the **mv-expand** [function](https://learn.microsoft.com/en-us/azure/data-explorer/kusto/query/mv-expand-operator), but as you can see on the image, on the same line as parse, it uses `mvexpand` instead of the `mv-expand` (another problem).

**Comment by FormindMPO** [comment] 2024-01-22 16:35
![image](https://github.com/Azure/Azure-Sentinel/assets/127124531/bd3faac7-4ccc-4d2c-be73-ca401e3b6625)
Nothing is up to date ...
We can't use the methods defined in the official documentation, we have to work around with old methods, please fix soon :(

**Comment by FormindMPO** [comment] 2024-01-23 09:18
I'm experiencing a new issue, because the DCR parsing seems to be in "legacy" mode whereas the Logs console is up to date
___
When trying to parse a Squid Table, I'm using this kql :
```kql
Squid_CL 
| parse RawData with * " squid squid_access: " EpochTimeExtended " " Duration " " SrcIpAddr " " ResultStatusCode " " Bytes " " HttpRequestMethod " " Url " " Username " " PeerStatusHost " " ContentType 
| parse ResultStatusCode with ResultCode "/" StatusCode 
| parse PeerStatusHost with PeerHost "/" StatusHost 
| extend EventEpochTime = tolong(replace(@"\.","",EpochTimeExtended)) 
| extend TimeGenerated = datetime(1970-01-01) + tolong(EventEpochTime/1000) * 1sec 
| project-away RawData, EventEpochTime, EpochTimeExtended
```

Which works perfectly in the Logs Console, and creates this table :

![image](https://github.com/Azure/Azure-Sentinel/assets/127124531/82643e4a-9fa1-4577-bbf7-3fc333bfcc28)
___
But, when it comes to DCRs, as it uses some "legacy" functions, everything breaks...

![image](https://github.com/Azure/Azure-Sentinel/assets/127124531/c724ab8f-57af-405c-9ccc-877a02122166)

It's quite hard to debug as I don't have access to a "legacy" console and I can't reproduce this weird parsing :(

**Comment by v-muuppugund** [comment] 2024-01-23 11:52
Hi @FormindMPO ,Will check on the above issues and get back to you with an update.

**Comment by v-muuppugund** [comment] 2024-01-27 09:37
Hi @FormindMPO ,yes the transformation doesn't support **parse-kv** and went in detail, The below are supported for table operators in transformations

- extend
- project
- print
- where
- parse
- project-away
- project-rename
- datatable
- columnifexists

Please find more details on the below documentation
https://learn.microsoft.com/en-us/azure/azure-monitor/essentials/data-collection-transformations-structure

**Comment by v-muuppugund** [comment] 2024-01-29 15:34
> Ok fine, we'll have to deal with Thank you @v-muuppugund !
> 
> However, i'm still having an issue that i can't reproduce Using a DCR to collect Squid logs, i can successfully parse my data like shown in the message above [#9792 (comment)](https://github.com/Azure/Azure-Sentinel/issues/9792#issuecomment-1905625441) But when i set this query in the transform module, it breaks, as a result of not parsing the data as in the `Log analytics` module What makes this happen ? How could I check that the DCR parse my data as in Log analytics ? (like some of a DCR - console¿)

Hi @FormindMPO ,Will try to reproduce this squid proxy query issue  and will let you know,mean while could you please reproduce the issue.

**Comment by FormindMPO** [comment] 2024-02-01 16:56
Started, will tell you soon

**Comment by FormindMPO** [comment] 2024-02-02 10:13
Hi @v-muuppugund 
Still broken :(

- Parsed table using DCR (broken):
![image](https://github.com/Azure/Azure-Sentinel/assets/127124531/9c03b4b4-d914-4154-8619-cf2fe3160db8)

- My DCR : 
![image](https://github.com/Azure/Azure-Sentinel/assets/127124531/eecfd0f8-311b-4f20-8b09-f437e6b227fd)


- Expected data (this is the same query as in transform, but using flat RawData - line 12)
![image](https://github.com/Azure/Azure-Sentinel/assets/127124531/27a9c91f-b4d0-41e4-b4b2-c0cf64a90401)

I can fix this in my analytics rules :
1. Disable transformation in DCR (flat Rawdata)
2. Use a custom function `Proxy`
  ![image](https://github.com/Azure/Azure-Sentinel/assets/127124531/be058896-1bd6-4d27-bd2c-1d0886ac03da)
3. And then call `Proxy` in my kql

But this is what the transform module is supposed to do...

> //PS : here the query :
Squid_CL 
| parse RawData with * " squid squid_access: " EpochTimeExtended " " Duration " " SrcIpAddr " " ResultStatusCode " " Bytes " " HttpRequestMethod " " Url " " Username " " PeerStatusHost " " ContentType 
| parse ResultStatusCode with ResultCode "/" StatusCode 
| parse PeerStatusHost with PeerHost "/" StatusHost 
| extend EventEpochTime = tolong(replace(@"\.","",EpochTimeExtended)) 
| extend TimeGenerated = datetime(1970-01-01) + tolong(EventEpochTime/1000) * 1sec 
| project-away RawData, EventEpochTime, EpochTimeExtended

**Comment by v-muuppugund** [comment] 2024-02-02 11:24
Hi @FormindMPO , unable to replicate the issue,asked to replicate the steps,so we can figure out the exact problem,got it,will check on the issue and keep you posted

**Comment by FormindMPO** [comment] 2024-02-06 10:43
Hello @v-muuppugund, I actually managed to reproduce this issue, don't know why the parsing is not done the same way

**Comment by v-muuppugund** [comment] 2024-02-07 02:36
Hi @FormindMPO ,got the issue,need some more time for further analysis,as its handled in DCR transformation and its not supported during transformation

**Comment by v-muuppugund** [comment] 2024-02-11 09:35
Hi @FormindMPO , Its not supported during transformation itself and need to do apply custom logic as above, parsing is not happening ,Will do some more analysis why parsing is not applied the same way and if needed we can have a teams call for the same.

**Comment by FormindMPO** [comment] 2024-02-12 08:34
Hey @v-muuppugund, thank you for you time, sure we can have a Teams call if needed.

**Comment by v-muuppugund** [comment] 2024-02-16 10:43
Noted @FormindMPO ,Could you please share email id and convenient time slots for a teams meeting.

**Comment by v-muuppugund** [comment] 2024-02-18 16:08
Hi @FormindMPO ,As discussed over email,blocked your calendar on wednesday,please join the meeting.

**Comment by v-muuppugund** [comment] 2024-02-22 03:29
Hi @FormindMPO ,As discussed over call yesterday, discussed in detail about second issue i.e. Squid proxy parsing in transformation is not happening correctly during DCR transformation and this is happening due to DCR is not supported and will reach the respective backend team about this issue.

**Comment by v-muuppugund** [comment] 2024-02-27 01:10
Hi @FormindMPO , I analyzed the logs again for  Parse-kv issue as discussed in last call its Transformation issue and not supported,Will be reaching the backend team on this issue, will share once we have an update.

**Comment by v-muuppugund** [comment] 2024-03-18 12:04
Hi @FormindMPO ,Hi <<Author>>,we are reaching out to the concerned team for this issue, once we receive an update on this over an email or loop once have an update from the team,we are closing your issue (https://github.com/Azure/Azure-Sentinel/issues/9792) as per our standard operating procedures. If you still need support for this issue, feel free to re-open at any time. Thank you for your co-operation!

**Closed by v-muuppugund** 2024-03-18 12:04 UTC
Labels: Config issue

**Comment by JustinGrote** [comment] 2024-09-26 16:23
Ran into this same issue, very annoyed parse-kv doesn't work. Thanks @FormindMPO for at least identifying that regex works.
```
Syslog
| where ProcessName startswith "meraki-ip_flow"
| parse-kv SyslogMessage as (
	src:string,
	dst:string,
	protocol:string,
	sport:int,
	dport:int,
	translated_src_ip:string,
	translated_dst_ip:string,
	translated_port:int
) with (pair_delimiter=" ", kv_delimiter="=")
```
