### ISSUE TITLE
Get-AlienVault_OTX_V2 confidence score limiting threat indicators that are added

### ISSUE THREAD

**Issue by over2under3** [Azure/Azure-Sentinel#5543] opened 2022-07-04 14:54 UTC
**Describe the bug**
I was able to successfully setup Get-AlienVault_OTX_V2 playbook and run it successfully.  I have the confidence score set to "25" and all the indicators that match a confidence score of "25" are successfully added to the Sentinel Threat Indicators.

The problem is ONLY the indicators with a threat score of "25" are added but nothing with a score above this is added. I was under the impression that "25" was a minimum score that has to be met for the indicator to get added.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by teachjing** [comment] 2022-07-13 19:16
Reaching out to author to add a parameter to handle a score greater than a certain numeric value. @AndrewBlumhardt

**Comment by v-rbajaj** [comment] 2023-06-07 12:20
Hi @over2under3, We wanted to check on the status of Issue https://github.com/Azure/Azure-Sentinel/issues/5543. The issue is pending for more than expected days. Please let us know if you need any assistance to review this Issue. As per our standard operating procedures if no response is received in the next 7 business days, we will close this Issue. Thank you for your cooperation.

**Comment by v-vdixit** [comment] 2023-06-15 05:23
Since we have not received a response in the last 7 days, we are closing your issue as per our standard operating procedures. If you still need support for this issue, feel free to re-open at any time. Thank you for your co-operation.

**Closed by v-vdixit** 2023-06-15 05:23 UTC
Labels: Investigating, Playbook
