### ISSUE TITLE
missing data - SPO/TEAMS

### ISSUE THREAD

**Issue by funzel1** [Azure/Azure-Sentinel#6569] opened 2022-11-07 11:03 UTC
**Describe the bug**
No data for SPO since two months  on two tenants, delay with Teams data

**To Reproduce**
1. Go to your Analytics workspace
2. run query
O365API_CL
|summarize by Workload_s

Output:

Workload_s
Aip
CRM
SecurityComplianceCenter
MicrosoftForms
PowerApps
PublicEndpoint

------------------------
data for SPO (last event 2 months old), for Teams last event 24 hours old
**Expected behavior**
last event for SPO and teams should have 30 min age as output with running query

**Comment by funzel1** [comment] 2022-11-07 12:34
Maybe related to Purview rollout ?

**Comment by v-rucdu** [comment] 2023-01-06 10:46
@funzel1 : This seems to be a very old problem, and this connector may have already had numerous updates, can you please check and confirm if your problem has been solved? Thanks!!

**Comment by funzel1** [comment] 2023-01-06 12:36
Hello @v-rucdu 
how check the version ?
What we got in parallel, we run into a limitation the count of operations is more as 500, so we have splitted api in services bases packages like one for Microsoft Forms only.

**Comment by v-rbajaj** [comment] 2023-06-06 05:37
Hi @funzel1, 
are you still facing this issue?

**Comment by v-rbajaj** [comment] 2023-06-07 11:54
We wanted to check on the status of Issue https://github.com/Azure/Azure-Sentinel/issues/6569. The issue is pending for more than the expected days. Please let us know if you need any assistance to review this Issue. As per our standard operating procedures if no response is received in the next 7 business days, we will close this Issue. Thank you for your cooperation.

**Comment by v-vdixit** [comment] 2023-06-15 05:41
Hi @6569 since we have not received a response in the last 7 days, we are closing your issue as per our standard operating procedures. If you still need support for this issue, feel free to re-open at any time. Thank you for your co-operation.

**Closed by v-vdixit** 2023-06-15 05:41 UTC
Labels: Connector
